### ISSUE TITLE
Tooltips in Character Preferences Popout Menus Layer Below Menu

### ISSUE THREAD

**Issue by TealSeer** [Bubberstation/Bubberstation#1005]
## Issue Summary
If you open the menu to change your e.g. hair, facial hair, undershirt, etc. in character preferences and hover over the options, the tooltip showing the name of the option you're hovering over appears below the menu and in most cases isn't readable. After some investigation it looks like the issue appeared in https://github.com/Bubberstation/Bubberstation/commit/1a955f563bae34573067dc8ae258155ad2808151
![image](https://github.com/Bubberstation/Bubberstation/assets/75404941/3d27ac2b-1895-4677-a5c6-ebba3afa16b6)

## Round ID:
N/A (has happened every round I've played)

## Testmerges:
N/A

## Reproduction:
- Compile and run code after https://github.com/Bubberstation/Bubberstation/commit/1a955f563bae34573067dc8ae258155ad2808151
- Open character setup menu
- Click to open menu for modifying hairstyle
- Note tooltip position

**Comment by Majkl-J** [comment]
Fixed with upstream merge
