### ISSUE TITLE
Service guard has access to a total of 0 service areas, and service baton cant recharge.in most service areas

### ISSUE THREAD

**Issue by nikothedude** [Bubberstation/Bubberstation#1013]
Reporting client version: 515.1609

## Issue Summary

Title. The baton just doesnt recharge in any service place I've found.

## Round ID:
3312

## Testmerges:
- [bubber always message staffchat ahelps](https://github.com/Bubberstation/Bubberstation/pull/935)
- [Nerfs most modsuits by giving them all armour boosters](https://github.com/Bubberstation/Bubberstation/pull/910)
- [[Early Mirror] Server announcements are no longer ock ick](https://github.com/Bubberstation/Bubberstation/pull/965)
- [[Early Mirror] Tarkon Retarken, The great Atarkoining](https://github.com/Bubberstation/Bubberstation/pull/968)
- [Contractor and Ninja Modsuits have a deployable microbomb (Enable the DNA lock and hit Lock on the modsuit to arm)](https://github.com/Bubberstation/Bubberstation/pull/625)
- [Ports Bloopers (Vocal Barks) from FluffySTG](https://github.com/Bubberstation/Bubberstation/pull/987)
- [[Will be MODULAR] Adds back TEG ](https://github.com/Bubberstation/Bubberstation/pull/798)
- [The Tajara DLC! Finishes Tajara up to be an actual species now.](https://github.com/Bubberstation/Bubberstation/pull/962)
- [[Do not merge] removes headsets from ghost cafe](https://github.com/Bubberstation/Bubberstation/pull/990)
- [Adds Moon Station: AKA Burgerstation 2](https://github.com/Bubberstation/Bubberstation/pull/921)

## Reproduction:

Step 1: Be service guard
Step 2: Try to open bar, or kitchen, or anything
Step 3: Fail

Step 1: Get a service baton
Step 2: Expend charges
Step 3: Be unable to refresh its charges

I could be doing something wrong, but having no access to ANY PART OF SERVICE seems a bit WEIRD.

**Comment by Majkl-J** [comment]
Which map was this on?

**Comment by nikothedude** [comment]
> Which map was this on?

Meta

Also, 2 things that I didn't remember til now:
1. The baton actually did recharge, just only in the area of the bar behind the counter
2. The hop said my Id was fucked, supported by the fact that the Id had no image

I maintain the baton thing is some measure of bug   since the baton should work in all service areas, but the Id could've been a isolated incident

**Comment by Majkl-J** [comment]
Fixed with upstream merge
