### ISSUE TITLE
Ashwalker tendril doesn't heal ashwalkers currently; it gibs them.

### ISSUE THREAD

**Issue by thegrb93** [Bubberstation/Bubberstation#1048]
## Issue Summary
Sleeping beside the ashwalker tendril is supposed to heal ashwalkers but it gibs them currently.

**Comment by thegrb93** [comment]
Should be fixed by https://github.com/Skyrat-SS13/Skyrat-tg/commit/9092c186acb0da47ebcaba45776bc14a4a44d80f

**Comment by Majkl-J** [comment]
Care to check if this has been fixed?

**Comment by thegrb93** [comment]
Yeah its fixed
