### ISSUE TITLE
Imaginary friend is invisible/inaudible to host, cannot move / teleport/tether to them either.

### ISSUE THREAD

**Issue by SpiritAngler** [Bubberstation/Bubberstation#1051]
## Issue Summary

Basically the title. Imaginary friend seems gigabugged- spammed requests, nothing on host's end, no ability to move / teleport to them.

## Round ID:

3368

## Testmerges:

Round ID: 3368
BYOND Version: 515.1616
Server revision compiled on: 2024-01-21T01:19:35+00:00
Master commit: [40ff0601354aabd5a8fbef4b2b78962ec8ac2e88](https://github.com/Bubberstation/Bubberstation/commit/40ff0601354aabd5a8fbef4b2b78962ec8ac2e88)
The following pull requests are currently test merged:
[#935: 'bubber always message staffchat ahelps' by nevimer at commit 4c8172eb1c](https://github.com/Bubberstation/Bubberstation/pull/935)
[#965: '[Early Mirror] Server announcements are no longer ock ick' by lessthnthree at commit e5cc02e2d0](https://github.com/Bubberstation/Bubberstation/pull/965)
[#968: '[Early Mirror] Tarkon Retarken, The great Atarkoining' by Erol509 at commit e91f203939](https://github.com/Bubberstation/Bubberstation/pull/968)
[#625: 'Contractor and Ninja Modsuits have a deployable microbomb (Enable the DNA lock and hit Lock on the modsuit to arm)' by nevimer at commit 1a9af007c8](https://github.com/Bubberstation/Bubberstation/pull/625)
[#987: 'Ports Bloopers (Vocal Barks) from FluffySTG' by shayoki at commit a645f6e07f](https://github.com/Bubberstation/Bubberstation/pull/987)
[#962: 'The Tajara DLC! Finishes Tajara up to be an actual species now.' by pixelkitty286 at commit 512d55133f](https://github.com/Bubberstation/Bubberstation/pull/962)
[#990: '[Do not merge] removes headsets from ghost cafe' by StrangeWeirdKitten at commit 121b897f44](https://github.com/Bubberstation/Bubberstation/pull/990)
[#1031: 'Fixes headshot stuff' by Majkl-J at commit 4a8f1b89c2](https://github.com/Bubberstation/Bubberstation/pull/1031)
[#1006: 'blocks 1626 [DO NOT MERGE]' by nevimer at commit f5faf6fde4](https://github.com/Bubberstation/Bubberstation/pull/1006)
[#456: 'Storyteller port from horizon [DNM]' by nevimer at commit 9964d43f58](https://github.com/Bubberstation/Bubberstation/pull/456)

Local commit: a229d954ee32c1e7bd9ad8d24940c67e3d697a4d
TGS version: 5.18.1
DMAPI version: 5.7.0

## Reproduction:

Spawn as an imaginary friend. Do less than the nothing that is normal. Profit.

**Comment by Majkl-J** [comment]
Seems to be fixed
