### ISSUE TITLE
Psyker Bitrunning Domains Crash Constantly

### ISSUE THREAD

**Issue by CMDR-Gungnir** [Bubberstation/Bubberstation#1065]
Reporting client version: 515.1623

## Issue Summary

I'm not sure if this is a TG issue or something caused by here, I haven't tested, I can move the issue report upstream if needed, but the two Psyker domains in Bitrunning just cause the game to freeze and crash constantly. They are functionally unplayable, and if you accidentally get one before you have upgrades (to know what's what) you pretty much just have to accept the loss of stars, because while you CAN clear them you will be lagging and crashing constantly.

## Round ID:
3394

## Testmerges:
- [bubber always message staffchat ahelps](https://github.com/Bubberstation/Bubberstation/pull/935)
- [[Early Mirror] Server announcements are no longer ock ick](https://github.com/Bubberstation/Bubberstation/pull/965)
- [[Early Mirror] Tarkon Retarken, The great Atarkoining](https://github.com/Bubberstation/Bubberstation/pull/968)
- [Contractor and Ninja Modsuits have a deployable microbomb (Enable the DNA lock and hit Lock on the modsuit to arm)](https://github.com/Bubberstation/Bubberstation/pull/625)
- [Ports Bloopers (Vocal Barks) from FluffySTG](https://github.com/Bubberstation/Bubberstation/pull/987)
- [The Tajara DLC! Finishes Tajara up to be an actual species now.](https://github.com/Bubberstation/Bubberstation/pull/962)
- [[Do not merge] removes headsets from ghost cafe](https://github.com/Bubberstation/Bubberstation/pull/990)
- [Fixes headshot stuff](https://github.com/Bubberstation/Bubberstation/pull/1031)
- [blocks 1626 [DO NOT MERGE]](https://github.com/Bubberstation/Bubberstation/pull/1006)
- [Adds Cargo shelves from Shiptest, makes Skyrat modular shelves buildable](https://github.com/Bubberstation/Bubberstation/pull/992)
- [Ports F3-LINE borgs!](https://github.com/Bubberstation/Bubberstation/pull/1055)
- [Removes barber templates, adds new NTR offices](https://github.com/Bubberstation/Bubberstation/pull/1003)
- [Storyteller port from horizon [DNM]](https://github.com/Bubberstation/Bubberstation/pull/456)

## Reproduction:

1) Go Bitrunning
2) Choose Crate Chaos or Infected Domain (I tihnk those are the two's names?)
3) Crash and DC constantly.

**Comment by CMDR-Gungnir** [comment]
Further experimenting seems to have this only being an issue when all three Bitrunners were in at the same time? It's gotten somewhat better in recent times, but it's not perfect, either, but it's ONLY these domains.

I have no idea what to suggest, in all honesty, because even the Three Bitrunners thing isn't entirely perfect, as I've had it happen in the past when it was just me.

**Comment by Majkl-J** [comment]
I've bitran a fair bit recently and couldn't reproduce it, this was probably fixed. Was a bug with how the overlay was rendered and tg optimized it a lot
