### ISSUE TITLE
DRAGNET's netting mode doesn't deal stamina damage.

### ISSUE THREAD

**Issue by mikederkan** [Bubberstation/Bubberstation#1067]
## Issue Summary

Title. It should deal 10 stamina damage per "net", 6 "net"s per shot.

## Reproduction:

Shoot someone with a DRAGnet set to netting.

**Comment by Majkl-J** [comment]
![image](https://github.com/Bubberstation/Bubberstation/assets/49160555/c7539da0-ea5d-4235-ab7f-0b1057cb1f50)

Tg did a widdle oopsie :3
