### ISSUE TITLE
Can't put items in display case

### ISSUE THREAD

**Issue by ReynTheLord** [Bubberstation/Bubberstation#1073]
Reporting client version: 515.1623

## Issue Summary
 When I try to put items in the display cases in the library it wont work

## Round ID:
3406

## Testmerges:
- [bubber always message staffchat ahelps](https://github.com/Bubberstation/Bubberstation/pull/935)
- [[Early Mirror] Server announcements are no longer ock ick](https://github.com/Bubberstation/Bubberstation/pull/965)
- [[Early Mirror] Tarkon Retarken, The great Atarkoining](https://github.com/Bubberstation/Bubberstation/pull/968)
- [Contractor and Ninja Modsuits have a deployable microbomb (Enable the DNA lock and hit Lock on the modsuit to arm)](https://github.com/Bubberstation/Bubberstation/pull/625)
- [Ports Bloopers (Vocal Barks) from FluffySTG](https://github.com/Bubberstation/Bubberstation/pull/987)
- [The Tajara DLC! Finishes Tajara up to be an actual species now.](https://github.com/Bubberstation/Bubberstation/pull/962)
- [[Do not merge] removes headsets from ghost cafe](https://github.com/Bubberstation/Bubberstation/pull/990)
- [Fixes headshot stuff](https://github.com/Bubberstation/Bubberstation/pull/1031)
- [blocks 1626 [DO NOT MERGE]](https://github.com/Bubberstation/Bubberstation/pull/1006)
- [Adds Cargo shelves from Shiptest, makes Skyrat modular shelves buildable](https://github.com/Bubberstation/Bubberstation/pull/992)
- [Removes barber templates, adds new NTR offices](https://github.com/Bubberstation/Bubberstation/pull/1003)
- [Storyteller port from horizon [DNM]](https://github.com/Bubberstation/Bubberstation/pull/456)

## Reproduction: 
I attempted to use the key for the curator's display cases, it said it went into historian mode. Empty hand on it just opens a UI, not sure what to do there. Tried clicking an item onto the display case, didnt work. Tried clicking on the UI, didnt work. It says to "Replace holographic trophy" And doesnt say how

**Comment by Majkl-J** [comment]
Use an ID on them
