### ISSUE TITLE
Safety incident display is displaying likely incorrect values

### ISSUE THREAD

**Issue by ReynTheLord** [Bubberstation/Bubberstation#1074]
Reporting client version: 515.1623

## Issue Summary
 I highly doubt  that we went 95 rounds without a delam and had 63 tram collisions on VOIDRAPTOR of all maps
![image](https://github.com/Bubberstation/Bubberstation/assets/37010048/d465e6bd-a346-4205-8efa-f922eb205a23)

## Round ID:
3406

## Testmerges:
- [bubber always message staffchat ahelps](https://github.com/Bubberstation/Bubberstation/pull/935)
- [[Early Mirror] Server announcements are no longer ock ick](https://github.com/Bubberstation/Bubberstation/pull/965)
- [[Early Mirror] Tarkon Retarken, The great Atarkoining](https://github.com/Bubberstation/Bubberstation/pull/968)
- [Contractor and Ninja Modsuits have a deployable microbomb (Enable the DNA lock and hit Lock on the modsuit to arm)](https://github.com/Bubberstation/Bubberstation/pull/625)
- [Ports Bloopers (Vocal Barks) from FluffySTG](https://github.com/Bubberstation/Bubberstation/pull/987)
- [The Tajara DLC! Finishes Tajara up to be an actual species now.](https://github.com/Bubberstation/Bubberstation/pull/962)
- [[Do not merge] removes headsets from ghost cafe](https://github.com/Bubberstation/Bubberstation/pull/990)
- [Fixes headshot stuff](https://github.com/Bubberstation/Bubberstation/pull/1031)
- [blocks 1626 [DO NOT MERGE]](https://github.com/Bubberstation/Bubberstation/pull/1006)
- [Adds Cargo shelves from Shiptest, makes Skyrat modular shelves buildable](https://github.com/Bubberstation/Bubberstation/pull/992)
- [Removes barber templates, adds new NTR offices](https://github.com/Bubberstation/Bubberstation/pull/1003)
- [Storyteller port from horizon [DNM]](https://github.com/Bubberstation/Bubberstation/pull/456)

## Reproduction:
 I have no clue matey

**Comment by Majkl-J** [comment]
Probably admins messing with the tram crash global values because I can't repro this. The SM stuff was legit though
