### ISSUE TITLE
Body swap anomaly as Teshari does not get fixed in a S.A.D

### ISSUE THREAD

**Issue by DiscordWizard** [Bubberstation/Bubberstation#1079]
## Issue Summary

After being hit with a body part swapping anomaly I had my arm turned into a skeleton's. After hopping into a S.A.D and accepting to be changed back into what my character was in the preferences menu, the arm was not fixed, it remained a skeleton arm.

I'd argue for the removal of an anomaly that messes with character body parts directly honestly.

## Reproduction:

Touch body swapping anomaly, get one of your limbs turned into a skeleton's (Haven't tried with anything else, maybe still breaks maybe not), walk into a S.A.D and try to have it fix you.

**Comment by YakumoChen** [comment]
duplicate issue #1052
