### ISSUE TITLE
Eating bodies as a transmutated space dragon round removes them.

### ISSUE THREAD

**Issue by MrZoraman** [Bubberstation/Bubberstation#1086]
## Issue Summary
If you transmutate into a space dragon, then eat a dead body, that body is destroyed. It does not come back when you morph back into a human.

## Reproduction:
1. Use the transmutation belt thing to turn into a space dragon
2. Eat a dead body
3. Turn back into a human.

It is expected that any bodies eaten should be ejected. Instead, they are deleted. The owners of those bodies are now round removed.

**Comment by projectkepler-ru** [comment]
@Majkl-J I recall you were fixing this?

**Comment by Majkl-J** [comment]
There's a PR up on tg but it's in the deep pits of hell

**Comment by Majkl-J** [comment]
Fixed on tg, will get it here soon
