### ISSUE TITLE
praetorian is comically bad

### ISSUE THREAD

**Issue by zeratino** [Bubberstation/Bubberstation#1119]
## Issue Summary

armor values are locked at a one or two
![image](https://github.com/Bubberstation/Bubberstation/assets/71103211/4c17ba26-4839-439d-86c9-51b7a6f47e54)

![image](https://github.com/Bubberstation/Bubberstation/assets/71103211/e08bbac0-db22-4b9a-abcb-65e3a32646b3)
with armor booster

-

![image](https://github.com/Bubberstation/Bubberstation/assets/71103211/6f72a06a-bd8b-49d6-a31c-9ea3c30bf56d)

blueshield armor for reference

## Testmerges:

[#935: 'bubber always message staffchat ahelps' by nevimer at commit 4c8172eb1c](https://github.com/Bubberstation/Bubberstation/pull/935)
[#965: '[Early Mirror] Server announcements are no longer ock ick' by lessthnthree at commit 761cea47a0](https://github.com/Bubberstation/Bubberstation/pull/965)
[#968: '[Early Mirror] Tarkon Retarken, The great Atarkoining' by Erol509 at commit 0f7d83df7e](https://github.com/Bubberstation/Bubberstation/pull/968)
[#625: 'Contractor and Ninja Modsuits have a deployable microbomb (Enable the DNA lock and hit Lock on the modsuit to arm)' by nevimer at commit 1a9af007c8](https://github.com/Bubberstation/Bubberstation/pull/625)
[#987: 'Ports Bloopers (Vocal Barks) from FluffySTG' by shayoki at commit 3b2ee3fdd2](https://github.com/Bubberstation/Bubberstation/pull/987)
[#962: 'The Tajara DLC! Finishes Tajara up to be an actual species now.' by pixelkitty286 at commit 6843316b48](https://github.com/Bubberstation/Bubberstation/pull/962)
[#990: '[Do not merge] removes headsets from ghost cafe' by StrangeWeirdKitten at commit 121b897f44](https://github.com/Bubberstation/Bubberstation/pull/990)
[#1031: 'Fixes headshot stuff' by Majkl-J at commit 4a8f1b89c2](https://github.com/Bubberstation/Bubberstation/pull/1031)
[#1006: 'blocks 1626 [DO NOT MERGE]' by nevimer at commit f5faf6fde4](https://github.com/Bubberstation/Bubberstation/pull/1006)
[#456: 'Storyteller port from horizon [DNM]' by nevimer at commit 62d4b20378](https://github.com/Bubberstation/Bubberstation/pull/456)
[#840: 'Reverts a few of the security alert sounds back to SR's' by iliyaxox at commit 24d0c80ab6](https://github.com/Bubberstation/Bubberstation/pull/840)
[#1103: 'Fixes double deathgasp and most simplemobs not deathgasping' by NithaIsTired at commit ef4018f32d](https://github.com/Bubberstation/Bubberstation/pull/1103)
[#1108: 'force atmos hack' by nevimer at commit 02b7fb567f](https://github.com/Bubberstation/Bubberstation/pull/1108)
[#1010: 'Logged out ghosts get sent back into the lobby' by Majkl-J at commit a8a7f36ea0](https://github.com/Bubberstation/Bubberstation/pull/1010)
[#1110: '[DNM] Revert "Makes roundending significantly harder by making the brain (Almost) indestructible"' by nevimer at commit 83614c5a6e](https://github.com/Bubberstation/Bubberstation/pull/1110)
[#1061: 'A bunch of bloodsucker changes' by Arturlang at commit 74c0d220aa](https://github.com/Bubberstation/Bubberstation/pull/1061)
[#1118: 'Fix Cortical Borer Chemicals (Test and Take Upstream)' by nevimer at commit e483cdd695](https://github.com/Bubberstation/Bubberstation/pull/1118)
## Reproduction:

play blueshield
pick up the modsuit, laugh

**Comment by YakumoChen** [comment]
not a bug

**Comment by Majkl-J** [comment]
Intentional. Just don't bluesec
