### ISSUE TITLE
Customs agent does not have access to the "Cargo Cell" airlock, in the cargo guard office, on metastation

### ISSUE THREAD

**Issue by nikothedude** [Bubberstation/Bubberstation#1138]
Reporting client version: 515.1630

## Issue Summary

Title. 

## Round ID:
3548

## Testmerges:
- [bubber always message staffchat ahelps](https://github.com/Bubberstation/Bubberstation/pull/935)
- [[Early Mirror] Server announcements are no longer ock ick](https://github.com/Bubberstation/Bubberstation/pull/965)
- [[Early Mirror] Tarkon Retarken, The great Atarkoining](https://github.com/Bubberstation/Bubberstation/pull/968)
- [Contractor and Ninja Modsuits have a deployable microbomb (Enable the DNA lock and hit Lock on the modsuit to arm)](https://github.com/Bubberstation/Bubberstation/pull/625)
- [Ports Bloopers (Vocal Barks) from FluffySTG](https://github.com/Bubberstation/Bubberstation/pull/987)
- [The Tajara DLC! Finishes Tajara up to be an actual species now.](https://github.com/Bubberstation/Bubberstation/pull/962)
- [[Do not merge] removes headsets from ghost cafe](https://github.com/Bubberstation/Bubberstation/pull/990)
- [Fixes headshot stuff](https://github.com/Bubberstation/Bubberstation/pull/1031)
- [blocks 1626 [DO NOT MERGE]](https://github.com/Bubberstation/Bubberstation/pull/1006)
- [Storyteller port from horizon [DNM]](https://github.com/Bubberstation/Bubberstation/pull/456)
- [Reverts a few of the security alert sounds back to SR's](https://github.com/Bubberstation/Bubberstation/pull/840)
- [Fixes double deathgasp and most simplemobs not deathgasping](https://github.com/Bubberstation/Bubberstation/pull/1103)
- [force atmos hack](https://github.com/Bubberstation/Bubberstation/pull/1108)
- [Fix Cortical Borer Chemicals (Test and Take Upstream)](https://github.com/Bubberstation/Bubberstation/pull/1118)
- [A bunch of bloodsucker changes](https://github.com/Bubberstation/Bubberstation/pull/1061)
- [Adds wounds to the medical huds](https://github.com/Bubberstation/Bubberstation/pull/1123)
- [[NO GBP] [MANUAL MIRROR] Mirrors 4 synth wound PRs from skyrat, made by yours truely](https://github.com/Bubberstation/Bubberstation/pull/1120)

## Reproduction:

Just try opening it as a customs agent, you cant.

**Comment by JagOfTroy** [comment]
Tried to reproduce this error on current build of MetaStation.dmm, Customs Agent had access to all appropriate doors as they should.
This may be fixed already and can be considered closed.
