### ISSUE TITLE
Space Pirates failing to spawn

### ISSUE THREAD

**Issue by GoreDem** [Bubberstation/Bubberstation#1142]
## Issue Summary

Storyteller spawned space pirates failed to spawn during a round, no paper or announcement was given but it was announced to ghosts/admins
Later admins spawned pirates to 'fix' the issue and those worked fine
![image](https://github.com/Bubberstation/Bubberstation/assets/58603746/ffca3702-b106-474c-8ffc-ec4212c8e188)
(Mate Solarbilge in the image is unrelated, from a bitrunner ruin)

## Round ID:

3554

## Testmerges:

https://github.com/Bubberstation/Bubberstation/pull/456

## Reproduction:

Difficult, as the exact cause I don't know and might just be storyteller shitting itself which might take a while to test

Ghost on a local/the actual server and wait for pirates to spawn, on a local server I believe the rates could be adjusted to see if it's broken.

**Comment by ReturnToZender** [comment]
Wanted to mention the reason provided by admin logs appears to be that there are no gangs listed, whatever that means

**Comment by Majkl-J** [comment]
Seems to have been fixed with upstream
