### ISSUE TITLE
Clicking on people as a ghost shows their security records instead of their quirks.

### ISSUE THREAD

**Issue by MrZoraman** [Bubberstation/Bubberstation#1157]
## Issue Summary
Clicking on a person as a ghost shows their security records instead of their quirks, as if I had a sec HUD on.

## Reproduction:

1. Be a ghost.
2. Left click a living being.
3. You will see their sec records. Expected behavior: their quirks should be listed.

**Comment by Majkl-J** [comment]
Fixed upstream by yours truly, and deployed here a few days ago
