### ISSUE TITLE
Couple issues with materials and machines.

### ISSUE THREAD

**Issue by Drayco84** [Bubberstation/Bubberstation#1158]
### 1: ORM and boulder refinery won't accept diamond ore nor sand, don't know about volcanic ash.
I don't know if this was because something in the code got borked with the boulder mining mechanics update, or if the round was getting unstable. But, the ORM kept refusing to take and refine diamond ore and sand and the boulder refinery which says it's supposed to accept non-mineral materials was also refusing to take the items.

### 2: ORM, techfab (Cargo, at least.), and autolathes are not accepting glass sheets as materials.
Could not get any of those machines to take back glass sheets for whatever reason, despite the fact that they always did before.

## Round ID:
3583

## Testmerges:
The following pull requests are currently test merged:
[#456: 'Storyteller port from horizon [DNM]' by nevimer at commit a57ba285ac](https://github.com/Bubberstation/Bubberstation/pull/456)
[#625: 'Contractor and Ninja Modsuits have a deployable microbomb (Enable the DNA lock and hit Lock on the modsuit to arm)' by nevimer at commit 1a9af007c8](https://github.com/Bubberstation/Bubberstation/pull/625)
[#677: 'round end credits' by nevimer at commit 29424afc4e](https://github.com/Bubberstation/Bubberstation/pull/677)
[#962: 'The Tajara DLC! Finishes Tajara up to be an actual species now.' by pixelkitty286 at commit 2976beeeb1](https://github.com/Bubberstation/Bubberstation/pull/962)
[#1031: 'Fixes headshot stuff' by Majkl-J at commit 4a8f1b89c2](https://github.com/Bubberstation/Bubberstation/pull/1031)
[#987: 'Ports Bloopers (Vocal Barks) from FluffySTG' by shayoki at commit 63e34b389a](https://github.com/Bubberstation/Bubberstation/pull/987)
[#1120: '[NO GBP] [MANUAL MIRROR] Mirrors 4 synth wound PRs from skyrat, made by yours truely' by nikothedude at commit a6e09fe0c4](https://github.com/Bubberstation/Bubberstation/pull/1120)
[#1125: 'Fixes borers in mobs getting blasted by weather' by Arturlang at commit a62e37d484](https://github.com/Bubberstation/Bubberstation/pull/1125)
[#1118: 'Fix Cortical Borer Chemicals (Test and Take Upstream)' by nevimer at commit e483cdd695](https://github.com/Bubberstation/Bubberstation/pull/1118)
[#1155: 'Sandstorms on Moon Station are less annoying + Other QoL' by BurgerLUA at commit 056d03ba32](https://github.com/Bubberstation/Bubberstation/pull/1155)
[#1145: '[TEST MERGE ONLY] [EARLY MIRROR] [SEMIMODULAR] Fixes multi-bodytype characters (digitigrade, species custom) only having digi apply when custom could be applied' by nikothedude at commit 50683595c3](https://github.com/Bubberstation/Bubberstation/pull/1145)
[#1156: '[MIRROR] Fixes high power consumption for lathes (#26446)' by Majkl-J at commit e05683ff97](https://github.com/Bubberstation/Bubberstation/pull/1156)

## Reproduction:

1: Dump diamond ore and sand on the input tile of an ORM and watch it slide through the machine. (I tried two different ORMs, BTW. One that was pre-built and linked, and one that I built myself but was unlinked.) Put diamond ore and sand in front of the boulder refinery and watch it stay there.

2: Try to put glass sheets into an ORM, autolathe, or techfab and get the message that the machine rejects the material.

**Comment by projectkepler-ru** [comment]
oh boy

**Comment by Majkl-J** [comment]
Fixed a while back with an upstream mirror
