### ISSUE TITLE
Lizard Bloodsuckers cannot adjust body temperature.

### ISSUE THREAD

**Issue by BurgerLUA** [Bubberstation/Bubberstation#1180]
## Issue Summary

Basically if you're warm, you will be warm forever and it will never go down naturally.
If you're cold, you will be cold forever and it will never go down naturally.

Basically if you're set on fire once or hit by a cold beam, you're fucked forever unless you have coffee or soda on you.

## Reproduction:

Be lizard bloodsucker.
Get set on fire once.
Forever burning and taking burn damage.

**Comment by Arturlang** [comment]
fixed, also made coffins set your temperature to normal
