### ISSUE TITLE
Ventrue's clan Objective is not counts as finished

### ISSUE THREAD

**Issue by delingar** [Bubberstation/Bubberstation#1208]
## Issue Summary

If you as Bloodsucked take a Ventrue clan, make your favourite vassal new Bloodsucker, Clan objective to create new bloodsucker will count failed

## Round ID:
3669

## Reproduction:

1. Become Bloodsucker
2. Pick Ventrue Clan
3. Make Vassal
4. Make this vassal Favourite
5. Upgrade Favourite vassal to Bloodsucker
6. End round
7. See, that your clan objective counts failed

**Comment by Arturlang** [comment]
Clan objectives not working properly is a known bug, sorry
