### ISSUE TITLE
Stacking 6 teshari kills the server's TIDI

### ISSUE THREAD

**Issue by Swiftfeather** [Bubberstation/Bubberstation#1230]
## Issue Summary

Title.

## Round ID:

3712

## Testmerges:

man idk

## Reproduction:

The server was lagging bad, ooc people said "maybe it's the 6 teshari" then they unstacked the 6 teshari and performance went right back to normal. I asked them to stack the 6 teshari again just to verify, and I watched htem IC stack the teshari and immediately as soon as they were stacked again performance tanked hardcore. This was done on live.

<img width="401" alt="image" src="https://github.com/Bubberstation/Bubberstation/assets/26744576/6ab283e9-50ae-4750-8549-dd6a129b1139">

**Comment by Cyprex** [comment]
Possibly echolocation, but we'll need to look at profiler info

**Comment by Majkl-J** [comment]
WHAT THE FUCK

**Comment by Majkl-J** [comment]
Just gonna ask zender to disallow carrying more than one, untestmerging https://github.com/Bubberstation/Bubberstation/pull/1131 until then

**Comment by trazodont** [comment]
> Just gonna ask zender to disallow carrying more than one, untestmerging #1131 until then

Hi as one of the people involved in the stack, we weren't using that quirk, we were aggro grabbing each other and then climbing up on each other's back one at a time.

![image](https://github.com/Bubberstation/Bubberstation/assets/97755577/b9f9f6dd-4d74-4234-90bb-38d0b4b172a7)
So Zucchini aggro grabs Sulfur, Sulfur climbs onto Zucchini's back, Sulfur aggro grabs Poptart, Poptart climbs up, ect.

**Comment by Cyprex** [comment]
Nevermind, it's not echolocation, that's not even testmerged

**Comment by Cyprex** [comment]
For future reference the verb show-server-revision will tell you testmerges and everything!

**Comment by Majkl-J** [comment]
> Hi as one of the people involved in the stack, we weren't using that quirk, we were aggro grabbing each other and then climbing up on each other's back one at a time.
> 
> ![image](https://private-user-images.githubusercontent.com/97755577/309379337-b9f9f6dd-4d74-4234-90bb-38d0b4b172a7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkzMjQ2MDEsIm5iZiI6MTcwOTMyNDMwMSwicGF0aCI6Ii85Nzc1NTU3Ny8zMDkzNzkzMzctYjlmOWY2ZGQtNGQ3NC00MjM0LTkwYmItMzhkMGI0YjE3MmE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAxVDIwMTgyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzNzc2NTU0YzMyYjA1OWQxYWMyOGM3ZjIzMDE1YmI0MjJjNjljNTBmZjQwNWY4YjUxY2M5ODNlNzUzNGNjMTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0d-Nlm8BLTg7rXQoIPgiJJNEbaSyLHYhYlzAYsqwyK8) So Zucchini aggro grabs Sulfur, Sulfur climbs onto Zucchini's back, Sulfur aggro grabs Poptart, Poptart climbs up, ect.

This used to be impossible to do so I am guessing something must've broken it. Zender's PR is very likely the culprit as it deals with all this code. So first part is checking if that's behind it after that guess I'll have to debug it proper

**Comment by Swiftfeather** [comment]
might be the piggyback quirk

**Comment by Majkl-J** [comment]
There is ANOTHER????

**Comment by ReturnToZender** [comment]
> There is ANOTHER????

The piggyback action is something that can be done by anyone, one of the original users said that was how they do it. Unsure if you can stack multiple people using the lift quirk, it uses the same code used by the fireman's carry so I doubt it

**Comment by trazodont** [comment]
> > There is ANOTHER????
> 
> The piggyback action is something that can be done by anyone, one of the original users said that was how they do it. Unsure if you can stack multiple people using the lift quirk, it uses the same code used by the fireman's carry so I doubt it, unless this is ALSO possible with the fireman's carry and it's a potential bug upstream

Carrying multiple people via piggyback has been a thing for a while, I remember doing it with at least 3 people like a year ago on SR. Pretty sure it just was never found until you put 6 teshari with a single braincell in front of each other to stack

BUT there's also a chance that something with the waddle quirk adds to it, since at least two of had the quirk.
