### ISSUE TITLE
Experimental seeds lack icon

### ISSUE THREAD

**Issue by Majkl-J** [Bubberstation/Bubberstation#1290]
## Issue Summary

Using a plant DNA manipulator to create seeds creates invisible seeds

## Round ID:

Any

## Testmerges:

N/A

## Reproduction:

1. Use a plant DNA manipulator to create seeds

2. It creates invisible seeds

**Comment by ReturnToZender** [comment]
This seems like an easy fix, I'll see if I can help any

**Comment by projectkepler-ru** [comment]
> This seems like an easy fix, I'll see if I can help any

Did you do it?
