### ISSUE TITLE
Abductor antagonist applies character prefs

### ISSUE THREAD

**Issue by Swiftfeather** [Bubberstation/Bubberstation#1336]
## Issue Summary

When abductors spawn in they're spawned in as disgusting half-breeds of the character's current prefs and abductor species. Abductors should always be 100% abductor and offer no respect to a char's prefs.

## Round ID:

Witnessed in multiple rounds for at least a month.

## Reproduction:

Multiple times witness abductors spawn with half of the player's character prefs applied. It's weird.

**Comment by YakumoChen** [comment]
https://github.com/Skyrat-SS13/Skyrat-tg/issues/11435

**Comment by projectkepler-ru** [comment]
@Majkl-J  still happening
