### ISSUE TITLE
Department lathes get stuck in the printing animation and become unsuable until reconstructed.

### ISSUE THREAD

**Issue by Swiftfeather** [Bubberstation/Bubberstation#1337]
## Issue Summary
Title

## Round ID:
Multiple rounds. I see it about once per day when I play

## Testmerges:
Don't think it's a TM I think it's with lathe changes from upstream.

## Reproduction:
I am not sure what causes this or how to reproduce it. I just know the lathes get stuck once in a while. Sometimes multiple times in a round.

**Comment by Majkl-J** [comment]
Should be fixed with upstream, reopen if not
