### ISSUE TITLE
Cargo Drone Menu is Busted

### ISSUE THREAD

**Issue by trazodont** [Bubberstation/Bubberstation#1342]
Reporting client version: 514.1589

## Issue Summary
![image](https://github.com/Bubberstation/Bubberstation/assets/97755577/60e03d2e-f311-458a-a498-235fc0347da7)
Can't control the drones if you can't use them in the first place.

## Round ID:
3966

## Testmerges:
- [round end credits](https://github.com/Bubberstation/Bubberstation/pull/677)
- [[Non-Modular Because Globalvars suck ass] Mirror-Nova: "Girl Dinner: Adds Mariinsky Ballet Company Chassis"](https://github.com/Bubberstation/Bubberstation/pull/1169)
- [Public Logging](https://github.com/Bubberstation/Bubberstation/pull/1203)
- [Ports BoxStation (NSSJourney) from FluffySTG](https://github.com/Bubberstation/Bubberstation/pull/1128)
- [[Nova Port] [TM ONLY; upstream pull] Frontier Tech finishes coming to Spinward!](https://github.com/Bubberstation/Bubberstation/pull/1282)
- [Reagent forging no longer makes healing completely free of charge](https://github.com/Bubberstation/Bubberstation/pull/1289)
- [Adds the DOTA suit and various extras](https://github.com/Bubberstation/Bubberstation/pull/1275)
- [Smooth the alcohol impairment curve because a bottle of vodka should last more than 5 minutes](https://github.com/Bubberstation/Bubberstation/pull/1115)
- [Lavaland Dauntless tweaks](https://github.com/Bubberstation/Bubberstation/pull/1301)
- [Storyteller port from horizon [DNM]](https://github.com/Bubberstation/Bubberstation/pull/456)
- [Nanite Slurry overdose heals organ damage in synthetics (with adjustments)](https://github.com/Bubberstation/Bubberstation/pull/1321)
- [[Semi-Modular] Adds back TEG ](https://github.com/Bubberstation/Bubberstation/pull/798)
- [Colossus bolts will gut you if you loose to them because I'm spiteful a salt PR broke my boy](https://github.com/Bubberstation/Bubberstation/pull/1340)
- [Removes security comms and access from blueshield](https://github.com/Bubberstation/Bubberstation/pull/1341)

**Comment by Majkl-J** [comment]
The menu's been fixed for a while now it seems
