### ISSUE TITLE
Quirk for different bare feet sounds

### ISSUE THREAD

**Issue by ronfino** [Bubberstation/Bubberstation#1381]
Add a neutral/negative quirk that makes your character footsteps sound different by using a preset of footsteps sound effects: Footsteps. Currently i'm using a full-on robot character but i hate it when it makes the sound of bare organic feet, a more metallic or at least jackboot sound effect would be better.

**Comment by nikothedude** [comment]
i dont think this is possible with how footsteps are coded but im not sure

**Comment by Majkl-J** [comment]
Feature requests belong in  the suggestions channel
