### ISSUE TITLE
Bubblegum Hallucination can break the coffin of a vampire sleeping within

### ISSUE THREAD

**Issue by Cyprex** [Bubberstation/Bubberstation#1384]
## Round ID: 4052

Bubblegum Hallucination can break the coffin of a vampire sleeping within.

I'm not sure what the proper fix for this is- but suppressing hallucinations entirely whilst in a coffin should work?

**Comment by Arturlang** [comment]
What the fuck?

**Comment by projectkepler-ru** [comment]
Remind me to check if something like this occur on TG
