### ISSUE TITLE
Allow Ghosts to possess and activate pAI cards?

### ISSUE THREAD

**Issue by Arriator** [Bubberstation/Bubberstation#140]
As someone very fond of using and playing pAIs, especially during lowpop hours, it'd be very cool if ghost players could possess them without requiring a master to grab a card and activate it, so the station can just have smaller companions running around for people like me that get bored, but not so much to load up a character. Thanks for all the hard work you've been doing to make this a pleasant and inviting space. <3

**Comment by ReturnToZender** [comment]
Adding a bounty here for $20 from server funds. I want to see this issue resolved.
