### ISSUE TITLE
Using Primitive Kitchen Alchemy to Produce Infinite Soupcans and Transmute Wood to Stone

### ISSUE THREAD

**Issue by fludd12** [Bubberstation/Bubberstation#1430]
## Issue Summary

Wood can be turned into storage barrels, a sane and reasonable crafting recipe, but deconstructing those has sent me down a chain of ever weirder material transmutations that has led to endless soup. Storage barrels deconstruct into clay bricks, a material which can be acquired in literally no other way. Clay bricks can be made into "clay ovens" or "clay ranges," which in actuality are *stone* ovens and *stone* stoves. These deconstruct into the same amount of stone used to create the appropriate kitchen implement as expected.

Notably, one can construct a stone stove, take the soup pot off of the stove, deconstruct the stove, and reconstruct it to get endless soup pots. These are listed as being made of metal, though I didn't have the opportunity to test if they could be broken down in an autolathe or recycler for materials.

## Reproduction:

Build two storage barrels out of wood, deconstruct them with a crowbar. The resulting clay bricks can be made into the aforementioned appliances, and deconstructed in the same way.

**Comment by ReturnToZender** [comment]
YOOO INFINITE SOUP GLITCH

**Comment by fludd12** [comment]
Why are we buying _soup pots_ at the **wood store?**

**Comment by ReturnToZender** [comment]
So full of soup pots yum

**Comment by Majkl-J** [comment]
I am losing it how the fuck is this a thing

**Comment by xXPawnStarrXx** [comment]
This should've been resolved by this PR: https://github.com/Skyrat-SS13/Skyrat-tg/pull/27477
