### ISSUE TITLE
Mold spiders suffocate because the mold eats the o2

### ISSUE THREAD

**Issue by Swiftfeather** [Bubberstation/Bubberstation#1475]
## Issue Summary

Mold spiders have this issue where they DIE because fungus needs o2 and makes co2 so it makes a fuckload of co2 in a room and kills all the spiders

**Comment by xXPawnStarrXx** [comment]
This should fix that.
https://github.com/Skyrat-SS13/Skyrat-tg/pull/27606

**Comment by Majkl-J** [comment]
Fixed upstream
