### ISSUE TITLE
Entombed Quirk Suit Selection Bugged 

### ISSUE THREAD

**Issue by trazodont** [Bubberstation/Bubberstation#1498]
Reporting client version: 515.1636

## Issue Summary

Attempting to selection a suit for the entombed quirk leaves it on default and does not save your selected choice!

## Round ID:
4274

## Testmerges:
- [round end credits](https://github.com/Bubberstation/Bubberstation/pull/677)
- [Storyteller port from horizon [DNM]](https://github.com/Bubberstation/Bubberstation/pull/456)
- [Adds Research cyborgs [Modularish] (oh no)](https://github.com/Bubberstation/Bubberstation/pull/1407)
- [Adds Big Black Fat Security Glocks](https://github.com/Bubberstation/Bubberstation/pull/1400)
- [Click First Combat (Part 2 | The Baton Knockdown Wallshove Combo)](https://github.com/Bubberstation/Bubberstation/pull/1453)
- [GAS 2 - Part 2 - The Sequel, the worm, what you have been waiting for](https://github.com/Bubberstation/Bubberstation/pull/1471)
- [[SEMI-MODULAR] More Kinetic Crushers (But this time it works)](https://github.com/Bubberstation/Bubberstation/pull/1479)
- [Box Station upkeep](https://github.com/Bubberstation/Bubberstation/pull/1483)
- [[WIP] Engineering Mishap Event](https://github.com/Bubberstation/Bubberstation/pull/1441)

**Comment by Colfer1** [comment]
This was fixed in this PR as far as I am aware.
https://github.com/Bubberstation/Bubberstation/pull/1582
