### ISSUE TITLE
THE BLUESHIELD DOES NOT GET AN OFFICE. ON EVERY MAP EXCEPT VOID RAPTOR.

### ISSUE THREAD

**Issue by neri-ventado** [Bubberstation/Bubberstation#15]
## Round ID:
219

## Testmerges:

[#10: 'Dynamic tweaks' by Cyprex at commit 764bc505d3](https://www.github.com/tgstation/tgstation/pull/10)
[#13: 'Blacksmithing!' by Gr33d-y at commit 06c598abe9](https://www.github.com/tgstation/tgstation/pull/13)

## Reproduction:
STEP ONE. LOG IN AS BLUESHIELD.

STEP TWO. SEE THIS.
![image](https://user-images.githubusercontent.com/71103211/216512259-6f30dca1-2955-4cab-ac15-f0f8760d39db.png)
AND THIS.
![image](https://user-images.githubusercontent.com/71103211/216512305-2422e866-7fd5-49c1-9470-0de3033e2817.png)

STEP THREE. CRY.

**Comment by theselfish** [comment]
This is because of Skyrat not wanting to keep readding their things to maps.

Instead of automapping in an office, they went with a locker.

**Comment by KathrinBailey** [comment]
guh???
