### ISSUE TITLE
Moon Station Science is Disconnected from distro

### ISSUE THREAD

**Issue by R3dtail** [Bubberstation/Bubberstation#1506]
## Issue Summary

The science Department on Moon Station is cut off from distro.  It's connected via waste, but the disconnects from distro happen by the circuitry lab and in the middle of robotics (I don't have a screenshot on hand I'll try and find one next time I play on Moon if this issue is still a thing by that point)

## Round ID:

Every Moon station round

## Reproduction:

Play on Moonstation

**Comment by ReturnToZender** [comment]
I just happen to be working on map updates right now, so uh, let me see if I can find this

**Comment by R3dtail** [comment]
> I just happen to be working on map updates right now, so uh, let me see if I can find this

Middle of Robotics lab, few tiles north of the surgery table, near that vicinity.  


Western most maintenance door in the circuitry lab.

**Comment by ReturnToZender** [comment]
> > I just happen to be working on map updates right now, so uh, let me see if I can find this
> 
> Middle of Robotics lab, few tiles north of the surgery table, near that vicinity.
> 
> Western most maintenance door in the circuitry lab.

Found them, will post PR soon

**Comment by ReturnToZender** [comment]
PR up, issue can be closed when merged :)
