### ISSUE TITLE
Infinite Damage Smithing weapons

### ISSUE THREAD

**Issue by KazooBard** [Bubberstation/Bubberstation#1512]
## Issue Summary
The Smithing items gain damage when perfectly hit. There is no hard cap to it. Bad hits regress the progress. Repeat for infinite damage.

## Reproduction:

Get max smithing, hit in pattern:
3 normal hits, two fast hits to proc bad hit
2 normal hits, two fast hits to proc bad hit

Repeat forever and hit it with perfects when ready.

**Comment by KazooBard** [comment]
![smithbug](https://github.com/Bubberstation/Bubberstation/assets/65713506/54ed465a-24c7-4437-adda-778c321c15b7)

**Comment by Majkl-J** [comment]
Whose fucking idea was this

**Comment by projectkepler-ru** [comment]
> Whose fucking idea was this

jj-park iirc

**Comment by xXPawnStarrXx** [comment]
I think there was meant to be a cap, but it's not working.

**Comment by projectkepler-ru** [comment]
> I think there was meant to be a cap, but it's not working.

No it's just poorly thought out code

**Comment by Arturlang** [comment]
Honestly, just give it a soft cap, not a hardcap

**Comment by Majkl-J** [comment]
Fixed upstream by yours truly

**Comment by xXPawnStarrXx** [comment]
> Fixed upstream by yours truly

Did you fix them being absolutely worthless after the first hit because the values drop so much?

**Comment by Majkl-J** [comment]
> > Fixed upstream by yours truly
> 
> Did you fix them being absolutely worthless after the first hit because the values drop so much?

The entire element no longer changes the force and just deals extra damage so yes, yes I did
