### ISSUE TITLE
Changeling Teshari are impossibly tiny for some reason

### ISSUE THREAD

**Issue by RareThrumbo** [Bubberstation/Bubberstation#1516]
## Issue Summary

If a Changeling shapeshifts into a Teshari, they become extremely small.

Additionally, if the Changeling's starting form was a Teshari, and they shift to something else and then back to their original form, using an SAD does not fix it. They remain permanently, irreversibly tiny.

This is a dead giveaway, as Teshari cannot become this small through any other method than this bug (as far as I know).

## Round ID:

N/A

## Reproduction:

1) Be a Changeling.
2) DNA sting a Teshari.
3) Shapeshift into that Teshari.
4) Lil baby man

![Screenshot 2024-05-14 232332](https://github.com/Bubberstation/Bubberstation/assets/32040673/380d6a88-1561-48ba-be39-c9dedfabf945)

**Comment by ReturnToZender** [comment]
LIL BABY MAN

**Comment by ReturnToZender** [comment]
I'm you, but smaller

**Comment by projectkepler-ru** [comment]
@Majkl-J  The changeling transformation code use your full pref so it can turn into the smallest possible sprite selection currently on it even if it does not normally work that way

**Comment by projectkepler-ru** [comment]
@Majkl-J still a problem
