### ISSUE TITLE
Anthromorph Asset Protection Chest Sprite Issue

### ISSUE THREAD

**Issue by rintherat** [Bubberstation/Bubberstation#1534]
## Issue Summary

As title explains. The chestplate becomes invisible on the anthromorph model (the player was a skunk tail user).

## Round ID:

4382

## Testmerges:

[#456: 'Storyteller port from horizon [DNM]' by nevimer at commit f3bd0c7ea4](https://github.com/Bubberstation/Bubberstation/pull/456)
[#1407: 'Adds Research cyborgs [Modularish] (oh no)' by pixelkitty286 at commit 8c6125009f](https://github.com/Bubberstation/Bubberstation/pull/1407)
[#1400: 'Adds Big Black Fat Security Glocks' by BurgerLUA at commit b945cedcfd](https://github.com/Bubberstation/Bubberstation/pull/1400)
[#1453: 'Click First Combat (Part 2 | The Baton Knockdown Wallshove Combo)' by StrangeWeirdKitten at commit 19aa819e65](https://github.com/Bubberstation/Bubberstation/pull/1453)
[#1471: 'GAS 2 - Part 2 - The Sequel, the worm, what you have been waiting for' by nevimer at commit 2fc4018ef4](https://github.com/Bubberstation/Bubberstation/pull/1471)
[#1479: '[SEMI-MODULAR] More Kinetic Crushers (But this time it works)' by Superhats at commit b3f8cf8c2b](https://github.com/Bubberstation/Bubberstation/pull/1479)
[#1441: '[WIP] Engineering Mishap Event' by nevimer at commit 082d62c529](https://github.com/Bubberstation/Bubberstation/pull/1441)
[#1502: '[EXPERIMENTAL and TM-ONLY] Atmos Hijinks - The hijinking' by Majkl-J at commit b4636a4fe0](https://github.com/Bubberstation/Bubberstation/pull/1502)
[#1524: '[MOD] smolraptor borgs' by aKromatopzia at commit 63b3a2d1ca](https://github.com/Bubberstation/Bubberstation/pull/1524)
[#1528: 'Nerfs No-Talk Borg Emags' by ReturnToZender at commit 6244fbc466](https://github.com/Bubberstation/Bubberstation/pull/1528)
[#1296: 'Removes Ascensions from Heretic because the Catholic Church sent me a DM' by BurgerLUA at commit 1e9432198d](https://github.com/Bubberstation/Bubberstation/pull/1296)

## Reproduction:

With the skunk tail or anthromorph body type, select equipment as Asset Protection. The chestplate should come up as invisible.

**Comment by ReturnToZender** [comment]
I believe it's specific to the digi legs, I made a fix a while ago and it just... stopped working. Must have been lost w/ an upstream merge. I'll try cracking at it again soon

**Comment by projectkepler-ru** [comment]
> I believe it's specific to the digi legs, I made a fix a while ago and it just... stopped working. Must have been lost w/ an upstream merge. I'll try cracking at it again soon

I'll take a look at the gitblame dw

**Comment by projectkepler-ru** [comment]
working on this
