### ISSUE TITLE
Brain Transplants are bugged to shit right now (upstream bug, probably)

### ISSUE THREAD

**Issue by GoreDem** [Bubberstation/Bubberstation#1549]
## Issue Summary
Souls are assigned to bodies instead of brains
borging is completely broken

**Comment by Majkl-J** [comment]
Works fine if you amputate the head then gut it for the brain, still unintentional that souls dont transfer with organ manip

**Comment by Arturlang** [comment]
Bloodsucker funny brain features slightly mess with how brainmobs work, but it shouldn't mess with soul transfer

**Comment by Majkl-J** [comment]
I fixed this upstream a while back and forgot to close, it's on live by now
