### ISSUE TITLE
Smoker Quirk Cigarette Preference Does Not Save

### ISSUE THREAD

**Issue by DexyEurion** [Bubberstation/Bubberstation#1554]
## Issue Summary
Any time you set your Smoker Quirk Preference, it just resets to Random the moment you click off the Dropdown even after setting it to a specific brand.

## Round ID:
4402

Bubberstation

## Reproduction:
You can easily reproduce this at any time by just clicking the Cog at anytime in the Character Preference Quirk Menu for the Smoker Quirk. Clicking any of the options will not save even after closing the Character Preference Menu or clicking off of the drop-down list, setting back to the Default of Random.

**Comment by Odairu** [comment]
This is no longer an issue 👍
