### ISSUE TITLE
Smoker quirk doesn't seem to work properly.

### ISSUE THREAD

**Issue by RadiantFlash7** [Bubberstation/Bubberstation#1584]
## Issue Summary
Smoker quirk adds a moodlet for not smoking in an amount of time. Smoking is supposed to clear this moodlet. It didn't. (This was using the round start c
![image](https://github.com/Bubberstation/Bubberstation/assets/12434413/bd22affc-3894-4ecb-99b1-91662665bd4d)

## Round ID:
4472

## Testmerges:
456
1407
1453
1471
1441
1502
1545
1544
1539
1538
1551
1557
1579
1580
## Reproduction:
Have smoker quirk. Smoke cigarette. Examine moodlet.

**Comment by ReturnToZender** [comment]
I wonder if the same fix to the entombed quirk done by Colfer fixes the issue
