### ISSUE TITLE
Brig cells on blueshift are broken

### ISSUE THREAD

**Issue by RadiantFlash7** [Bubberstation/Bubberstation#1585]
## Issue Summary
Brig cells are broken on blueshift. Several brig cell controls don't connect to lockers, or even doors- and some don't even work at all.

## Round ID:
N/A

## Testmerges:

N/A

## Reproduction:
Try using most of the brig cells on blueshift. Cry because they're broken.

**Comment by ReturnToZender** [comment]
I'll see if I can fix this upstream
