### ISSUE TITLE
the modsuit armor module don't work

### ISSUE THREAD

**Issue by projectkepler-ru** [Bubberstation/Bubberstation#1621]
## Issue Summary
won't turn on

## Round ID:
4557

## Testmerges:
N/A

## Reproduction:
![image](https://github.com/Bubberstation/Bubberstation/assets/99981766/6eef1a42-1bf0-454c-bfac-71631869b69d)
it does not turn on

**Comment by nevimer** [comment]
should be fixed - reopen if not
