### ISSUE TITLE
Adding/Removing an item from Pockets has no indicator

### ISSUE THREAD

**Issue by Mewchild** [Bubberstation/Bubberstation#1622]
## Issue Summary
When you strip strip an item from someone's pockets, the individual being stripped gets no indication of it happening, and only realize it if they see the item's gone missing.

## Round ID:
4557

## Testmerges:
[#1407: 'Adds Research cyborgs [Modularish] (oh no)' by pixelkitty286 at commit f25cd24c88](https://github.com/Bubberstation/Bubberstation/pull/1407)
[#1453: 'Click First Combat (Part 2 | The Baton Knockdown Wallshove Combo)' by StrangeWeirdKitten at commit 19aa819e65](https://github.com/Bubberstation/Bubberstation/pull/1453)
[#1471: 'GAS 2 - Part 2 - The Sequel, the worm, what you have been waiting for' by nevimer at commit 2fc4018ef4](https://github.com/Bubberstation/Bubberstation/pull/1471)
[#1502: '[EXPERIMENTAL and TM-ONLY] Atmos Hijinks - The hijinking' by Majkl-J at commit 079eb31253](https://github.com/Bubberstation/Bubberstation/pull/1502)
[#1545: 'Public Logging Update' by nevimer at commit 687d0d08e5](https://github.com/Bubberstation/Bubberstation/pull/1545)
[#1544: 'Adds Big Bertha, a unique one-of-a-kind two-handed shield for security that blocks (almost) everything.' by BurgerLUA at commit cb403c2b02](https://github.com/Bubberstation/Bubberstation/pull/1544)
[#1539: 'You only get 1 corrupt organ when sacrificed (and removes dogshit organs from the corruption pool) instead of 2 to 4.' by BurgerLUA at commit 3ea6f8324f](https://github.com/Bubberstation/Bubberstation/pull/1539)
[#1538: 'Moth buff port from Nova Sector' by ReturnToZender at commit 8d5d5357de](https://github.com/Bubberstation/Bubberstation/pull/1538)
[#1590: '[TEST] Removes the Ambient Buzz' by nevimer at commit 14c19b1dda](https://github.com/Bubberstation/Bubberstation/pull/1590)
[#1602: 'Wawastation (#82298)' by nevimer at commit 3a6e8597b9](https://github.com/Bubberstation/Bubberstation/pull/1602)
[#1525: 'Bluespace Experi-Scanner' by codehonky at commit 7b19d3d81c](https://github.com/Bubberstation/Bubberstation/pull/1525)
[#1611: 'Wawastation automapper templates [TM ONLY]' by lessthnthree at commit 889676b935](https://github.com/Bubberstation/Bubberstation/pull/1611)
[#1615: 'Captain office access can't magically grant you AA anymore' by Majkl-J at commit 6eb4b7b98f](https://github.com/Bubberstation/Bubberstation/pull/1615)
[#1594: '[MIRROR] Tram update package' by lessthnthree at commit 0cbda1cb42](https://github.com/Bubberstation/Bubberstation/pull/1594)

## Reproduction:
Get a sneaky compatriot
Place an item in your pocket
Have your companion pick your pocket
Marvel at the lack of chat indicators showing someone is in your pocketses

**Comment by StrangeWeirdKitten** [comment]
Intentional

**Comment by YakumoChen** [comment]
That's literally pickpocketing, yes. You can also reverse-pickpocket silently
