### ISSUE TITLE
Service Borg Issues

### ISSUE THREAD

**Issue by Cecily-C-Catherine** [Bubberstation/Bubberstation#1645]
Reporting client version: 515.1637

## Issue Summary

Service borgs can no longer have the cook book or rolling table upgrade put into them as well they can no longer fill cups they are holding and instead have to be placed down.

## Round ID:
4592

## Reproduction:

Attempt to upgrade cook book module or fill drink as borg.

**Comment by Majkl-J** [comment]
This was already fixed upstream at https://github.com/tgstation/tgstation/pull/83785 and will get here in a few days
