### ISSUE TITLE
Cooking Menu Ingredient Tab is horribly laggy

### ISSUE THREAD

**Issue by FalloutFalcon** [Bubberstation/Bubberstation#1647]
Reporting client version: 515.1634

## Issue Summary
Having the Ingredient tab open causes consistent lag
I haven't looked at the code but i assume the issue is under utilizing static data

## Round ID:
4602

## Testmerges:
- [Click First Combat (Part 2 | The Baton Knockdown Wallshove Combo)](https://github.com/Bubberstation/Bubberstation/pull/1453)
- [GAS 2 - Part 2 - The Sequel, the worm, what you have been waiting for](https://github.com/Bubberstation/Bubberstation/pull/1471)
- [Public Logging Update](https://github.com/Bubberstation/Bubberstation/pull/1545)
- [You only get 1 corrupt organ when sacrificed (and removes dogshit organs from the corruption pool) instead of 2 to 4.](https://github.com/Bubberstation/Bubberstation/pull/1539)
- [[TEST] Removes the Ambient Buzz](https://github.com/Bubberstation/Bubberstation/pull/1590)
- [Wawastation (#82298)](https://github.com/Bubberstation/Bubberstation/pull/1602)
- [Bluespace Experi-Scanner](https://github.com/Bubberstation/Bubberstation/pull/1525)
- [Wawastation automapper templates](https://github.com/Bubberstation/Bubberstation/pull/1611)
- [Captain office access can't magically grant you AA anymore](https://github.com/Bubberstation/Bubberstation/pull/1615)
- [[MIRROR] Tram update package](https://github.com/Bubberstation/Bubberstation/pull/1594)
- [Maybe fixes roundstart sometimes lagging](https://github.com/Bubberstation/Bubberstation/pull/1623)
- [Ports #28102 from upstream](https://github.com/Bubberstation/Bubberstation/pull/1631)
- [[EXPERIMENTAL and TM-ONLY] Atmos Hijinks - The hijinking](https://github.com/Bubberstation/Bubberstation/pull/1502)

## Reproduction:
Switch to the between sorting by Category and Ingredient and notice how much worse the frame drops are as you walk around

**Comment by Majkl-J** [comment]
Anyhow this is a tg bug so the report should be made there
