### ISSUE TITLE
Sol Dry is not present within an upgraded soda dispenser

### ISSUE THREAD

**Issue by plsleavemealon** [Bubberstation/Bubberstation#1650]
## Issue Summary

Sol Dry isn't located within the upgraded soda dispenser.  Unsure if this is true of all stages, but it should be present according to the wiki.

## Round ID:4616
[Round ID]: 4616

## Reproduction:

Just walk up to the soda dispenser and witness that sol dry is missing.

**Comment by YakumoChen** [comment]
Seems like a bug upstream for skyrat, not sure if it works on tg base

**Comment by projectkepler-ru** [comment]
yea i'll take a look
eventually
