### ISSUE TITLE
Cryopod cloning 

### ISSUE THREAD

**Issue by ItsMoka** [Bubberstation/Bubberstation#1655]
## Issue Summary

You can clone yourself and your starting gear (loadout and job) by using a crypod

## Round ID:

4619

## Testmerges:

X

## Reproduction:

You can clone yourself by:
Laying in a cryopod 
Pressing escape (open menu)
Pressing down arrow (exit cryopod) WHILE in the menu 
Ghosting yourself 
Respawning

**Comment by Majkl-J** [comment]
This seems just like regular ghosting out whilst out of a cryopod
