### ISSUE TITLE
Moonstation Mines Z-layer is counted as being on station for Event Rolls

### ISSUE THREAD

**Issue by Mewchild** [Bubberstation/Bubberstation#1669]
## Issue Summary
Moonstation Mines are considered to be part of the station. This has a number of negative effects, particularly for those of ghost roles.

## Testmerges:
Server revision compiled on: 2024-06-20T05:09:12+00:00
Master commit: [2dd33a57235d197b19692a77c70f2fd63d3c8698](https://github.com/Bubberstation/Bubberstation/commit/2dd33a57235d197b19692a77c70f2fd63d3c8698)
The following pull requests are currently test merged:
[#1453: 'Click First Combat (Part 2 | The Baton Knockdown Wallshove Combo)' by StrangeWeirdKitten at commit 19aa819e65](https://github.com/Bubberstation/Bubberstation/pull/1453)
[#1471: 'GAS 2 - Part 2 - The Sequel, the worm, what you have been waiting for' by nevimer at commit 2fc4018ef4](https://github.com/Bubberstation/Bubberstation/pull/1471)
[#1545: 'Public Logging Update' by nevimer at commit 687d0d08e5](https://github.com/Bubberstation/Bubberstation/pull/1545)
[#1539: '[Ready] You only get 1 corrupt organ when sacrificed (and removes dogshit organs from the corruption pool) instead of 2 to 4.' by BurgerLUA at commit 1d78824417](https://github.com/Bubberstation/Bubberstation/pull/1539)
[#1590: '[TEST] Removes the Ambient Buzz' by nevimer at commit 14c19b1dda](https://github.com/Bubberstation/Bubberstation/pull/1590)
[#1602: 'Wawastation (#82298)' by nevimer at commit 3a6e8597b9](https://github.com/Bubberstation/Bubberstation/pull/1602)
[#1611: 'Wawastation automapper templates' by lessthnthree at commit b182c4897b](https://github.com/Bubberstation/Bubberstation/pull/1611)
[#1615: 'Captain office access can't magically grant you AA anymore' by Majkl-J at commit 6eb4b7b98f](https://github.com/Bubberstation/Bubberstation/pull/1615)
[#1594: '[MIRROR] Tram update package' by lessthnthree at commit 5d963dbc30](https://github.com/Bubberstation/Bubberstation/pull/1594)
[#1631: 'Ports #28102 from upstream' by theselfish at commit cf274b563c](https://github.com/Bubberstation/Bubberstation/pull/1631)
[#1633: 'Massive Overhaul of the Dauntless ' by shellspeed1 at commit 6fa6bf6ec0](https://github.com/Bubberstation/Bubberstation/pull/1633)
[#1599: 'Adds Antag Tickets' by BurgerLUA at commit 6377e4bed6](https://github.com/Bubberstation/Bubberstation/pull/1599)
[#1657: 'Bug fix / refactor-ish to cyborg resting procs' by pixelkitty286 at commit 93463977f6](https://github.com/Bubberstation/Bubberstation/pull/1657)
[#1653: 'fix two sets of delays on storyteller events' by nevimer at commit ed98124cc1](https://github.com/Bubberstation/Bubberstation/pull/1653)
[#1658: 'Chest Loss only makes one Organ be removed' by nevimer at commit f9a99cc642](https://github.com/Bubberstation/Bubberstation/pull/1658)
[#1667: 'allow the ghost to be votable at any time' by nevimer at commit 9b6ac14162](https://github.com/Bubberstation/Bubberstation/pull/1667)
[#1665: 'Fixes the Projection Barrier' by theselfish at commit 80bf29ef3c](https://github.com/Bubberstation/Bubberstation/pull/1665)

## Reproduction:
While the map is moonstation, trigger any of the following events:
Station Blackout
Scrubbers Backflow
Xenomorph Spawn (has a chance to spawn in Dauntless)
Biological Obstruction (has a chance to spawn in any Dauntless air fixture)
Radiation Storm
In addition, Fulton Beacons don't work properly in the mines, due to them not being considered an outside area

**Comment by BurgerLUA** [comment]
This is a /tg/ issue, believe it or not. All these issues also occur on icebox and there is no way of fixing this without going upstream for it.

**Comment by Mewchild** [comment]
I'm crying such big tears right now, burgers.

**Comment by Majkl-J** [comment]
Can't really fix on here it's a long-known tg bug.
