### ISSUE TITLE
The donaters-only button in the loadout directs you to a non-existant channel on the disc

### ISSUE THREAD

**Issue by nikothedude** [Bubberstation/Bubberstation#1692]
Reporting client version: 515.1635

## Round ID:
4714

## Testmerges:
- [GAS 2 - Part 2 - The Sequel, the worm, what you have been waiting for](https://github.com/Bubberstation/Bubberstation/pull/1471)
- [Public Logging Update](https://github.com/Bubberstation/Bubberstation/pull/1545)
- [[Ready] You only get 1 corrupt organ when sacrificed (and removes dogshit organs from the corruption pool) instead of 2 to 4.](https://github.com/Bubberstation/Bubberstation/pull/1539)
- [Wawastation (#82298)](https://github.com/Bubberstation/Bubberstation/pull/1602)
- [Wawastation automapper templates](https://github.com/Bubberstation/Bubberstation/pull/1611)
- Rate limitede

## Reproduction:

Go into head, scroll down, click the pink heart on the flowers, get this message:

This item is restricted to donators only, for more information, please check the discord(#server-info) for more information!

Server-info does not exist.

**Comment by Majkl-J** [comment]
Eeeh new loadouts probably fixed this since the donator items can't even show up unless you're donator
