### ISSUE TITLE
Proto-Kinetic crusher now requires you to shoot yourself to fire a bolt at a rock 

### ISSUE THREAD

**Issue by KateAnbolho** [Bubberstation/Bubberstation#1698]
## Testmerges: [#1545: 'Public Logging Update' by nevimer at commit 687d0d08e5](https://github.com/Bubberstation/Bubberstation/pull/1545)
[#1539: '[Ready] You only get 1 corrupt organ when sacrificed (and removes dogshit organs from the corruption pool) instead of 2 to 4.' by BurgerLUA at commit 914aff5048](https://github.com/Bubberstation/Bubberstation/pull/1539)
[#1633: 'Massive Overhaul of the Dauntless (DNM) (Fine for Test merge.)' by shellspeed1 at commit 6c0e10e493](https://github.com/Bubberstation/Bubberstation/pull/1633)
[#1599: 'Adds Antag Tickets' by BurgerLUA at commit ac880b7ef0](https://github.com/Bubberstation/Bubberstation/pull/1599)
[#1658: 'Chest Loss only makes one Organ be removed' by nevimer at commit ad3c9eac26](https://github.com/Bubberstation/Bubberstation/pull/1658)
[#1617: '[Ready] Nerfs Bow because I saw someone die to it once' by BurgerLUA at commit 4b403ae9c6](https://github.com/Bubberstation/Bubberstation/pull/1617)
[#1557: 'Adds Changeling Zombies (Now 99% more changeling integration)' by BurgerLUA at commit a772563ac4](https://github.com/Bubberstation/Bubberstation/pull/1557)
[#1581: '[TM Only] Nerfs blade ascension, removes Moon+Void ascension' by ReturnToZender at commit 6cb89d20e6](https://github.com/Bubberstation/Bubberstation/pull/1581)
[#1696: 'Hypospray hotfix' by lessthnthree at commit e76318c2dd](https://github.com/Bubberstation/Bubberstation/pull/1696)
[#1694: '[UPSTREAM MIRROR] Fixes a typo in electrical damage description + prevents electrical damage from worsening during repairs + remove some nova edits' by nikothedude at commit d6871dcef5](https://github.com/Bubberstation/Bubberstation/pull/1694)
[#1693: '[UPSTREAM MIRROR] A bunch of taur fixes and expansions' by nikothedude at commit 54c90e6154](https://github.com/Bubberstation/Bubberstation/pull/1693)
[#1684: 'Nerfs bloodsucker blood gain from the blood reagent' by Arturlang at commit 2bf0defc0e](https://github.com/Bubberstation/Bubberstation/pull/1684)

## Reproduction: When you try to mine with a proto-kinetic crusher you can't click on rocks. 

Attempt to click on rocks 

Cant fire at rocks

Click self 

Bolt fires eastward

**Comment by Erol509** [comment]
Mined with it yesterday, and it worked.

**Comment by KateAnbolho** [comment]
https://gyazo.com/5dc3e8015a8a27bcf690c825179c216f video of it still not working, i cant click myself with gyazo overlaid over my character tho so rip

**Comment by Majkl-J** [comment]
Fixed upstream and as such won't be a problem soon enough
