### ISSUE TITLE
Placing vamp structures anywhere

### ISSUE THREAD

**Issue by KazooBard** [Bubberstation/Bubberstation#1700]
Okay so you can just, do what I do in this video, ez spam the station with hallucinations and structures which are really fucking hard to break cause it's funny. 

https://github.com/Bubberstation/Bubberstation/assets/65713506/b8261d6e-6de5-41ad-8a08-4b97a70a5932

And yeah accidentally posted it empty then I panicked and closed this, woopsieeees

**Comment by KazooBard** [comment]
FUCK I PRESSED ENTER ON ACCIDENT

**Comment by ReturnToZender** [comment]
@Arturlang

**Comment by Arturlang** [comment]
Huh. Damn
