### ISSUE TITLE
Ninjas load prefs, entombed ninjas spawn with no ninja mod

### ISSUE THREAD

**Issue by KazooBard** [Bubberstation/Bubberstation#1701]
## Issue Summary

Pretty simple. You roll ninja. You got two choices. Both keep your traits. Welcome the entombed ninja everyone, who spawns with a sword and their entire kit missing.

I don't even need to give round ID because this happens so often, I made an extra char just for ninja so my monophobia doesn't load with it.

**Comment by Erol509** [comment]
entombed should be blacklisted from ninja
