### ISSUE TITLE
Various Loadout issues.

### ISSUE THREAD

**Issue by theselfish** [Bubberstation/Bubberstation#1733]
Reporting client version: 515.1639

## Issue Summary

Compiling various loadout issues that I personally have experienced. I'd encourage others to also post theirs here to compile them in one place.

-Some items are broken in the loadout preview. Mainly GAGS related stuff like the bows and cowboy hats. Guessing that wherever the loadout points to get the obj file is missing?

~~-If you have your loadout pref set to 'place all in case' your character is nude in the preview menu.~~ Fixed with https://github.com/Skyrat-SS13/Skyrat-tg/pull/28684

 ~~-Some items vanished, /obj/item/clothing/under/costume/skyrat/kimono/sigmar is one. A lot of these seem to be Skyrat donator uniforms. Maybe it wasn't updated properly?~~ Fixed with https://github.com/Skyrat-SS13/Skyrat-tg/pull/28662
 
-Some objects, suits mainly are showing flash suits as their previews for some reason?

## Round ID:
4760

## Testmerges:
- [Public Logging Update](https://github.com/Bubberstation/Bubberstation/pull/1545)
- [[Ready] You only get 1 corrupt organ when sacrificed (and removes dogshit organs from the corruption pool) instead of 2 to 4.](https://github.com/Bubberstation/Bubberstation/pull/1539)
- [Massive Overhaul of the Dauntless (DNM) (Fine for Test merge.)](https://github.com/Bubberstation/Bubberstation/pull/1633)
- [GITHUB API ERROR: RATE LIMITED](https://github.com/Bubberstation/Bubberstation/pull/1599)
- [GITHUB API ERROR: RATE LIMITED](https://github.com/Bubberstation/Bubberstation/pull/1658)
- [GITHUB API ERROR: RATE LIMITED](https://github.com/Bubberstation/Bubberstation/pull/1581)
- [GITHUB API ERROR: RATE LIMITED](https://github.com/Bubberstation/Bubberstation/pull/1696)
- [GITHUB API ERROR: RATE LIMITED](https://github.com/Bubberstation/Bubberstation/pull/1684)
- [GITHUB API ERROR: RATE LIMITED](https://github.com/Bubberstation/Bubberstation/pull/1706)
- [GITHUB API ERROR: RATE LIMITED](https://github.com/Bubberstation/Bubberstation/pull/1710)
- [GITHUB API ERROR: RATE LIMITED](https://github.com/Bubberstation/Bubberstation/pull/1724)
- [GITHUB API ERROR: RATE LIMITED](https://github.com/Bubberstation/Bubberstation/pull/1727)
- [GITHUB API ERROR: RATE LIMITED](https://github.com/Bubberstation/Bubberstation/pull/1471)

## Reproduction:

Go into the loadout menu.

**Comment by theselfish** [comment]
Wallets are missing.

**Comment by plsleavemealon** [comment]
Also related to this, you can't make custom item descriptions, only custom item names.

**Comment by Majkl-J** [comment]
> Also related to this, you can't make custom item descriptions, only custom item names.

I'm on this, and the missing icons
