### ISSUE TITLE
Armadyne security vendor doesn't show contraband after emagging and cutting contraband wire

### ISSUE THREAD

**Issue by Shroopy** [Bubberstation/Bubberstation#1735]
## Issue Summary
The Armadyne security vendor doesn't show contraband after emagging it and cutting the contraband wire

## Round ID:
N/A

## Testmerges:
None

## Reproduction:
Spawn in armadyne sec vendor, emag it, cut the contraband wire, no contraband

**Comment by theselfish** [comment]
There might just be no contraband. I know some vendors don't have em.

**Comment by Odairu** [comment]
![image](https://github.com/user-attachments/assets/648d42ff-ac80-4c85-9659-ea899377cdf6)
