### ISSUE TITLE
CMO Hypospray doesn't accept large hypovials

### ISSUE THREAD

**Issue by RadiantFlash7** [Bubberstation/Bubberstation#1739]
## Issue Summary
CMO hypospray does not accept large vials. Cue panicked CMO flailing.  🙀 
![image](https://github.com/Bubberstation/Bubberstation/assets/12434413/0d4fb735-1439-4a8e-aef1-7cacce62b704)

## Testmerges:
#1545
#1539
#1633
#1599
#1658
#1581
#1684
#1706
#1724
#1727
#1471 

## Reproduction: 
Insert large hypovial into cmo hypospray. Panick when it fails to work. 🙀

**Comment by projectkepler-ru** [comment]
alright im murdering someone for this

**Comment by Majkl-J** [comment]
Seems to have been fixed
