### ISSUE TITLE
Mothroaches jump out of hands and bags

### ISSUE THREAD

**Issue by Shroopy** [Bubberstation/Bubberstation#1740]
## Issue Summary
Mothroaches jump out of inventories, making them almost impossible to contain without a pet carrier.

## Round ID:
N/A

## Testmerges:
None

## Reproduction:
Pick up a mothroach and wait a bit

**Comment by ReturnToZender** [comment]
You can't keep 'em down

**Comment by Odairu** [comment]
https://github.com/tgstation/tgstation/pull/84921#issue-2406413792 closes this
