### ISSUE TITLE
Public logging lacks PDA messages

### ISSUE THREAD

**Issue by ReturnToZender** [Bubberstation/Bubberstation#1788]
## Issue Summary
Public logging shows most forms of communication, but not PDA messages. A sanitized version of these should be provided.

## Round ID:
N/A

## Testmerges:
Not relevant

## Reproduction:
Open [https://parsedlogs.bubberstation.org/logs/](https://parsedlogs.bubberstation.org/logs/)
Go to any round #
Search for keyword "PDA:", find nothing
Open up pda.log on same round on server box, find messages
Weep

**Comment by lessthnthree** [comment]
A good candidate to combine with subtle PDA messaging. Which I think I have sitting on a branch 90% completed ported from Effigy.

**Comment by ReturnToZender** [comment]
> A good candidate to combine with subtle PDA messaging. Which I think I have sitting on a branch 90% completed ported from Effigy.

oo

**Comment by lessthnthree** [comment]
> > A good candidate to combine with subtle PDA messaging. Which I think I have sitting on a branch 90% completed ported from Effigy.
> 
> oo

https://github.com/Bubberstation/Bubberstation/pull/2058
