### ISSUE TITLE
Missing Items

### ISSUE THREAD

**Issue by Fragenstien** [Bubberstation/Bubberstation#1791]
## Issue Summary
Some items seem to be missing. The only one I have documented is the "shorter shorts", which can be selected in the loadout but don't appear on spawn or in the vendors.

**Comment by Odairu** [comment]
![image](https://github.com/user-attachments/assets/dc862814-70ea-4e84-aed5-822c79cc017b)
Shorter shorts appear to exist so I'm not sure without having more things to check for

**Comment by Majkl-J** [comment]
![image](https://github.com/user-attachments/assets/78f0528b-2257-4ed7-aebe-1c8294c5c765)

Can't repro
