### ISSUE TITLE
Cargo module mechs no longer have the ability to open their cargo bay.

### ISSUE THREAD

**Issue by KateAnbolho** [Bubberstation/Bubberstation#1798]
## Issue Summary

Cargo module mechs no longer have the ability to open their cargo bay. It appears to be constantly attempting to reselect the hydraulic clamp instead of opening the cargo bay UI, which means anything put into a mech is sent to the shadow realm.

## Testmerges:

Round ID: 4887
BYOND Version: 515.1641
Server revision compiled on: 2024-07-15T23:20:37+00:00
Master commit: [f07acd247a2bd29bd38434b83f020516d880db7c](https://github.com/Bubberstation/Bubberstation/commit/f07acd247a2bd29bd38434b83f020516d880db7c)
The following pull requests are currently test merged:
[#1545: 'Public Logging Update' by nevimer at commit 687d0d08e5](https://github.com/Bubberstation/Bubberstation/pull/1545)
[#1633: 'Massive Overhaul of the Dauntless (Ready for review) (Don't merge until after review so I can update the space version)' by shellspeed1 at commit 749debce6c](https://github.com/Bubberstation/Bubberstation/pull/1633)
[#1658: 'Chest Loss only makes one Organ be removed' by nevimer at commit 00ae7de72e](https://github.com/Bubberstation/Bubberstation/pull/1658)
[#1581: '[TM Only] Nerfs blade ascension, removes Moon+Void ascension' by ReturnToZender at commit e569ec0f27](https://github.com/Bubberstation/Bubberstation/pull/1581)
[#1684: 'Nerfs bloodsucker blood gain from the blood reagent' by Arturlang at commit 1efffc634e](https://github.com/Bubberstation/Bubberstation/pull/1684)
[#1471: 'GAS 2 - Part 2 - The Sequel, the worm, what you have been waiting for' by nevimer at commit fef4911ada](https://github.com/Bubberstation/Bubberstation/pull/1471)
[#1458: 'Bloodsucker power refactor' by Arturlang at commit 7c7e17ed3b](https://github.com/Bubberstation/Bubberstation/pull/1458)
[#1738: 'Reverts emp nerf since they arent as powerful anymore' by Majkl-J at commit 9bc3ff15d3](https://github.com/Bubberstation/Bubberstation/pull/1738)
[#1777: 'GITHUB API ERROR: RATE LIMITED' by GITHUB API ERROR: RATE LIMITED at commit a8eb790a81](https://github.com/Bubberstation/Bubberstation/pull/1777)
[#1706: 'GITHUB API ERROR: RATE LIMITED' by GITHUB API ERROR: RATE LIMITED at commit 69ff65c615](https://github.com/Bubberstation/Bubberstation/pull/1706)
[#1724: 'GITHUB API ERROR: RATE LIMITED' by GITHUB API ERROR: RATE LIMITED at commit 115e4a3ff1](https://github.com/Bubberstation/Bubberstation/pull/1724)
[#1790: 'GITHUB API ERROR: RATE LIMITED' by GITHUB API ERROR: RATE LIMITED at commit 384655388d](https://github.com/Bubberstation/Bubberstation/pull/1790)

Local commit: 280c6c36d53abd6c62e96c27a74b91cac661bba8
TGS version: 5.18.1
DMAPI version: 5.9.0

Current Informational Settings:
Protect Authority Roles From Traitor: 1
Protect Assistant Role From Traitor: 0
Enforce Human Authority: 0
Allow Latejoin Antagonists: 1
## Reproduction:

> Load the Big Bess with the warehouse full of crates 
> Try to select the cargo bay 
> Can't drop the crates  :(

**Comment by KateAnbolho** [comment]
Updated test: It appears to work if you mount a non-hydraulic clamp to the other mech hand

**Comment by Majkl-J** [comment]
![image](https://github.com/user-attachments/assets/f064c192-487e-4e11-88d8-413a97f36325)

Seems to not be a thing anymore
