### ISSUE TITLE
Wargame holographs, in the wargame holodeck program, appear pitch black in the space tiles in the program

### ISSUE THREAD

**Issue by nikothedude** [Bubberstation/Bubberstation#1818]
Reporting client version: 515.1637

## Issue Summary

![image](https://github.com/user-attachments/assets/c9486336-cd98-4d71-9e45-f32bc7454235)

## Round ID:
4916

## Testmerges:
- [Public Logging Update](https://github.com/Bubberstation/Bubberstation/pull/1545)
- [Massive Overhaul of the Dauntless (Ready for review) (Don't merge until after review so I can update the space version)](https://github.com/Bubberstation/Bubberstation/pull/1633)
- [[TM Only] Nerfs blade ascension, removes Moon+Void ascension](https://github.com/Bubberstation/Bubberstation/pull/1581)
- [Nerfs bloodsucker blood gain from the blood reagent](https://github.com/Bubberstation/Bubberstation/pull/1684)
- [GAS 2 - Part 2 - The Sequel, the worm, what you have been waiting for](https://github.com/Bubberstation/Bubberstation/pull/1471)
- [Bloodsucker power refactor](https://github.com/Bubberstation/Bubberstation/pull/1458)
- [ [MDB Ignore] [IDB Ignore] Bubberstation x Effigy Promo [TM ONLY]](https://github.com/Bubberstation/Bubberstation/pull/1724)
- [The offstation cargo update (Test merge ready)](https://github.com/Bubberstation/Bubberstation/pull/1764)
- [Station power is finally stable and intelligent, can you believe it? [TM ONLY]](https://github.com/Bubberstation/Bubberstation/pull/1816)

## Reproduction:

Open wargaming holodeck program, spawn things. Theyre black

**Comment by Odairu** [comment]
![image](https://github.com/user-attachments/assets/949338ca-b8bd-4761-bff2-fa1bff856fbb)

**Comment by nikothedude** [comment]
> ![image](https://private-user-images.githubusercontent.com/39929315/356840492-949338ca-b8bd-4761-bff2-fa1bff856fbb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMzNDYzNDgsIm5iZiI6MTcyMzM0NjA0OCwicGF0aCI6Ii8zOTkyOTMxNS8zNTY4NDA0OTItOTQ5MzM4Y2EtYjhiZC00NzYxLWJmZjItZmExYmZmODU2ZmJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODExVDAzMTQwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkzMTU2ZGQ5YzJjZTZjMmZlMjVjMTNmYmNkMDRiMDlmNzY3YTAyOWQxNTg0MDVhODFjOTVmOGZlZWZiNjA5MjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Yf3_2tY0cYy2vOLt6WuMtThAKBE15NbSedTDdMJr9Zk)

i guess the tiles got changed to something else somehow, thats a different texture
