### ISSUE TITLE
Vampire feeding bug

### ISSUE THREAD

**Issue by AlmaTray** [Bubberstation/Bubberstation#1827]
## Issue Summary

When you start feeding as a vampire and then move a tile, the feeding stops and never works unless an admin removes and grants it again.

## Reproduction: Click "Feed", move somewhere. You won't be able to activate the ability again.

**Comment by ReturnToZender** [comment]
@Arturlang may want to take a stab at this

**Comment by Arturlang** [comment]
this is fixed

**Comment by Majkl-J** [comment]
Fixed
