### ISSUE TITLE
Prescription HUDs are acting VERY strangely

### ISSUE THREAD

**Issue by nikothedude** [Bubberstation/Bubberstation#1899]
Reporting client version: 515.1637

## Issue Summary

Prescription HUDs inconsistantly grant their HUD. HUD aviators, like the prescription security HUD aviators...

1. Dont apply their HUD with the HUD mode enabled
2. Cease being prescription glasses if you enable flash protection

## Round ID:
5042

## Testmerges:
- [Public Logging Update](https://github.com/Bubberstation/Bubberstation/pull/1545)
- [Massive Overhaul of the Dauntless (Ready for review) (Don't merge until after review so I can update the space version)](https://github.com/Bubberstation/Bubberstation/pull/1633)
- [[TM Only] Nerfs blade ascension, removes Moon+Void ascension](https://github.com/Bubberstation/Bubberstation/pull/1581)
- [GAS 2 - Part 2 - The Sequel, the worm, what you have been waiting for](https://github.com/Bubberstation/Bubberstation/pull/1471)
- [ [MDB Ignore] [IDB Ignore] Bubberstation x Effigy Promo [TM ONLY]](https://github.com/Bubberstation/Bubberstation/pull/1724)
- [The offstation cargo update (Ready for review)](https://github.com/Bubberstation/Bubberstation/pull/1764)
- [Adds Void Walker to Storyteller](https://github.com/Bubberstation/Bubberstation/pull/1838)
- [[Bounty] Vore 4.0](https://github.com/Bubberstation/Bubberstation/pull/1808)
- [Limbgrown bodies.](https://github.com/Bubberstation/Bubberstation/pull/1842)
- [Emags unlink borgs from the console + 0.5 delay in opening their covers](https://github.com/Bubberstation/Bubberstation/pull/1871)
- [[TM ONLY] Echolocation](https://github.com/Bubberstation/Bubberstation/pull/1876)
- [Bounty cube export gate [TM ONLY]](https://github.com/Bubberstation/Bubberstation/pull/1841)
- [[TM ONLY] Reverts the TGUI stat panels](https://github.com/Bubberstation/Bubberstation/pull/1887)

## Reproduction:

Step 1: Get prescription aviators
Step 2: Get no HUD, see that the flash protection mdoe doesnt reduce nearsightedness

**Comment by ReturnToZender** [comment]
TG recently changed how HUDs work to be based off of traits, could it be that they forgot prescriptions?

**Comment by Majkl-J** [comment]
I fixed this upstream, and I think we got it here now :3
