### ISSUE TITLE
Assistants don't spawn in with chosen loadout jumpsuit slot items with Delete Job Items pref

### ISSUE THREAD

**Issue by YakumoChen** [Bubberstation/Bubberstation#1908]
## Issue Summary

I have Delete Job Items as my loadout pref, when I spawn in as assistant, I still spawn with a coloured jumpskirt regardless instead of my intended loadout item. This doesn't seem to be tied to any station trait (happened on a no trait round)

## Round ID:

consistent over multiple rounds

## Testmerges:
[#1545: 'Public Logging Update' by nevimer at commit 687d0d08e5](https://github.com/Bubberstation/Bubberstation/pull/1545)
[#1581: '[TM Only] Nerfs blade ascension, removes Moon+Void ascension' by ReturnToZender at commit a8af947b28](https://github.com/Bubberstation/Bubberstation/pull/1581)
[#1471: 'GAS 2 - Part 2 - The Sequel, the worm, what you have been waiting for' by nevimer at commit fef4911ada](https://github.com/Bubberstation/Bubberstation/pull/1471)
[#1724: ' [MDB Ignore] [IDB Ignore] Bubberstation x Effigy Promo [TM ONLY]' by lessthnthree at commit 608444f208](https://github.com/Bubberstation/Bubberstation/pull/1724)
[#1764: 'The offstation cargo update (Ready for review)' by shellspeed1 at commit 8a6fca2627](https://github.com/Bubberstation/Bubberstation/pull/1764)
[#1808: '[Bounty] Vore 4.0' by ShadowLarkens at commit 0c4ceb342a](https://github.com/Bubberstation/Bubberstation/pull/1808)
[#1842: 'Limbgrown bodies.' by xXPawnStarrXx at commit cf5f2384fd](https://github.com/Bubberstation/Bubberstation/pull/1842)
[#1871: 'Emags unlink borgs from the console + 0.5 delay in opening their covers' by StrangeWeirdKitten at commit e900f6aa47](https://github.com/Bubberstation/Bubberstation/pull/1871)
[#1876: '[TM ONLY] Echolocation' by Majkl-J at commit f4e231d87e](https://github.com/Bubberstation/Bubberstation/pull/1876)
[#1841: 'Bounty cube export gate [TM ONLY]' by lessthnthree at commit 2834db0e2c](https://github.com/Bubberstation/Bubberstation/pull/1841)
[#1887: '[TM ONLY] Reverts the TGUI stat panels' by StrangeWeirdKitten at commit 6cbc2d2f8b](https://github.com/Bubberstation/Bubberstation/pull/1887)
[#1458: 'Bloodsucker power refactor' by Arturlang at commit 94e774db54](https://github.com/Bubberstation/Bubberstation/pull/1458)
[#1900: 'Intern Job Tags by Azarak, Fixed' by ReturnToZender at commit 837e36114d](https://github.com/Bubberstation/Bubberstation/pull/1900)

**Comment by Odairu** [comment]
![image](https://github.com/user-attachments/assets/cf83ad71-5344-45b8-b5c9-b39d7d94d640)
![image](https://github.com/user-attachments/assets/ae87e7ed-e70e-4e57-b7cb-5be58e11dc9d)
![image](https://github.com/user-attachments/assets/d855bc80-70ec-48ed-9010-301539633b05)


If you have a suit in your loadout that has a jumpskirt and jumpsuit version, your preference here
![image](https://github.com/user-attachments/assets/f9e71e27-34bc-427b-99eb-026395fd9627)
will determine which version you wear.

**Comment by YakumoChen** [comment]
You completely missed the title and description @Odairu 

This bug only applies to **Assistants**
It even displays the bug on the character select screen
![image](https://github.com/user-attachments/assets/61e708f6-1183-4d96-a810-81214ea01114)
![image](https://github.com/user-attachments/assets/bd5d30cf-f22f-4806-9be1-2efcdab7920f)
Note that this is the job and loadout view respectively
