### ISSUE TITLE
[Bounty] $10 to apply crawling under tables from Cortical Borers to any mob, not just cortical borers

### ISSUE THREAD

**Issue by projectkepler-ru** [Bubberstation/Bubberstation#1921]
### Discussed in https://github.com/Bubberstation/Bubberstation/discussions/1804

<div type='discussions-op-text'>

<sup>Originally posted by **ReturnToZender** July 17, 2024</sup>
May need some slight balancing work, in which case price is negotiable.

Currently, cortical borers are the only mob that can crawl under a table. I want to change that so my fellows can be under my table to, uh, hide from Security, yes.</div>

**Comment by Odairu** [comment]
this can be closed
