### ISSUE TITLE
Prisoners can be interns

### ISSUE THREAD

**Issue by nikothedude** [Bubberstation/Bubberstation#1939]
Reporting client version: 515.1637

## Issue Summary

Title.

## Round ID:
5125

## Testmerges:
- [Public Logging Update](https://github.com/Bubberstation/Bubberstation/pull/1545)
- [GAS 2 - Part 2 - The Sequel, the worm, what you have been waiting for](https://github.com/Bubberstation/Bubberstation/pull/1471)
- [[Bounty] Vore 4.0](https://github.com/Bubberstation/Bubberstation/pull/1808)
- [[Modular] Gives shadekin A BUNCH of stuff to make them closer to being accurate to their origination lore.](https://github.com/Bubberstation/Bubberstation/pull/1501)
- [[TM ONLY] Reverts the TGUI stat panels](https://github.com/Bubberstation/Bubberstation/pull/1887)
- [The offstation cargo update (Ready for review)](https://github.com/Bubberstation/Bubberstation/pull/1764)
- [Removes code edits allowing Botany plants to mutate any botany trait](https://github.com/Bubberstation/Bubberstation/pull/1896)
- [Intern Job Tags by Azarak, Fixed](https://github.com/Bubberstation/Bubberstation/pull/1900)
- [Limits movement speed to about x2 the base movespeed](https://github.com/Bubberstation/Bubberstation/pull/1828)
- [[TM ONLY] Unfucking disease outbreaks/transmission](https://github.com/Bubberstation/Bubberstation/pull/1919)
- [Bounty cube export gate [TM ONLY]](https://github.com/Bubberstation/Bubberstation/pull/1841)
- [[PORT][TM ONLY] New Health Analyzer from TGMC](https://github.com/Bubberstation/Bubberstation/pull/1882)

## Reproduction:

Spawn as a prisoner for the first time. Youre somehow an intern? Literally how

**Comment by Majkl-J** [comment]
https://github.com/Bubberstation/Bubberstation/pull/1900/commits/cdb2500aa58717af1b2e22c47c84063b4ff20b19
