### ISSUE TITLE
Organ Bounties are completely broken and do not accept any type or tier of organ.

### ISSUE THREAD

**Issue by BundayBunBun** [Bubberstation/Bubberstation#1947]
## Issue Summary
After the recent bounty nerf for medical organ bounties, you can no longer supply any tier of organ for bounties on the bounty pad, even organic ones. It just isn't accepted.

## Round ID: 
5132

## Reproduction:
Go to the bounty pad at cargo and attempt to turn in any organ bounty with any type of organ, synthetic or organic ones.

**Comment by BundayBunBun** [comment]
Round ID copied wrong, It's 5132 :(

**Comment by Odairu** [comment]
https://github.com/Skyrat-SS13/Skyrat-tg/pull/29252 fixes this
