### ISSUE TITLE
Can't set mmi/positronic brain preference

### ISSUE THREAD

**Issue by Shroopy** [Bubberstation/Bubberstation#1958]
## Issue Summary
There's a preference to choose whether your character has an mmi or positronic brain when you're playing a cyborg or synth, but it doesn't show up in the character lore menu or in the character visuals menu. The preference is brain_type in the code.

**Comment by Odairu** [comment]
![image](https://github.com/user-attachments/assets/0bf58479-979c-4869-a783-ad97e4867bb3)
its at the bottom of the lore tab

**Comment by Shroopy** [comment]
Ah I figured it out, it's because there's two scrollbars and I needed to scroll down on the second
