### ISSUE TITLE
Offset on newly built directional windows

### ISSUE THREAD

**Issue by RidiueV1** [Bubberstation/Bubberstation#1976]
### Client Version

515.1642

### Issue Summary

Issue is regarding the offset of newly built directional windows, not map placed ones.

This is a visual issue that has very little impact on making things like gas but the visual is a bit off by a half tile as shown below.

![God why](https://github.com/user-attachments/assets/28b2f145-3bb1-4e99-8953-be3943ef9dfe)

This issue only pertains to newly made directional window tiles, regular box tiles are just fine I have more images showing this to be the case. I will place them here.
![2](https://github.com/user-attachments/assets/8066c906-6767-4f53-9684-976adf8501a0)
![3](https://github.com/user-attachments/assets/85e4a7da-3b49-480b-b739-17adae23677f)
![4](https://github.com/user-attachments/assets/157ab0c2-1322-4fc9-a9f9-5778edd98ee0)
![5](https://github.com/user-attachments/assets/77273d31-7b80-49c6-b721-6dd10afbc5a4)

The image below is from the Atmos lobby on Blueshift, it shows the difference of a newly made one (Middle) to the others on the sides.
![6](https://github.com/user-attachments/assets/a777d957-17f7-4261-8de8-ded053da4743)

### Round ID

5183+

### Reproduction steps

Step 1. Grab an RCD as Engi or really anyone.
Step 2. Build a directional window using the RCD anywhere on a valid tile.
Step 3. Behold the unholy offset and weep.

**Comment by nikothedude** [comment]
id argue this deserve a CODECON 4 because it can be really disorienting to play around

**Comment by Cyprex** [comment]
wtf

**Comment by Majkl-J** [comment]
> wtf

https://github.com/Skyrat-SS13/Skyrat-tg/pull/29526
