### ISSUE TITLE
You cannot eat honey sweetrolls.

### ISSUE THREAD

**Issue by MaSvedish** [Bubberstation/Bubberstation#1977]
### Client Version

515.1641

### Issue Summary

When I attempt to eat honey sweetrolls [one made by hand, havent tried spawned ones], you cannot. 

### Round ID

5184

### Test Merges

- [Public Logging Update](https://github.com/Bubberstation/Bubberstation/pull/1545)
- [GAS 2 - Part 2 - The Sequel, the worm, what you have been waiting for](https://github.com/Bubberstation/Bubberstation/pull/1471)
- [[Modular] Gives shadekin A BUNCH of stuff to make them closer to being accurate to their origination lore.](https://github.com/Bubberstation/Bubberstation/pull/1501)
- [[TM ONLY] Reverts the TGUI stat panels](https://github.com/Bubberstation/Bubberstation/pull/1887)
- [The offstation cargo update (Ready for review)](https://github.com/Bubberstation/Bubberstation/pull/1764)
- [Removes code edits allowing Botany plants to mutate any botany trait](https://github.com/Bubberstation/Bubberstation/pull/1896)
- [Limits movement speed to about x2 the base movespeed](https://github.com/Bubberstation/Bubberstation/pull/1828)
- [[TM ONLY] Unfucking disease outbreaks/transmission](https://github.com/Bubberstation/Bubberstation/pull/1919)
- [[PORT][TM ONLY] New Health Analyzer from TGMC](https://github.com/Bubberstation/Bubberstation/pull/1882)
- [Removes the n-spector contraband scanning](https://github.com/Bubberstation/Bubberstation/pull/1872)
- [Revenant Micro Patch](https://github.com/Bubberstation/Bubberstation/pull/1959)
- [Adds the xiarn and a related spawner, a admin only podperson variant](https://github.com/Bubberstation/Bubberstation/pull/1966)
- [Abductor machines no longer check for species when deciding if you can use it or not](https://github.com/Bubberstation/Bubberstation/pull/1964)

### Reproduction steps

Eat a honey sweet role.
Sob.

**Comment by Majkl-J** [comment]
Known issue on tg, and already mirrored there
