### ISSUE TITLE
Job preferences do not accurately show the required playtime for a job

### ISSUE THREAD

**Issue by nikothedude** [Bubberstation/Bubberstation#1993]
### Client Version:

515.1637

### Issue Summary:

Title.

![image](https://github.com/user-attachments/assets/1f36fe3e-4a55-4d5b-a8d6-46e2e7cdd9f2)

They seem to be showing the default values, instead of the bubber values.

For example - nettles told me QM takes 30 hours, but you can see it takes 15. This caused confusuon where I had 40 h ours of in sec, above the amount it says I needed - but the truth is that it takes 60. 

### Round ID:

5224

### Test Merge Information:

- [Public Logging Update](https://github.com/Bubberstation/Bubberstation/pull/1545)
- [GAS 2 - Part 2 - The Sequel, the worm, what you have been waiting for](https://github.com/Bubberstation/Bubberstation/pull/1471)
- [[TM ONLY] Reverts the TGUI stat panels](https://github.com/Bubberstation/Bubberstation/pull/1887)
- [The offstation cargo update (Ready for review)](https://github.com/Bubberstation/Bubberstation/pull/1764)
- [Removes code edits allowing Botany plants to mutate any botany trait](https://github.com/Bubberstation/Bubberstation/pull/1896)
- [Limits movement speed to about x2 the base movespeed](https://github.com/Bubberstation/Bubberstation/pull/1828)
- [[TM ONLY] Unfucking disease outbreaks/transmission](https://github.com/Bubberstation/Bubberstation/pull/1919)
- [[PORT][TM ONLY] New Health Analyzer from TGMC](https://github.com/Bubberstation/Bubberstation/pull/1882)
- [Revenant Micro Patch](https://github.com/Bubberstation/Bubberstation/pull/1959)
- [Adds the xiarn and a related spawner, a admin only podperson variant](https://github.com/Bubberstation/Bubberstation/pull/1966)
- [Abductor machines no longer check for species when deciding if you can use it or not](https://github.com/Bubberstation/Bubberstation/pull/1964)
- [Reworks (mostly) and renames all the storytellers and improves the code. (TM Only, for now)](https://github.com/Bubberstation/Bubberstation/pull/1980)
- [Bloodsucker power refactor](https://github.com/Bubberstation/Bubberstation/pull/1458)
- [Dollification Admin Smite](https://github.com/Bubberstation/Bubberstation/pull/1991)

### Reproduction Steps:

1. Open job menu
2. See how its wrong lol

**Comment by ReturnToZender** [comment]
You have 15h remaining in QM because QM requires 40 hours in supply, but also, you're right, based on your image of your playtime some of these are just wrong. You have 10h in Command so Captain and NTC should both say you have 30h remaining, _not_ 40. Weird.

**Comment by nikothedude** [comment]
> You have 15h remaining in QM because QM requires 40 hours in supply (and you have about 25), but also, you're right, based on your image of your playtime some of these are just wrong. You have 10h in Command so Captain and NTC should both say you have 30h remaining, _not_ 40. Weird.

actually, if its true it changes based on REMANING time needed, this makes a lot more sense, since 

the image youre looking at is actually my TG playtime, so i have 0h here

guess im a fool - just didnt know it changed based on REMAINING time

**Comment by nikothedude** [comment]
meant to close at not planned but w/e
