### ISSUE TITLE
Blueshift tcomms camera console doesn't have any cameras linked

### ISSUE THREAD

**Issue by SapphoQueer** [Bubberstation/Bubberstation#2015]
### Client Version:

515.1642

### Issue Summary:

![image](https://github.com/user-attachments/assets/afee2d12-9531-4474-8668-aa4ea287c74b)
This camera console isn't linked to any cameras

### Round ID:

5259

### Reproduction Steps:

1. Click camera console
2. See no cameras are linked
3. cry

**Comment by Swiftfeather** [comment]
We've deactivated blueshift and this will likely be its permanent retirement from Bubberstation. If it comes back this is an issue that would need to be made on skyrat's github.
