### ISSUE TITLE
Mech domination upgrade for Malfunctioning AI breaks the Malf UI

### ISSUE THREAD

**Issue by SynergyJohn** [Bubberstation/Bubberstation#2021]
### Client Version:

515-1643

### Issue Summary:

When you buy the mech domination upgrade, it will make the Malfunction UI where you buy upgrades bluescreen with the NTOS message.

### Reproduction Steps:

1. Become a Malfunctioning AI
2. Purchase Mech Domination
3. Attempt to enter the Upgrade UI again

**Comment by Odairu** [comment]
This no longer happens (just tested on local)
![image](https://github.com/user-attachments/assets/f7361177-4734-45a0-bebb-11a946125a2c)
its not there because I bought it
