### ISSUE TITLE
Ghosts are able to disable window air bags

### ISSUE THREAD

**Issue by Tawaporah** [Bubberstation/Bubberstation#2022]
### Client Version:

515.1642

### Issue Summary:

As a ghost, alt+clicking certain windows that are examined to disable the air bags, well, disables the airbags. 

### Round ID:

5273

### Test Merge Information:

- [Public Logging Update](https://github.com/Bubberstation/Bubberstation/pull/1545)
- [GAS 2 - Part 2 - The Sequel, the worm, what you have been waiting for](https://github.com/Bubberstation/Bubberstation/pull/1471)
- [[TM ONLY] Reverts the TGUI stat panels](https://github.com/Bubberstation/Bubberstation/pull/1887)
- [The offstation cargo update (Ready for review)](https://github.com/Bubberstation/Bubberstation/pull/1764)
- [[TM ONLY] Unfucking disease outbreaks/transmission](https://github.com/Bubberstation/Bubberstation/pull/1919)
- [[PORT][TM ONLY] New Health Analyzer from TGMC](https://github.com/Bubberstation/Bubberstation/pull/1882)
- [Revenant Micro Patch](https://github.com/Bubberstation/Bubberstation/pull/1959)
- [Adds the xiarn and a related spawner, a admin only podperson variant](https://github.com/Bubberstation/Bubberstation/pull/1966)
- [Abductor machines no longer check for species when deciding if you can use it or not](https://github.com/Bubberstation/Bubberstation/pull/1964)
- [Reworks (mostly) and renames all the storytellers and improves the code. (TM Only, for now)](https://github.com/Bubberstation/Bubberstation/pull/1980)
- [Bloodsucker power refactor](https://github.com/Bubberstation/Bubberstation/pull/1458)
- [Dollification Admin Smite](https://github.com/Bubberstation/Bubberstation/pull/1991)

### Reproduction Steps:

1. Examine any full tile window.
2. If it says "press alt-click to remove airbag"
3. Press Alt+click on said window.

**Comment by Majkl-J** [comment]
https://github.com/Bubberstation/Bubberstation/pull/2117
