### ISSUE TITLE
Silent Radio Component do not work as intended

### ISSUE THREAD

**Issue by DragonbornTheWolf** [Bubberstation/Bubberstation#2025]
### Client Version:

515.1643

### Issue Summary:

So this was already known to people, but I done a bit of testing. While you have your "Loadout Item Preference" set to anything but "Place all in case", the gaiter does not give you sec comm access. However, having the option set to start the gaiter in the case will give it access to sec comms.

### Round ID:

5284

### Test Merge Information:

- [GITHUB API ERROR: RATE LIMITED](https://github.com/Bubberstation/Bubberstation/pull/1545)
- [GITHUB API ERROR: RATE LIMITED](https://github.com/Bubberstation/Bubberstation/pull/1471)
- [GITHUB API ERROR: RATE LIMITED](https://github.com/Bubberstation/Bubberstation/pull/1887)
- [GITHUB API ERROR: RATE LIMITED](https://github.com/Bubberstation/Bubberstation/pull/1764)
- [GITHUB API ERROR: RATE LIMITED](https://github.com/Bubberstation/Bubberstation/pull/1919)
- [GITHUB API ERROR: RATE LIMITED](https://github.com/Bubberstation/Bubberstation/pull/1882)
- [GITHUB API ERROR: RATE LIMITED](https://github.com/Bubberstation/Bubberstation/pull/1959)
- [GITHUB API ERROR: RATE LIMITED](https://github.com/Bubberstation/Bubberstation/pull/1966)
- [GITHUB API ERROR: RATE LIMITED](https://github.com/Bubberstation/Bubberstation/pull/1964)
- [GITHUB API ERROR: RATE LIMITED](https://github.com/Bubberstation/Bubberstation/pull/1980)
- [GITHUB API ERROR: RATE LIMITED](https://github.com/Bubberstation/Bubberstation/pull/1458)
- [GITHUB API ERROR: RATE LIMITED](https://github.com/Bubberstation/Bubberstation/pull/1991)
- [GITHUB API ERROR: RATE LIMITED](https://github.com/Bubberstation/Bubberstation/pull/2007)

### Reproduction Steps:

1. Have the "Tacticool Neck Gaiter" mask item seleted in loadout
2. Set "Loadout Item Preference" to "Place all in case"
3. Spawn in and wear the gaiter
4. Wait for someone to talk in security comms

**Comment by projectkepler-ru** [comment]
similarly forr some reason cube sometime still play radio message
@Majkl-J 

The most fucking annoying part
is that this is not consistent
Because that round i showed you the screenshot on we can VERIFIABLY CONFIRM it the gaiter. it showed the radio
but the next few days i tested the bounty cube it didnt show radio
but then today on blueshift
it definitely did show the radio

I have
no fucking idea what's the root cause of this. and it honestly upsets me.
