### ISSUE TITLE
Pulsating tumor ghost role breaks.

### ISSUE THREAD

**Issue by Nus127** [Bubberstation/Bubberstation#2065]
### Client Version:

151.1642

### Issue Summary:

Pulsating tumors once you insert a legion core (any type), would probe the ghosts for a role to take up.
however, due to how ghost role selection takes place here, it bugs the tumour out if no ghost selects to take the position.

This may be due to the fact that when a ghost role is available, it automatically says "yes" on the sever's end for the role, even if no ghost takes it. Normally, a tumor would go dormant again if no ghost said yes to be it, but because the server itself said yes, despite no ghost wanting to become it through the 30 second timer, the tumor doesnt go dormant and permanently stays active. 

This leads to miners being unable to active ANY other tumor because they are waiting to fight the one they had activated prior that this bug effects due to tumors having code to forcibly teleport someone back to the arena 

### Round ID:

5368

### Reproduction Steps:

1. Place a legion core inside of a tumor
2. Activate the tumor and wait the 30 seconds of a ghost role selection timer
3. observe as nothing happens, the tumor doesnt go dormant and you're unable to activate any other tumor

**Comment by Majkl-J** [comment]
This was a tg bug with how ghost queries always sent out a list filled with nulls even when nobody picked it. Should be fixed next upstream

**Comment by Majkl-J** [comment]
Closing as fixed as we seem to have the fixes now as far as I can tell
