### ISSUE TITLE
Latejoin Medical Doctors get blank IDs

### ISSUE THREAD

**Issue by sionallona** [Bubberstation/Bubberstation#2095]
### Client Version:

515.1641

### Issue Summary:

When latejoining as a Medical Doctor, instead of receiving a trimmed ID, you receive a blank one with no access. The HoP ID trim machine seems unable to apply Medical Doctor trims to **any** ID, not just this one, as well. Occurred on Tramstation and happens regardless of your job title (Virologist, Medical Doctor, etc). Blaberface tested this with me to ensure it was not a clientside issue with my own prefs. Unsure if it works on other maps atm.
![image](https://github.com/user-attachments/assets/cbea589a-4932-4abf-9ccc-52a811147d94)

### Round ID:

5453

### Test Merge Information:

- [Public Logging Update](https://github.com/Bubberstation/Bubberstation/pull/1545)
- [[TM ONLY] Reverts the TGUI stat panels](https://github.com/Bubberstation/Bubberstation/pull/1887)
- [Bloodsucker power refactor](https://github.com/Bubberstation/Bubberstation/pull/1458)
- [[Ready for Testmerge] Adds a new heretic path: Path of Exile](https://github.com/Bubberstation/Bubberstation/pull/2020)
- [[PORT][TM ONLY] New Health Analyzer from TGMC](https://github.com/Bubberstation/Bubberstation/pull/1882)
- [[Modular] Doubles the amount of sacrifices required to ascend](https://github.com/Bubberstation/Bubberstation/pull/1915)
- [Vetted System conversion to SQL](https://github.com/Bubberstation/Bubberstation/pull/2075)
- [Fix delete button on belly messages seeming to delete the wrong message.](https://github.com/Bubberstation/Bubberstation/pull/2087)
- [[TM ONLY] Unfucking disease outbreaks/transmission](https://github.com/Bubberstation/Bubberstation/pull/1919)

### Reproduction Steps:

1. Latejoin Tramstation as Medical Doctor.
2. Realize you can't enter medbay.
3. Cry.

**Comment by lessthnthree** [comment]
@sionallona Do you have an alternate job title set? If yes, this might be a TG bug.

If it is happening with alt job title, try switching to normal Medical Doctor and see if it still does do it.

**Comment by lessthnthree** [comment]
No reproduction found.
