### ISSUE TITLE
Malf AI doesn't roll properly

### ISSUE THREAD

**Issue by Swiftfeather** [Bubberstation/Bubberstation#2108]
### Issue Summary:

When storyteller fires midround malf it often fails. 

Create antagonists verb does not make a malf even if there's an AI with malf enabled. 

### Reproduction Steps:

Storytellers fires malf
It fails to give AI malf even if they have it enabled

Create antagonist fails too

Applying directly via tp is the only way

**Comment by Majkl-J** [comment]
Could be failing due to low antag cap, fired fine in my testing.
