### ISSUE TITLE
When you fish a skeleton up from lava, the tile you're on becomes impassable.

### ISSUE THREAD

**Issue by fludd12** [Bubberstation/Bubberstation#2113]
### Client Version:

515.1643

### Issue Summary:

As an ashwalker, I made a bone fishing rod. While fishing with it on lavaland tile, when I caught a charred skeleton corpse, the tile I was standing on became impassable. This happened reliably.

Notably, after an ash storm came by, the affected tiles were reverted if they were in an outside area. This does not seem to happen on properly latticed and tiled tiles.

### Round ID:

5507

### Test Merge Information:

The following pull requests are currently test merged:
[#1545: 'Public Logging Update' by nevimer at commit 687d0d08e5](https://github.com/Bubberstation/Bubberstation/pull/1545)
[#1887: '[TM ONLY] Reverts the TGUI stat panels' by StrangeWeirdKitten at commit 32ca8a004c](https://github.com/Bubberstation/Bubberstation/pull/1887)
[#2020: '[Ready for Testmerge] Adds a new heretic path: Path of Exile' by BurgerLUA at commit b78d9ce6e7](https://github.com/Bubberstation/Bubberstation/pull/2020)
[#1882: '[PORT][TM ONLY] New Health Analyzer from TGMC' by Erol509 at commit e3eead9890](https://github.com/Bubberstation/Bubberstation/pull/1882)
[#2075: 'Vetted System conversion to SQL' by nevimer at commit 567ae003e3](https://github.com/Bubberstation/Bubberstation/pull/2075)
[#1919: '[TM ONLY] Unfucking disease outbreaks/transmission' by lessthnthree at commit 6af72c50d8](https://github.com/Bubberstation/Bubberstation/pull/1919)
[#2101: 'Adds Global Event Cooldowns for Storyteller' by BurgerLUA at commit 326eb598fa](https://github.com/Bubberstation/Bubberstation/pull/2101)
[#1994: 'Bloodsucker leveling rework' by Arturlang at commit e91239e37c](https://github.com/Bubberstation/Bubberstation/pull/1994)

### Reproduction Steps:

1. Get a lavaland fishing pole.
2. Equip it with sinew string.
3. Stand on volcanic floor.
4. Fish in lava until a corpse comes out.
5. Move off the tile and try to move back on.

**Comment by Majkl-J** [comment]
Can't repro, presumably fixed some upstream merge
