### ISSUE TITLE
Unable to level up as Ventrue Vampire.

### ISSUE THREAD

**Issue by DatFrostys** [Bubberstation/Bubberstation#2130]
### Client Version:

515.1641

### Issue Summary:

As a ventrue bloodsucker, I ended up unable to level up myself or my favorite vassal despite having all the requirements to do so.

### Round ID:

5531

### Test Merge Information:

- [Public Logging Update](https://github.com/Bubberstation/Bubberstation/pull/1545)
- [[TM ONLY] Reverts the TGUI stat panels](https://github.com/Bubberstation/Bubberstation/pull/1887)
- [[Ready for Testmerge] Adds a new heretic path: Path of Exile](https://github.com/Bubberstation/Bubberstation/pull/2020)
- [Vetted System conversion to SQL](https://github.com/Bubberstation/Bubberstation/pull/2075)
- [[TM ONLY] Unfucking disease outbreaks/transmission](https://github.com/Bubberstation/Bubberstation/pull/1919)
- [Adds Global Event Cooldowns for Storyteller](https://github.com/Bubberstation/Bubberstation/pull/2101)
- [Bloodsucker leveling rework](https://github.com/Bubberstation/Bubberstation/pull/1994)

### Reproduction Steps:

1. Be a bloodsucker
2. Choose the ventrue clan
3. Acquire a vassal and make them into your favorite
4. Attempt to level them up or to level yourself up with blood thickening
5. Doesn't work.

**Comment by StrangeWeirdKitten** [comment]
@Arturlang

**Comment by Arturlang** [comment]
Fixed in https://github.com/Bubberstation/Bubberstation/pull/1994
