### ISSUE TITLE
Many clothing items have nonfunctional suit sensors

### ISSUE THREAD

**Issue by Nairbhaon** [Bubberstation/Bubberstation#2131]
### Client Version:

515.1643

### Issue Summary:

Lots of clothing items including all the bunnysuits, the default RD skirt, the gear harness, and others have suit sensors that don't show up on crew monitors.

### Reproduction Steps:

1. Put on an affected clothing item.
2. Turn sensors up to max.
3. Check crew monitor.

**Comment by lessthnthree** [comment]
Are you turning on the sensors using the ctrl-click shortcut on the uniform, or using the TGUI menu?

Also can you check in game now that https://github.com/Bubberstation/Bubberstation/pull/2121 is TM'd?

**Comment by Nairbhaon** [comment]
Seems fixed now
