### ISSUE TITLE
Can't dip/inject chems into havanian cigars

### ISSUE THREAD

**Issue by plsleavemealon** [Bubberstation/Bubberstation#2138]
### Issue Summary:

Can't dip/inject chems into havanian cigars, the cigar says its full.  This probably true of cigarettes, and other cigar variants.

This issue appeared when the ability to eat cigars/cigarettes was implemented.

### Reproduction Steps:

Grab havanian cigar, grab syringe full of chems.  Attempt to inject cigar with chem, note how it says its full.  Grab glass full of chems/drink, click cigar onto glass, note how it says its full.

**Comment by Majkl-J** [comment]
See https://github.com/tgstation/tgstation/pull/87733

**Comment by Majkl-J** [comment]
Fix merged upstream, to be pulled here
