### ISSUE TITLE
Fancy cowboy hats hide all belt worn item sprites (usually)

### ISSUE THREAD

**Issue by TacoSalad7** [Bubberstation/Bubberstation#2148]
### Client Version:

515.1643

### Issue Summary:

Wearing one of these hats causes anything on your belt to vanish from your sprite. Toolbelts, chest rigs, guns, frontier kits, all of them get layered over or something. Sucks. I have had my belt worn items unhidden when wearing a retracted modsuit.
![image](https://github.com/user-attachments/assets/ff709e0e-d1ec-4678-b2de-219b29d0d6e9)

### Reproduction Steps:

1. Wear anything belt worn
2. Wear one of those hats (wide brimmed, feathered and non feathered 100% does it)
3. Witness the vanishing act

**Comment by Majkl-J** [comment]
Apparently this is somehow real

**Comment by TacoSalad7** [comment]
> Apparently this is somehow real

Yeah, it is. And as pretty much the Sole cowboy hat user on this server it greatly hurts my steeze and style. Also, some other headwear does it, some sec helmets. I forgot to note exactly which ones but its a greater issue than just these fine western hats.

**Comment by Majkl-J** [comment]
Will soon be fixed
