### ISSUE TITLE
Civilian Computers not able to be deconstructed

### ISSUE THREAD

**Issue by ro3ger** [Bubberstation/Bubberstation#2169]
### Client Version:

515.1641

### Issue Summary:

Modular computers are unable to be deconstructed normally, you have to destroy the console via a weapon to break it down

### Round ID:

5587

### Reproduction Steps:

Try to deconstruct a civilian console/modular computer
Make sure to right click to interact with frame
Unable to deconstruct

**Comment by Odairu** [comment]
you just right click it with a wrench while interacting with the cpu
