### ISSUE TITLE
     Sakhno to Xhihao 'Rengo' Conversion craft is non-functional 

### ISSUE THREAD

**Issue by KateAnbolho** [Bubberstation/Bubberstation#2176]
### Client Version:

515.1641

### Issue Summary:

Attempting to perform the "Sakhno to Xhihao 'Rengo' Conversion" craft on either form of the Sakhno rifle is non-functional. I am unable to apply the kit to an open and pulled-back bolted rifle of either form. When attempting to apply it to a closed-bolt rifle it recognizes it is closed. 

### Round ID:

5605

### Test Merge Information:

The following pull requests are currently test merged:
[#1545: 'Public Logging Update' by nevimer at commit 687d0d08e5](https://github.com/Bubberstation/Bubberstation/pull/1545)
[#2075: 'Vetted System conversion to SQL' by nevimer at commit 567ae003e3](https://github.com/Bubberstation/Bubberstation/pull/2075)
[#1919: '[TM ONLY] Unfucking disease outbreaks/transmission' by lessthnthree at commit 6af72c50d8](https://github.com/Bubberstation/Bubberstation/pull/1919)
[#1959: 'Revenant Micro Patch' by nevimer at commit 3579ac9a9d](https://github.com/Bubberstation/Bubberstation/pull/1959)
[#2121: '[MIRROR] Suit sensors updates/fixes package' by lessthnthree at commit 88e661856d](https://github.com/Bubberstation/Bubberstation/pull/2121)
[#2136: '[port] Moth PR for Central' by nevimer at commit 1ba97390cb](https://github.com/Bubberstation/Bubberstation/pull/2136)
[#2137: '[TM Only] Removes skyrat wound chance with total damage enhancement.' by Swiftfeather at commit b01be119dd](https://github.com/Bubberstation/Bubberstation/pull/2137)
[#2007: 'Fleshmind (but using basic mob AI controllers)' by StrangeWeirdKitten at commit 2918eb0a66](https://github.com/Bubberstation/Bubberstation/pull/2007)
[#2091: 'Adds the Vortex Luxury Emergency Shuttle' by ChromeFoxxity at commit 2d1ca289ec](https://github.com/Bubberstation/Bubberstation/pull/2091)
[#2125: 'Brings upstream cargo features in line with our cargo changes' by ReturnToZender at commit d5937f344f](https://github.com/Bubberstation/Bubberstation/pull/2125)
[#2058: 'Is that a PDA in your pocket or are you just happy to subtle me' by lessthnthree at commit e5b5ce8435](https://github.com/Bubberstation/Bubberstation/pull/2058)
[#2167: 'Right clicking on airlocks will now give the AI a chat prompt to allow them to open the door without looking at you' by Odairu at commit cd37ad48df](https://github.com/Bubberstation/Bubberstation/pull/2167)
[#2173: 'Bangle Sprites: The Sequel' by Offwrldr at commit c1847fc0a4](https://github.com/Bubberstation/Bubberstation/pull/2173)

### Reproduction Steps:

1. Suffer RNG to buy the Percision Rifle
2. Buy the conversion kit stock to sell as a funny rifle
3. Unable to apply rifle upgrade kit
4. *scream

**Comment by Majkl-J** [comment]
![image](https://github.com/user-attachments/assets/30c0bbe2-7f4b-4809-aa6b-4c46ced9085c)

Can't reproduce, did you try emptying the rifle first?
