### ISSUE TITLE
Dental Implanting just DOES NOT work

### ISSUE THREAD

**Issue by Hotmud9** [Bubberstation/Bubberstation#2208]
### Client Version:

515.1643

### Issue Summary:

Attempting to perform a dental implant goes well except for when you actually try to start drilling into the mouth. It will just loop back in on itself, continually requesting the drill be used.

### Round ID:

5720

### Test Merge Information:

- [Adds the Vortex Luxury Emergency Shuttle](https://github.com/Bubberstation/Bubberstation/pull/2091)
- [Public Logging Update](https://github.com/Bubberstation/Bubberstation/pull/1545)
- [[TM ONLY] Unfucking disease outbreaks/transmission](https://github.com/Bubberstation/Bubberstation/pull/1919)
- [Storyteller 2.2](https://github.com/Bubberstation/Bubberstation/pull/2116)
- [Space MP5 - Redux](https://github.com/Bubberstation/Bubberstation/pull/2199)
- [Xenomorph Hybrid Rework](https://github.com/Bubberstation/Bubberstation/pull/2198)
- [Succumbing now alerts everyone around you that you gave up on life.](https://github.com/Bubberstation/Bubberstation/pull/2193)
- [[TestMerge Only] ITS A SPOOKY MONTH](https://github.com/Bubberstation/Bubberstation/pull/2184)
- [Patches a bug with adding vetted users.](https://github.com/Bubberstation/Bubberstation/pull/2200)
- [Investigate Stat Panel as a Stutter cause](https://github.com/Bubberstation/Bubberstation/pull/2201)
- [Limbgrown bodies.](https://github.com/Bubberstation/Bubberstation/pull/1842)

### Reproduction Steps:

1. start a surgery on mouth for dental implanting
2. attempt to drill into their mouth with a surgical drill
3. Fail because what the fuck why drill no workie
4. Cry.

**Comment by lessthnthree** [comment]
@Hotmud9 Can you try again, it works fine for me. Was it a specific drill type?

**Comment by lessthnthree** [comment]
No issue found.
