### ISSUE TITLE
Septembers Changelog is broken

### ISSUE THREAD

**Issue by StrangeWeirdKitten** [Bubberstation/Bubberstation#2226]
### Client Version:

N/A

### Issue Summary:

![image](https://github.com/user-attachments/assets/2cfa9a8d-368e-40b5-aac5-99dca879720d)

Duplicate mapping keys. Will need to be fixed.

### Round ID:

N/A

### Test Merge Information:

N/A

### Reproduction Steps:

N/A

**Comment by lessthnthree** [comment]
I fixed the mapping key, and still got a new error. So not as quick as I thought it'd be.
