### ISSUE TITLE
Instruments not working properly

### ISSUE THREAD

**Issue by Lizardslizards** [Bubberstation/Bubberstation#2236]
### Client Version:

515.1639

### Issue Summary:

When you try to play songs on any instruments (Xylophone, trumpet, harmonica, banjo etc) the limit for the number of characters the song may have is now drastically less than previously and you simply cannot play the songs on the TG wiki "Songs" page anymore physically. 

### Reproduction Steps:

Get any instrument. Copy the formatted song from the TG wiki "Songs" page of your choosing. Import the song as a new song on the popup pasting the text into the field. Try to click submit. Be met with failure.

(Note: I am new to submitting bugs here and I am not sure about the Round ID and Test Merge information, tips are appreciated)

**Comment by lessthnthree** [comment]
Thanks. It's an upstream issue logged here: https://github.com/tgstation/tgstation/issues/83654
