### ISSUE TITLE
Basicmob mob AI doesn't work

### ISSUE THREAD

**Issue by SapphoQueer** [Bubberstation/Bubberstation#2240]
### Client Version:

515.1642

### Issue Summary:

Go to lavaland. 
Basicmobs do nothing.
They just stand there. 
You can beat their ass. They do nothing.

### Round ID:

5773

### Test Merge Information:

The following pull requests are currently test merged:
[#2091: 'Adds the Vortex Luxury Emergency Shuttle' by ChromeFoxxity at commit 1d89244e39](https://github.com/Bubberstation/Bubberstation/pull/2091)
[#1545: 'Public Logging Update' by nevimer at commit 687d0d08e5](https://github.com/Bubberstation/Bubberstation/pull/1545)
[#1919: '[TM ONLY] Unfucking disease outbreaks/transmission' by lessthnthree at commit 250e2f4a4e](https://github.com/Bubberstation/Bubberstation/pull/1919)
[#2116: 'Storyteller 2.2' by Majkl-J at commit dde494b59a](https://github.com/Bubberstation/Bubberstation/pull/2116)
[#2199: 'Space MP5 - Redux' by Offwrldr at commit 4b4316633d](https://github.com/Bubberstation/Bubberstation/pull/2199)
[#2198: 'Xenomorph Hybrid Rework' by Aroliacue at commit 0cca5ab780](https://github.com/Bubberstation/Bubberstation/pull/2198)
[#2193: 'Succumbing now alerts everyone around you that you gave up on life.' by StrangeWeirdKitten at commit 5e60bb8a88](https://github.com/Bubberstation/Bubberstation/pull/2193)
[#2200: 'Patches a bug with adding vetted users.' by nevimer at commit fe397409ff](https://github.com/Bubberstation/Bubberstation/pull/2200)
[#2201: 'Investigate Stat Panel as a Stutter cause' by nevimer at commit 1a82d06b50](https://github.com/Bubberstation/Bubberstation/pull/2201)
[#1842: 'Limbgrown bodies.' by xXPawnStarrXx at commit b24d0250c7](https://github.com/Bubberstation/Bubberstation/pull/1842)
[#2206: '(Port) MKUltra - Mind Control' by xPokee at commit 4397ec0409](https://github.com/Bubberstation/Bubberstation/pull/2206)
[#2211: 'halloween: a 2spooky update' by lessthnthree at commit a29fe8b3ee](https://github.com/Bubberstation/Bubberstation/pull/2211)

### Reproduction Steps:

Go to lavaland. 
Simplemobs do nothing.
They just stand there. 
You can beat their ass. They do nothing.

https://github.com/user-attachments/assets/6e05d227-2e00-40ba-b672-ceb5725014da

**Comment by StrangeWeirdKitten** [comment]
Will need to check the MC and run it on local. But this seems to be a massive issue, yes.

**Comment by SapphoQueer** [comment]
okay fuck it's all simplemobs
