### ISSUE TITLE
Hypnosis_pref game preference error

### ISSUE THREAD

**Issue by Shadow-Quill** [Bubberstation/Bubberstation#2246]
### Client Version:

515.1643

### Issue Summary:

![image](https://github.com/user-attachments/assets/15684e77-7f82-4934-9be5-2ec3672fc6af)
Likely from upstream pull.

### Round ID:

5774

### Reproduction Steps:

Open game preferences.

**Comment by StrangeWeirdKitten** [comment]
#2206

**Comment by xPokee** [comment]
This should be fixed when the test merges update.
