### ISSUE TITLE
Drying rack dosent dry weed.

### ISSUE THREAD

**Issue by LeatherGnome** [Bubberstation/Bubberstation#2247]
### Client Version:

515.1644

### Issue Summary:

The drying rack dosent produce the dried variants of weed, catnip or other dry'ables, making it impossible to make joints without admin intervation.

### Round ID:

5774

### Test Merge Information:

Does this need to be put in?

### Reproduction Steps:

1.Create drying rack on station.
2.Put in weed or anyother dryable of preffrence
3.Turn it on
4.Observe and wait.
5.Nothing happens

**Comment by Majkl-J** [comment]
Can't repro now, made rollies just fine from dry catnip and a rollingpaper, presuming fixed
