### ISSUE TITLE
Falling onto transport modules from multiple z-levels does no damage if no solid turf.

### ISSUE THREAD

**Issue by OfflcerSam** [Bubberstation/Bubberstation#2256]
### Client Version:

515.1644

### Issue Summary:

I assume the fall damage is based on a variable in turfs somewhere, I kinda understand that the transport module isn't really turf but rather a structure. So if you fall from any height it will do no damage if the turf is open space underneath the transport module. This is a relatively small issue as not many maps seem to make use of the elevator system beyond like 2 levels.

### Reproduction Steps:

1. Create map with multiple z-levels and an elevator with atleast 3+ floors.
2. Tell elevator to goto floor two and jump down onto it. 
3. Game will say you hit open space turf and you take no damage.

https://github.com/user-attachments/assets/b6be3c5d-1ba5-480a-9408-0ef762065777

**Comment by IgiariValkyr** [comment]
off-topic, but is that a recreation of TenStation? 👀

**Comment by OfflcerSam** [comment]
> off-topic, but is that a recreation of TenStation? 👀

I don't know what TenStation is unfortunately, but I was making a concept skyscraper map for fun with some other random maps.

**Comment by projectkepler-ru** [comment]
Is there even a map this can happens on?

**Comment by OfflcerSam** [comment]
> Is there even a map this can happens on?

I don't think any of the included maps have any elevators that span more than two floors, Icebox station I think has like a single two floor elevator. Theres also the weird issue where the elevator music resets everytime you move in the elevator.

**Comment by OfflcerSam** [comment]
to note: this also happens with lattice as falling onto lattice makes you hit openspace and thus does no fall damage.

**Comment by lessthnthree** [comment]
Transport modules are TG. Copy paste the report over there.
