### ISSUE TITLE
Obsessed can still roll despite having the "Be Antagonist" button turned off

### ISSUE THREAD

**Issue by xPokee** [Bubberstation/Bubberstation#2258]
### Client Version:

515.1640

### Issue Summary:

Pretty much as the title says. I'm fairly sure it's unintended as no other antagonists will roll if that button is off, yet obsessed seems to roll regardless, resulting in frustrations.

### Round ID:

5785

### Test Merge Information:

- [Public Logging Update](https://github.com/Bubberstation/Bubberstation/pull/1545)
- [[TM ONLY] Unfucking disease outbreaks/transmission](https://github.com/Bubberstation/Bubberstation/pull/1919)
- [Storyteller 2.2](https://github.com/Bubberstation/Bubberstation/pull/2116)
- [Space MP5 - Redux](https://github.com/Bubberstation/Bubberstation/pull/2199)
- [Xenomorph Hybrid Rework](https://github.com/Bubberstation/Bubberstation/pull/2198)
- [Succumbing now alerts everyone around you that you gave up on life.](https://github.com/Bubberstation/Bubberstation/pull/2193)
- [Patches a bug with adding vetted users.](https://github.com/Bubberstation/Bubberstation/pull/2200)
- [Investigate Stat Panel as a Stutter cause](https://github.com/Bubberstation/Bubberstation/pull/2201)
- [Limbgrown bodies.](https://github.com/Bubberstation/Bubberstation/pull/1842)
- [(Port) MKUltra - Mind Control](https://github.com/Bubberstation/Bubberstation/pull/2206)
- [halloween: a 2spooky update](https://github.com/Bubberstation/Bubberstation/pull/2211)
- [Adds *yip and *yipyip](https://github.com/Bubberstation/Bubberstation/pull/2254)
- [Fix job title in head arrival radio messages being empty](https://github.com/Bubberstation/Bubberstation/pull/2255)

### Reproduction Steps:

1. Join the game with be antagonist toggled off but obsessed enabled in your antagonist preferences.
2. Wait for obsessed to roll
3. Get hit with an unwanted antagonist roll despite your preferences being off

**Comment by Majkl-J** [comment]
Obsessed when running isn't an antag event but a normal event. Why? Idk but it is. Will look into

**Comment by projectkepler-ru** [comment]
> Obsessed when running isn't an antag event but a normal event. Why? Idk but it is. Will look into

prob cause its a type of brain damage I assume
