### ISSUE TITLE
Tarkon RCDs are detonated by AIs detonating RCDs, despite never having visited station Z-level for the flag.

### ISSUE THREAD

**Issue by kassori** [Bubberstation/Bubberstation#2268]
### Issue Summary:

RCD detonation is supposed to only affect RCDs that have been on the station Z-level during the shift. Malf AIs are blowing up all RCDs, regardless if they have been on the same Z-level as the station or not. Primarily an issue with Tarkon and Dauntless.

### Reproduction Steps:

Detonate RCDs as Malf
See all RCDs on every Z level detonate

**Comment by nevimer** [comment]
`	var/list/bombable = SSmapping.levels_by_trait(ZTRAIT_STATION)
	for(var/obj/item/construction/rcd/rcd in world)
		if(rcd.z == locate(rcd.z) in bombable)
		dothings()`
should sort this out for anyone willing to make the change
