### ISSUE TITLE
SAD dumps your implants onto the ground when reapplying prefs

### ISSUE THREAD

**Issue by lessthnthree** [Bubberstation/Bubberstation#2273]
### Client Version:

515.1641

### Issue Summary:

SAD dumps out a player's currently installed implants when resetting their preferences

### Round ID:

5803

### Reproduction Steps:

- Have an implant in your mob, such as a breathing implant
- Use the SAD to reset your mob
- The implant you had installed is ejected to the floor

**Comment by YakumoChen** [comment]
It does duplicate the ones in your loadout

**Comment by projectkepler-ru** [comment]
Oversight
