### ISSUE TITLE
Mapvotes reverted to weighted, hidden

### ISSUE THREAD

**Issue by Shadow-Quill** [Bubberstation/Bubberstation#2284]
### Issue Summary:

Mapvotes have been reverted to a weighted vote, with vote tallies hidden when results are revealed.

### Round ID:

5814

### Reproduction Steps:

https://github.com/Bubberstation/Bubberstation/blob/ed276bb2eda5ea61d6aa59f5843d906e5f5a84ba/code/controllers/subsystem/map_vote.dm#L82

**Comment by lessthnthree** [comment]
Map vote is a subsystem now and can't quickly be changed to winner takes all voting. But in the meantime we can unhide the vote.

**Comment by lessthnthree** [comment]
Simple voting will be included with https://github.com/tgstation/tgstation/pull/87218

**Comment by lessthnthree** [comment]
Okay, added simple voting to the PR.
