### ISSUE TITLE
Entering into Soulcatcher as observer hides your name and flavor text

### ISSUE THREAD

**Issue by KeptheKobold** [Bubberstation/Bubberstation#2292]
### Client Version:

515.1641

### Issue Summary:

After observing from lobby and joining someones soulcatcher, you are given a random name and flavor text is locked to "The soulcatcher soul lacks a discernible form."

This should only happen if you die in round and then join a bodycatcher, restoring the name and flavortext if your body is scanned with an Evoker

### Round ID:

5828

### Test Merge Information:

[#1545: 'Public Logging Update' by nevimer at commit 687d0d08e5](https://github.com/Bubberstation/Bubberstation/pull/1545)
[#1919: '[TM ONLY] Unfucking disease outbreaks/transmission' by lessthnthree at commit 250e2f4a4e](https://github.com/Bubberstation/Bubberstation/pull/1919)
[#2116: 'Storyteller 2.2' by Majkl-J at commit dde494b59a](https://github.com/Bubberstation/Bubberstation/pull/2116)
[#2199: 'Space MP5 - Redux' by Offwrldr at commit 4b4316633d](https://github.com/Bubberstation/Bubberstation/pull/2199)
[#2193: 'Succumbing now alerts everyone around you that you gave up on life.' by StrangeWeirdKitten at commit 5e60bb8a88](https://github.com/Bubberstation/Bubberstation/pull/2193)
[#2200: 'Patches a bug with adding vetted users.' by nevimer at commit fe397409ff](https://github.com/Bubberstation/Bubberstation/pull/2200)
[#2201: 'Investigate Stat Panel as a Stutter cause' by nevimer at commit 1a82d06b50](https://github.com/Bubberstation/Bubberstation/pull/2201)
[#1842: 'Limbgrown bodies.' by xXPawnStarrXx at commit b24d0250c7](https://github.com/Bubberstation/Bubberstation/pull/1842)
[#2206: '(Port) MKUltra - Mind Control' by xPokee at commit 80882be2d5](https://github.com/Bubberstation/Bubberstation/pull/2206)
[#2285: 'Map vote uses simple, not weighted random / show map vote calculation and carryover info' by lessthnthree at commit 764470ca54](https://github.com/Bubberstation/Bubberstation/pull/2285)
[#2278: 'Fixes *meow and *purr emotes (and other emote third person keys)' by lessthnthree at commit 3d2148f14e](https://github.com/Bubberstation/Bubberstation/pull/2278)

### Reproduction Steps:

1. Observe into game
2. Join a soulcatcher
3. Look at your name and flavour text

**Comment by xXPawnStarrXx** [comment]
This is intentional; I'm pretty sure they didn't want people getting meta revived with this.

**Comment by xXPawnStarrXx** [comment]
It was always intended that you were unknown, it's part of why they made the overlays 'fuzzy' like you're not supposed to know what's real. The revival is actually something I changed in one of my PRs.

**Comment by KeptheKobold** [comment]
I do distinctly remember them not obscuring pure observers before having met a person by them joining my nif as ghost with flavortext and proper name, but if it's an intentional change then this issue can be closed and I'll make a suggestion elsewhere

**Comment by Majkl-J** [comment]
Apparently this is intentional
