### ISSUE TITLE
Power sink makes the APC environment channel flicker on and off

### ISSUE THREAD

**Issue by lessthnthree** [Bubberstation/Bubberstation#2294]
### Client Version:

515.1641

### Issue Summary:

Power sink makes the APCs environment channel constantly cycle on and off. This is probably a TG bug, but I'm putting it here so I remember to do something about it.

### Round ID:

5828

### Reproduction Steps:

Power sink the powernet

**Comment by lessthnthree** [comment]
Powersink isn't even an /obj/machinery arghhjhhh../df/.df

**Comment by Majkl-J** [comment]
I haven't seen this happen in testing anymore
