### ISSUE TITLE
XL beakers are still 120u instead of 150u

### ISSUE THREAD

**Issue by LordQuailius** [Bubberstation/Bubberstation#2304]
### Client Version:

515.1642

### Issue Summary:

The description of the XL beaker says they can hold 150u, when they can still only hold 120u mechanically

### Round ID:

5845

### Test Merge Information:

- [Public Logging Update](https://github.com/Bubberstation/Bubberstation/pull/1545)
- [[TM ONLY] Unfucking disease outbreaks/transmission](https://github.com/Bubberstation/Bubberstation/pull/1919)
- [Storyteller 2.2](https://github.com/Bubberstation/Bubberstation/pull/2116)
- [Space MP5 - Redux](https://github.com/Bubberstation/Bubberstation/pull/2199)
- [Succumbing now alerts everyone around you that you gave up on life.](https://github.com/Bubberstation/Bubberstation/pull/2193)
- [Patches a bug with adding vetted users.](https://github.com/Bubberstation/Bubberstation/pull/2200)
- [Investigate Stat Panel as a Stutter cause](https://github.com/Bubberstation/Bubberstation/pull/2201)
- [Limbgrown bodies.](https://github.com/Bubberstation/Bubberstation/pull/1842)
- [(Port) MKUltra - Mind Control](https://github.com/Bubberstation/Bubberstation/pull/2206)
- [Buffs the Chill](https://github.com/Bubberstation/Bubberstation/pull/2290)

### Reproduction Steps:

1.) Obtain a XL beaker
2.) Put it into a chem machine to see that it's capped at 120u

**Comment by lessthnthree** [comment]
Fixed in https://github.com/Bubberstation/Bubberstation/pull/2302

**Comment by LordQuailius** [comment]
The examine will say that it can hold 150u, but actually putting it in a machine shows it's only 120u. Mechanically they can only hold 120u despite that description in 2302

![image](https://github.com/user-attachments/assets/19ce1c41-88cc-435a-afaf-2b43fba2c2a4)

**Comment by lessthnthree** [comment]
![image](https://github.com/user-attachments/assets/41de61d0-3844-4b47-8616-d08305e34e8f)
 It's not live on the server yet.

**Comment by LordQuailius** [comment]
oh mb then
