### ISSUE TITLE
The 'tallest' body size option causes sprite issues

### ISSUE THREAD

**Issue by xPokee** [Bubberstation/Bubberstation#2317]
### Client Version:

515.1640

### Issue Summary:

When you join as a character with the tallest body height it cuts off a portion of their head, mostly just the hair and ears.
![image](https://github.com/user-attachments/assets/b529e84f-9cd2-4acc-903c-506d4b56e8ea)

### Round ID:

5867

### Test Merge Information:

- [Public Logging Update](https://github.com/Bubberstation/Bubberstation/pull/1545)
- [[TM ONLY] Unfucking disease outbreaks/transmission](https://github.com/Bubberstation/Bubberstation/pull/1919)
- [Storyteller 2.2](https://github.com/Bubberstation/Bubberstation/pull/2116)
- [Space MP5 - Redux](https://github.com/Bubberstation/Bubberstation/pull/2199)
- [Succumbing now alerts everyone around you that you gave up on life.](https://github.com/Bubberstation/Bubberstation/pull/2193)
- [Patches a bug with adding vetted users.](https://github.com/Bubberstation/Bubberstation/pull/2200)
- [Investigate Stat Panel as a Stutter cause](https://github.com/Bubberstation/Bubberstation/pull/2201)
- [Limbgrown bodies.](https://github.com/Bubberstation/Bubberstation/pull/1842)
- [(Port) MKUltra - Mind Control](https://github.com/Bubberstation/Bubberstation/pull/2206)
- [Persistence Base (A new offstation syndicate map) (Should be ready for test merge)](https://github.com/Bubberstation/Bubberstation/pull/2265)
- [Adds a new emote: Bonk](https://github.com/Bubberstation/Bubberstation/pull/2251)

### Reproduction Steps:

1. Set your body height of your character to 'Tallest'
2. Spawn in and look at your character
3. Their hair and ears will be cut off at the top

**Comment by Majkl-J** [comment]
Fundemental engine issue that we can't really fix. Post process filters only work within the size of your sprite and cant extend it beyond the limits
