### ISSUE TITLE
DNA Vault exclusive genes are able to be copied and distributed

### ISSUE THREAD

**Issue by xPokee** [Bubberstation/Bubberstation#2359]
### Issue Summary:

I've seen it abused a few times now but forgot to report it every time, but it's pretty clearly unintended given you're only able to choose one gene and the fact that they have the locked variable on them. They're SUPPOSED to be like x-ray where if you get it you can't save it or redistribute it.

### Reproduction Steps:

1. Build and complete a DNA vault
2. Select your mutation
3. Go to genetics and you should be able to save it to the DNA console and then redistribute it

**Comment by Mitryll** [comment]
Just to be thorough, tested this on a /tg/ localhost today and confirmed that this bug is specific to Bubber.
