### ISSUE TITLE
The detective holster can't hold .38 speed loaders

### ISSUE THREAD

**Issue by ronfino** [Bubberstation/Bubberstation#240]
![image](https://github.com/Bubberstation/Bubberstation/assets/77462428/90f2e088-ed2f-432d-84b1-fbe166a68d3d)

**Comment by Majkl-J** [comment]
![image](https://github.com/Bubberstation/Bubberstation/assets/49160555/c78bc404-91e8-4b98-9bd5-25092c025e6c)

**Comment by ronfino** [comment]
> ![image](https://user-images.githubusercontent.com/49160555/255404310-c78bc404-91e8-4b98-9bd5-25092c025e6c.png)

I guess it got fixed? I'll close it then.
