### ISSUE TITLE
Can't change the Research Node Announcement.

### ISSUE THREAD

**Issue by MothionTechnologies** [Bubberstation/Bubberstation#2424]
### Client Version:

515.1646

### Issue Summary:

When I try to change what the Research Node Announcement says in the Automated Announcement System it just revers back to the default one instead of keeping the new one. This happens on all maps as far as I know.

### Round ID:

[5961](https://scrubby.melonmesa.com/round/5961)

### Reproduction Steps:

Go to the Automated Announcement System
Attempt to change the Research Node Announcement
It will revert back to the original

**Comment by JagOfTroy** [comment]
Fixed through a bug found in the tg database code with the announcement system. PR has already been committed. 
Can close this one out as fixed.

**Comment by JagOfTroy** [comment]
https://github.com/tgstation/tgstation/pull/87928

Case closed.
