### ISSUE TITLE
Action buttons disappear when antag status is gained

### ISSUE THREAD

**Issue by ABoxFaux** [Bubberstation/Bubberstation#2433]
### Client Version:

515.1646

### Issue Summary:

Midway through a round, I rolled bloodsucker, and it removed all of my action buttons, from welding helmet/light to the PDA light. Nothing I tried fixed it - resetting the action buttons with shift/alt click, both individually and with the tab below, and relogging made it worse  - removing all of my action buttons. For bloodsucker specifically, this meant I couldn't feed, nor choose an initial clan.
When I consulted an admin, which culminated in me asking to have my antagonist status removed, as I couldn't feed, as the action button wasn't there, they gave me changeling as a test, and the same applied - no antagonist abilities or panel.
Resetting it through external means - namely through taking off the welding hard hat, breath mask, and PDA, fixed a couple of the buttons, but for antagonistic ones, losing and gaining the status did nothing.
As a side note, two other bugs happened to me, one - I was perpetually in zero-g but could move around freely, akin to a carp (slips didn't work on me,) and the icon stayed whilst the brainwashing icon disappeared. Also, something resulted in someone on-shift becoming extremely shaky and hyper and I have no idea if it's related.

https://github.com/user-attachments/assets/ff9cdcd2-b653-44d1-9bc8-ff64d8d78e11

### Round ID:

[5969](https://scrubby.melonmesa.com/round/5969)

### Reproduction Steps:

In order, I had no-gravity, rolled bloodsucker and lost all my action buttons, tested with an admin a bit, then went into a no-gravity environment, came back, and I was back to regular gravity. ~10 minutes later I tried removing and re-equipping items, and it fixed the respective action buttons (Though I still couldn't reset/center them)

**Comment by Arturlang** [comment]
Did you try to open the action button folder on the top left?

**Comment by ABoxFaux** [comment]
Yep, clicking it to open and close did nothing, and neither did resetting the location of the buttons. I could reset the buttons I could see by moving/shift/alt clicking, but for the ones I couldn't see I couldn't figure anything out.

**Comment by ABoxFaux** [comment]
It should've been 7-10 pm EST, somewhere around that time, it was a 3+ hour shift

**Comment by ABoxFaux** [comment]
After a bit of localhost testing, I figured being permanently in no-gravity is from placing (or RCDing) a floortile directly below you in open space. It fixes itself when you go to a no-grav zone and come back in (or use magboots). As for anything else, I have no idea, but I'll say I was brainwashed- that was something I forgot to mention.

**Comment by Arturlang** [comment]
Likely a issue with action buttons themselves, as bloodsucker-ism should not affect these at all unless the antag datum is removed or you level up. I've not seen this issue seen again so i'm closing, re-open if this happens again
