### ISSUE TITLE
the bloodsucker bloodmagic ability auspex

### ISSUE THREAD

**Issue by Syilumi** [Bubberstation/Bubberstation#2474]
### Client Version:

515.1646

### Issue Summary:

![image](https://github.com/user-attachments/assets/07171ba7-4324-4814-a6d0-86dcee2e4571)

unlike what the image says level 6 does not let you teleport to places you cannot fully see

### Round ID:

[2](https://scrubby.melonmesa.com/round/2)

### Reproduction Steps:

be a sucker for blood
magic clan
level hard ghoulmaxing
false advertising

**Comment by Arturlang** [comment]
Can you describe better the conditions you tried to teleport in? Do you mean trying to teleport between walls with or without mesons/xray?

**Comment by Syilumi** [comment]
well i had xray vision because of adminabuse (i was in the insane clan but they did a funny reset my clan because im indecisive) but it didnt work, tried it with mesons and that also seemed to be borked too

**Comment by Syilumi** [comment]
sorry for the late late reply im very sleepy all the time
