### ISSUE TITLE
dragon got bsa'd and green ungen'd turf was exposed

### ISSUE THREAD

**Issue by Syilumi** [Bubberstation/Bubberstation#2496]
### Client Version:

515.1646

### Issue Summary:

![image](https://github.com/user-attachments/assets/f8f1ad54-e434-4160-bdf9-d1a30c0f1ef2)

im guessing lavaland ruins when exposed to explosives made ungen turf

### Round ID:

[5](https://scrubby.melonmesa.com/round/5)

### Reproduction Steps:

BOMB THEM (the ruins and stuff)

**Comment by Syilumi** [comment]
the ruins pictured are the Lava-Ruin Fountain Hall and Lava-Ruin Biodome Winter

**Comment by Majkl-J** [comment]
ages old tg bug that nobody knows how to fix without breaking ruins in some way

**Comment by Syilumi** [comment]
oh woa
