### ISSUE TITLE
goliath can push ashwalker stone doors

### ISSUE THREAD

**Issue by Makeshift-coder** [Bubberstation/Bubberstation#2515]
### Client Version:

N/A

### Issue Summary:

the goliath can push certain anchored objects and displace them, however some things shouldn't be pushed for example the ashwalker stone gate that's meant to be super heavy ancient magic rock stuff

### Round ID:

[6030](https://scrubby.melonmesa.com/round/6030)

### Reproduction Steps:

get a goliath tamed
ride it
close the ancient gate
walk into it and it'll become your bitch

**Comment by Majkl-J** [comment]
Fix merged on TG, will arrive eventually
