### ISSUE TITLE
Plants are invisible

### ISSUE THREAD

**Issue by lessthnthree** [Bubberstation/Bubberstation#2524]
### Issue Summary:

Plants are invisible

### Round ID:

[6042](https://scrubby.melonmesa.com/round/6042)

### Reproduction Steps:

Attempt to look at plant. Fail to see plant.

**Comment by SynergyJohn** [comment]
No?
![image](https://github.com/user-attachments/assets/8136e2a7-d67d-40c1-8ff8-38680c41052f)

**Comment by lessthnthree** [comment]
![image](https://github.com/user-attachments/assets/9e6dcf80-0959-4887-888d-be25eaf9b83a)

**Comment by lessthnthree** [comment]
![image](https://github.com/user-attachments/assets/de329d8b-39e0-4d18-8efe-f6a94d66a499)

**Comment by lessthnthree** [comment]
TG bug, fixed, waiting for mirror.
