### ISSUE TITLE
Mining borgs proto-kinetic crusher clears all three modules if used on mob.

### ISSUE THREAD

**Issue by Strazyplus** [Bubberstation/Bubberstation#2629]
### Issue Summary:

When I use proto-kinetic crusher on a mob, the modules slots all clear out. 
If I use proto-kinetic crusher on structure like a window, it will allow me to hit it.

![image](https://github.com/user-attachments/assets/356dda8c-a09c-46a5-adbe-7ec92bd62caa)

### Reproduction Steps:

1. Play as a cyborg (suffer)
2. load up mining. (more suffering)
3. fill modules(items) and select proto-kinetic crusher. (basically just a flashlight at this point, suffer)
4. hit a mob with proto-kinetic crusher (cry as your modules are now empty and you will have to select/load them up again)
5. Weep.

**Comment by Majkl-J** [comment]
Use it in hand to wield it

**Comment by Strazyplus** [comment]
SIR THIS IS CYBORG, REOPEN.

**Comment by RimiNosha** [comment]
Borgs don't have hands, and therefore can't wield. This is a valid issue.

**Comment by Majkl-J** [comment]
> Borgs don't have hands, and therefore can't wield. This is a valid issue.

Try it. You can wield it just fine because wielding code actually works with borgs somehow. I literally used the crusher on a borg fine last weekend

**Comment by Strazyplus** [comment]
https://www.youtube.com/watch?v=WkVeBhPQrAo

I am in round right now.

**Comment by Majkl-J** [comment]
> infact I already knew of this bug like a week ago, I just couldnt be bothered to report it at the time.

Press Z once with the thing equipped

**Comment by RimiNosha** [comment]
I bet borgs have three hands under the hood for reasons I don't want to know

**Comment by Strazyplus** [comment]
![image](https://github.com/user-attachments/assets/c2a63657-5aa7-4915-a3b0-6749b5cb5cf0)
goddamnit.

**Comment by CloverIsLucky** [comment]
![imagen](https://github.com/user-attachments/assets/4bf0d1f9-0664-4888-8915-c5aa8e42280e)

Press Z to wield. You're welcome.
