### ISSUE TITLE
Next generation text input/privacy

### ISSUE THREAD

**Issue by Cyprex** [Bubberstation/Bubberstation#263]
This is a collection of text input options, or how text input should work, in my opinion.

Replace Subtle/Subtler with "private chat"

So essentially the way this works is that you have a way to set privacy- who can see your stuff?
There might be various options:
Only these people: 
Everyone within x tiles
Ghosts yes/no

Rather than Subtle you'd have only one option- private chat. Whatever privacy options you configured are applied to any subsequent "private chat". This function replaces the current subtle/subtler functionality.
A shorthand of the current settings could be displayed in the text input box(And maybe a collapsible element/button that opens a window/some other way to reach settings? This does sound pretty neat...)

Maybe an option to have privacy apply to regular say as well- Mayhaps a new thing- private say, that works exactly like say, but applies privacy options.

I don't know if only one set of settings and private chat prompt is the way to go- maybe having multiple sets of them, i. e. Privatechat1, privatechat2, privatechat3, all with potentially their own configurable hotkeys, and independent set of settings.
Or maybe the single chat with the ability to save and load presets quickly? Only really necessary if just changing the settings is more than 2 clicks.

**Comment by Cyprex** [comment]
this is rough and I need to put more time and thought into this. I have a concerns section planned as well

**Comment by magatsuchi** [comment]
please move to discussions
