### ISSUE TITLE
Deleting your last loadout locks you out of the loadout screen

### ISSUE THREAD

**Issue by Krypandenej** [Bubberstation/Bubberstation#2648]
### Client Version:

515.1643

### Issue Summary:

![image](https://github.com/user-attachments/assets/bc700743-f0cd-4e28-8bd4-311321f0ab25)

If you try to delete your LAST loadout on any character, attempting to access the loadout screen will result in the BSOD shown above.

### Round ID:

[6217](https://scrubby.melonmesa.com/round/6217)

### Test Merge Information:

- [[TM ONLY] Unfucking disease outbreaks/transmission](https://github.com/Bubberstation/Bubberstation/pull/1919)
- [Investigate Stat Panel as a Stutter cause](https://github.com/Bubberstation/Bubberstation/pull/2201)
- [Saddles, saddlebags, calvary](https://github.com/Bubberstation/Bubberstation/pull/2291)
- [[TM ONLY] [MDB IGNORE] Pubbystation 2](https://github.com/Bubberstation/Bubberstation/pull/2401)
- [[TM READY] New mutation - Strong legs](https://github.com/Bubberstation/Bubberstation/pull/2405)
- [Adds a new mod module - mind swap - to illegal tech](https://github.com/Bubberstation/Bubberstation/pull/2419)
- [Brings back MCR recharging, rebalances the MCR progression techweb](https://github.com/Bubberstation/Bubberstation/pull/2529)
- [[Ready for Review] Round Removal Opt-In](https://github.com/Bubberstation/Bubberstation/pull/2122)
- [Surgery speed bonus revert/refactor](https://github.com/Bubberstation/Bubberstation/pull/2569)
- [Buffs cyborg health to match human health (135)](https://github.com/Bubberstation/Bubberstation/pull/2644)
- [Fixes map vote winner selection (or: how I found 10,000 extra votes for Tramstation)](https://github.com/Bubberstation/Bubberstation/pull/2647)

### Reproduction Steps:

1. Make new character/place old char on sacrificial altar
2. In loadout manager, attempt to delete "Default"
3. Watch fireworks

**Comment by Krypandenej** [comment]
howww does one apply the bug label

**Comment by ReturnToZender** [comment]
The mental image of this moment is killing me

**Comment by Strazyplus** [comment]
Roundabout way to fix this issue!

switch character 
open loadout (should work)
switch character back while in loadout.
select item to fix glitched state

**Comment by RimiNosha** [comment]
Deleting default is physically impossible. You might be thinking of the clear all button, which I could replicate this on.
