### ISSUE TITLE
I cannot see Donator only items in the loadout menu.

### ISSUE THREAD

**Issue by MothionTechnologies** [Bubberstation/Bubberstation#2654]
### Client Version:

515.1647

### Issue Summary:

As the title says, I cannot see donator items in the loadout menu, as seen in the attached screenshots.

![Pic1](https://github.com/user-attachments/assets/ecc61bc2-71c0-4b97-af09-33feaa149e85)
![Pic2](https://github.com/user-attachments/assets/d25f1238-d484-4a33-bffb-3d9baf095438)

I have no idea what causes all this. It has been like this since the first day I joined this server.
This issue has also been happening across three different computers on multiple Byond versions.

### Round ID:

6220

### Test Merge Information:

- [[TM ONLY] Unfucking disease outbreaks/transmission](https://github.com/Bubberstation/Bubberstation/pull/1919)
- [Investigate Stat Panel as a Stutter cause](https://github.com/Bubberstation/Bubberstation/pull/2201)
- [Saddles, saddlebags, calvary](https://github.com/Bubberstation/Bubberstation/pull/2291)
- [[TM ONLY] [MDB IGNORE] Pubbystation 2](https://github.com/Bubberstation/Bubberstation/pull/2401)
- [[TM READY] New mutation - Strong legs](https://github.com/Bubberstation/Bubberstation/pull/2405)
- [Adds a new mod module - mind swap - to illegal tech](https://github.com/Bubberstation/Bubberstation/pull/2419)
- [Brings back MCR recharging, rebalances the MCR progression techweb](https://github.com/Bubberstation/Bubberstation/pull/2529)
- [[Ready for Review] Round Removal Opt-In](https://github.com/Bubberstation/Bubberstation/pull/2122)
- [Surgery speed bonus revert/refactor](https://github.com/Bubberstation/Bubberstation/pull/2569)
- [Buffs cyborg health to match human health (135)](https://github.com/Bubberstation/Bubberstation/pull/2644)

### Reproduction Steps:

I have no idea, it has been like this since the beginning. 
The issue is present on multiple computers.

**Comment by lessthnthree** [comment]
Related: https://github.com/Bubberstation/Bubberstation/issues/2604

**Comment by lessthnthree** [comment]
After joining a donator tier the in game benefit is not automatically applied, you have to ask for it presumably in the donors discord channel or something.
