### ISSUE TITLE
ai core can be shoved by running into it

### ISSUE THREAD

**Issue by Syilumi** [Bubberstation/Bubberstation#2659]
### Client Version:

515.1647

### Issue Summary:

it seems like the ai bolts only stop people from pulling it.. not.. moving it by running into it

### Reproduction Steps:

walk upto ai
push past them by running
somehow you moved a solid cube of plastanium bolted to the floor by just being in a hurry

**Comment by Majkl-J** [comment]
Open this up on tg

**Comment by Syilumi** [comment]
eh someone else will find this bug
