### ISSUE TITLE
Moth antennae cannot be hidden by any means

### ISSUE THREAD

**Issue by Krypandenej** [Bubberstation/Bubberstation#2665]
### Client Version:

515.1643

### Issue Summary:

See above. Even with the ability to hide mutant parts, the moth antennae (at least White Fly variety) cannot be hidden via verbs or outfits.

### Round ID:

6245

### Test Merge Information:

- [[TM ONLY] Unfucking disease outbreaks/transmission](https://github.com/Bubberstation/Bubberstation/pull/1919)
- [Investigate Stat Panel as a Stutter cause](https://github.com/Bubberstation/Bubberstation/pull/2201)
- [Saddles, saddlebags, calvary](https://github.com/Bubberstation/Bubberstation/pull/2291)
- [[TM READY] New mutation - Strong legs](https://github.com/Bubberstation/Bubberstation/pull/2405)
- [Adds a new mod module - mind swap - to illegal tech](https://github.com/Bubberstation/Bubberstation/pull/2419)
- [[Ready for Review] Round Removal Opt-In](https://github.com/Bubberstation/Bubberstation/pull/2122)
- [Surgery speed bonus revert/refactor](https://github.com/Bubberstation/Bubberstation/pull/2569)

### Reproduction Steps:

1. Make new moth char
2. Assign antennae
3. Attempt to hide antennae with hide mutant parts verb

**Comment by Majkl-J** [comment]
Moved to #2790
