### ISSUE TITLE
Miniskirt covers your breasts

### ISSUE THREAD

**Issue by lessthnthree** [Bubberstation/Bubberstation#2672]
### Issue Summary:

The miniskirt, which is just that, a skirt with no shirt, counts as a chest covering and hides your breasts with the default 'hidden by clothes' setting

### Reproduction Steps:

Have breasts
Put on solely a miniskirt
Watch your breasts vanish

**Comment by Majkl-J** [comment]
Breast reduction surgeons hate her! See how this demihuman removes her breasts. Learn this one weird trick for stunning results!

**Comment by Drayco84** [comment]
Can be observed in the loadout screen and happens with both variants of miniskirt, the recolorable one and the security variant.
Checked other leg-only options and didn't find any others with this effect.
