### ISSUE TITLE
Cook still shows up as unknown department on crew monitor

### ISSUE THREAD

**Issue by lessthnthree** [Bubberstation/Bubberstation#2673]
### Issue Summary:

Cook still shows up as orange (unknown department) on the crew health monitor.

### Reproduction Steps:

Look at crew monitor.

**Comment by JagOfTroy** [comment]
![Screenshot 2024-12-14 012805](https://github.com/user-attachments/assets/2866148e-621a-41fc-9ffd-9a7cdb515b79)
Replicated.
Looking into it... might have something to do with the crew.dm thinking the chef is undefined so its using the auto-default to orange instead of 'service'

**Comment by JagOfTroy** [comment]
![Screenshot 2024-12-14 013320](https://github.com/user-attachments/assets/ebd2809e-25fe-4f3e-a6be-03ad32da4a87)
Gonna check TGMaster and see if the problem still persists.

**Comment by JagOfTroy** [comment]
![Screenshot 2024-12-14 014357](https://github.com/user-attachments/assets/a99fbc2b-d217-480e-9e06-f26178893c12)
Works fine on TGmaster.
