### ISSUE TITLE
death degradation seems a bit funked

### ISSUE THREAD

**Issue by Syilumi** [Bubberstation/Bubberstation#2690]
### Client Version:

515.1647

### Issue Summary:

I had my stamina degradation as 
![image](https://github.com/user-attachments/assets/c0f52c6b-3193-4681-b86b-9704545c8905)
and yet as soon as it hit 1 degradation i had max stamina damage and kept collapsing
i tried it with the end being at 0 but that just disabled the whole stamina reduction

### Reproduction Steps:

get DDD
mess around with the settings
crippled

**Comment by Syilumi** [comment]
i misread..

**Comment by nikothedude** [comment]
actually a valid bug, fixed by https://github.com/Bubberstation/Bubberstation/pull/2976

**Comment by Syilumi** [comment]
> actually a valid bug, fixed by [#2976](https://github.com/Bubberstation/Bubberstation/pull/2976)

OH welp time to use DDD again!! thanks for tellin me
