### ISSUE TITLE
Voidraptor Janitor spawns in area they don't have access to.

### ISSUE THREAD

**Issue by Cyprex** [Bubberstation/Bubberstation#27]
## Round ID: 278

Janitor spawned in an area they can't get out of without help, Emergency EVA in Escape. Map is voidraptor

## Testmerges:

Server revision compiled on: 2023-02-07T15:15:39+00:00
Master commit: [a4ccb89f1e6509bbfeb3a5fe1acd8cce763b5c1f](https://github.com/Bubberstation/Bubberstation/commit/a4ccb89f1e6509bbfeb3a5fe1acd8cce763b5c1f)
The following pull requests are currently test merged:
[#10: 'Dynamic tweaks' by Cyprex at commit 764bc505d3](https://github.com/Bubberstation/Bubberstation/pull/10)
[#13: 'Blacksmithing!' by Gr33d-y at commit b4a31c9442](https://github.com/Bubberstation/Bubberstation/pull/13)

Local commit: 616b79235bb76ef9f88324867141892fcd6b54cc

![](https://i.imgur.com/wlwjxMp.png)

**Comment by magatsuchi** [comment]
![image](https://github.com/Bubberstation/Bubberstation/assets/88991542/fe15694f-787e-4e6a-9eca-da1c86f60e85)

(please post this issue to either Skyrat-SS13/Skyrat-tg or tgstation/tgstation)
