### ISSUE TITLE
research borg modules are fucked

### ISSUE THREAD

**Issue by Krypandenej** [Bubberstation/Bubberstation#2704]
### Client Version:

515.1643

### Issue Summary:

-The borg cannot grasp mech control modules with the research manip
-The borg cannot use it's inducer, as the inducer starts empty. Likely broken with cell/Megacell updates.
-The borg cannot grab mech chassis parts with research manip

### Round ID:

6300

### Test Merge Information:

- [[TM ONLY] Unfucking disease outbreaks/transmission](https://github.com/Bubberstation/Bubberstation/pull/1919)
- [Investigate Stat Panel as a Stutter cause](https://github.com/Bubberstation/Bubberstation/pull/2201)
- [Saddles, saddlebags, calvary](https://github.com/Bubberstation/Bubberstation/pull/2291)
- [[Review ready] New mutation - Strong legs](https://github.com/Bubberstation/Bubberstation/pull/2405)
- [[Ready for Review] Round Removal Opt-In](https://github.com/Bubberstation/Bubberstation/pull/2122)
- [Surgery speed bonus revert/refactor](https://github.com/Bubberstation/Bubberstation/pull/2569)

### Reproduction Steps:

1. Attempt to use items as described with context
2. Sob

**Comment by Majkl-J** [comment]
Seeing as the one issue that is unintentional was fixed upstream, (That being the inducers) closing.
