### ISSUE TITLE
Cortically Augmented Brain "Augment" is unusable on ghost roles.

### ISSUE THREAD

**Issue by MrGloopy** [Bubberstation/Bubberstation#2724]
### Client Version:

515.1647

### Issue Summary:

Equipping the Cortically Augmented Brain in Character Settings, under Augments, attempting to spawn in as a ghost role will instantly ash your character, whether a Synthetic Humanoid or Organic (IE, any other race).

### Round ID:

6317

### Test Merge Information:

- [[TM ONLY] Unfucking disease outbreaks/transmission](https://github.com/Bubberstation/Bubberstation/pull/1919)
- [Investigate Stat Panel as a Stutter cause](https://github.com/Bubberstation/Bubberstation/pull/2201)
- [Saddles, saddlebags, calvary](https://github.com/Bubberstation/Bubberstation/pull/2291)
- [[Review ready] New mutation - Strong legs](https://github.com/Bubberstation/Bubberstation/pull/2405)
- [[Ready for Review] Round Removal Opt-In](https://github.com/Bubberstation/Bubberstation/pull/2122)
- [Surgery speed bonus revert/refactor](https://github.com/Bubberstation/Bubberstation/pull/2569)
- [[TM ready, again] brain augment fluff](https://github.com/Bubberstation/Bubberstation/pull/2497)
- [Nebulastation ERT/aux docks](https://github.com/Bubberstation/Bubberstation/pull/2716)
- [Makes the xmas period longer](https://github.com/Bubberstation/Bubberstation/pull/2722)

### Reproduction Steps:

1. Equip the "Cortically-Augmented Brain" in the Augments+ category in character preferences.
2. Attempt to spawn in as a ghost role. I attempted to spawn in at the ghost cafe for testing purposes. I tested both Mothman and Synthetic Humanoid races, with the same results.
3. Character will instantly be ashed, displaying the following message. Image attached below:

![image](https://github.com/user-attachments/assets/e9fdf801-4f1a-4523-8064-715f89f2bdb3)

4. Ghost character will be immediately teleported to a random tile on the arrivals shuttle.
5. Ghost character will be a random Human name and not the currently selected character, as it normally would be. Loadout items are not spawned, in-hand suitcase is not spawned. Preferences are not even fully applied before the ashing happens, it seems.

**Comment by Majkl-J** [comment]
Marking as resolved
