### ISSUE TITLE
Moth antennae do not hide under hats or when hidden with mutant parts option

### ISSUE THREAD

**Issue by MrGloopy** [Bubberstation/Bubberstation#2739]
### Client Version:

515.1647

### Issue Summary:

Moth antennae do not hide under hats or when hidden with mutant parts option

### Round ID:

6335

### Test Merge Information:

- [[TM ONLY] Unfucking disease outbreaks/transmission](https://github.com/Bubberstation/Bubberstation/pull/1919)
- [Investigate Stat Panel as a Stutter cause](https://github.com/Bubberstation/Bubberstation/pull/2201)
- [[Review ready] New mutation - Strong legs](https://github.com/Bubberstation/Bubberstation/pull/2405)
- [[Ready for Review] Round Removal Opt-In](https://github.com/Bubberstation/Bubberstation/pull/2122)
- [Surgery speed bonus revert/refactor](https://github.com/Bubberstation/Bubberstation/pull/2569)
- [[TM ready, again] brain augment fluff](https://github.com/Bubberstation/Bubberstation/pull/2497)
- [Revert "Makes the christmas tree safe" (Please use broken gear responsibly)](https://github.com/Bubberstation/Bubberstation/pull/2723)
- [Flechett ammo rebalance.](https://github.com/Bubberstation/Bubberstation/pull/2729)

### Reproduction Steps:

Enable moth antennae in character creator.
Wear a large hat that would normally cover the antennae or enable the "Hide mutant parts" option and select antennae.
Antennae will not hide underneath the hat/hood or when toggled with mutant parts.

**Comment by Majkl-J** [comment]
Moved to #2790
