### ISSUE TITLE
Draft of Bubberstation auth scheme

### ISSUE THREAD

**Issue by Cyprex** [Bubberstation/Bubberstation#286]
Here's how I envision whitelisting/Panic Bunker Bypass should work:

There's a Discord bot component, presumably a redbot cog, and DM code accompanying it. The DB is used as a central datastore for both.

There's a Discord linking feature, which works by giving users a unique per-user token and having them enter it in discord. Example:

"To play on Bubberstation you need to link a Discord account. To do so enter `/discordlink clock-teak-weasel-birch` in any channel."

The token is generated and stored in the DB(or possibly elsewhere), along with the ckey the code belongs to. When `/discordlink` is received by the Discord bot it looks up the code and (if valid) associates the ckey with that Discord User (ID).

Rather than use the current panic bunker terminology I will describe ckeys as "locked" if they haven't gone through the process of getting whitelisted yet. Note that crew role membership is what signifies it on Discord. In contrast a ckey being locked is an in-game status applied to a ckey.
When a user that hasn't yet bypassed the panic bunker joins they are told they need to link Discord(if no link exists yet) & that they need to whitelist. If a link exists the DM code automatically checks if the person is whitelisted on Discord, and if so allows them entry. This could be implemented in various ways, For example the Discord bot could be queried on a users role membership when a locked ckey joins(and unlock them). This seems like the best way.  
Update: Actually there is no need to involve non-DM code in this-we can simply have a second Discord bot in DM Code. SSDiscord already exists and should handle most of the nitty-gritty of dealing with Discord's API already.

Alternatively a Discord bot could poll role membership/whitelist application status. The problem here is that discord api rate limits might slow this approach down. Requiring users to wait 30 minutes for their whitelist status to propagate in-game is undesirable.

This mostly replaces the current system where admins manually add ckeys to the panic bunker.

TODO: Look into tg's implementation of discord linking.

**Comment by magatsuchi** [comment]
please move to discussions
