### ISSUE TITLE
Add gunpointing and pointing as bindable commands.

### ISSUE THREAD

**Issue by ronfino** [Bubberstation/Bubberstation#31]
Make gunpointing and pointing a bindable command. Unluckily, my middle mouse button doesn't work when pressed. It's a bit frustrating being limited in certain actions because of this.

**Comment by mcmeiler** [comment]
You can point at someone through the context menu, already.

**Comment by ronfino** [comment]
> You can point at someone through the context menu, already.

I know, but that's incredibly _not_ convenient and slow during frantic situations, especially if i'm playing while readminning which increases the amount of options in the context menu. That's why having it as a bindable command would be great, same thing for gunpointing, except that it's worse since i sometimes shoot by accident people and cause escalations.

![image](https://user-images.githubusercontent.com/77462428/226177330-20376825-2922-4fe4-8eac-e5559ccb2598.png)

**Comment by Majkl-J** [comment]
> I know, but that's incredibly _not_ convenient and slow during frantic situations, especially if i'm playing while readminning which increases the amount of options in the context menu. That's why having it as a bindable command would be great, same thing for gunpointing, except that it's worse since i sometimes shoot by accident people and cause escalations.
> 
> ![image](https://user-images.githubusercontent.com/77462428/226177330-20376825-2922-4fe4-8eac-e5559ccb2598.png)

Shift middleclick

**Comment by ronfino** [comment]
> Shift middleclick

My MMB doesn't work like i said initially

**Comment by Majkl-J** [comment]
> > Shift middleclick
> 
> My MMB doesn't work like i said initially

valid, I'll try adding it to prefs... somehow

**Comment by ronfino** [comment]
> valid, I'll try adding it to prefs... somehow

I would very much appreciate that.

**Comment by magatsuchi** [comment]
![image](https://github.com/Bubberstation/Bubberstation/assets/88991542/41fdb4f6-7019-4630-8d7d-0a2a4247c492)

**Comment by ronfino** [comment]
I got a new mouse, i don't care anymore lol.
