### ISSUE TITLE
Hydra head neutral trait always randomizes identity

### ISSUE THREAD

**Issue by Colfer1** [Bubberstation/Bubberstation#322]
## Round ID:
1646

## Testmerges:
[#208: 'Test revert of #190 to try and solve the error-people.' by KathrinBailey at commit 9d786b9510](https://github.com/Bubberstation/Bubberstation/pull/208)
[#282: '[MODULAR] Adds a hud to being a cortical borer.' by nevimer at commit a4201d2928](https://github.com/Bubberstation/Bubberstation/pull/282)
[#294: 'Blacksmithing workshops' by Scuhf-git at commit 283baa27e6](https://github.com/Bubberstation/Bubberstation/pull/294)
[#248: 'Reset the Gateway to TGstation, allowing cyborgs to enter' by nevimer at commit e499e44135](https://github.com/Bubberstation/Bubberstation/pull/248)
[#306: 'Ports GAS' by nevimer at commit 41f7d18ef3](https://github.com/Bubberstation/Bubberstation/pull/306)
[#305: 'Ports Lima Station from TaleStation' by INKVD at commit d13af4c06a](https://github.com/Bubberstation/Bubberstation/pull/305)
[#272: 'Adds nearly every item to the game into maintenance.' by BurgerLUA at commit 3bfc1c4699](https://github.com/Bubberstation/Bubberstation/pull/272)
[#313: '[NON-MODULAR] Jetpack Fix' by Higgin at commit 92285db044](https://github.com/Bubberstation/Bubberstation/pull/313)
[#312: '(NON-MODULAR) Salt PR' by Kilmented at commit 512572a40d](https://github.com/Bubberstation/Bubberstation/pull/312)
[#318: '[NONMODULAR] Biodome Un-Soulening' by TripleShades at commit 01ded50b9b](https://github.com/Bubberstation/Bubberstation/pull/318)
[#319: '[NON-MODULAR] Buffs Burn Wounds' by Higgin at commit 5b53e86277](https://github.com/Bubberstation/Bubberstation/pull/319)
[#241: '[MODULAR] Progtot goals override' by nevimer at commit a234c045e1](https://github.com/Bubberstation/Bubberstation/pull/241)
[#309: '[Modular] Moves Crewsimov, adds Crew Overlord' by ReturnToZender at commit 05f5cd254a](https://github.com/Bubberstation/Bubberstation/pull/309)
[#310: '[Semi-Modular] Makes asset protection compatible with digi and better vox' by ReturnToZender at commit 1fb587bcb6](https://github.com/Bubberstation/Bubberstation/pull/310)
[#314: '[Modular] Makes all techwebs generate points' by ReturnToZender at commit 8a41be5ab2](https://github.com/Bubberstation/Bubberstation/pull/314)
[#315: '[Fixes Modularity] Removes ballistic weapons from command, gives proper eguns' by ReturnToZender at commit b45fee125a](https://github.com/Bubberstation/Bubberstation/pull/315)

## Reproduction:
Select hydra head, Name it literally anything, try to use the verbs you get, your identity has been permanently altered. Even using the EXAMPLE GIVEN in the trait (Rucks-Sucks-Ducks) doesnt work correctly, and will seemingly always reset your name to some random human name

**Comment by magatsuchi** [comment]
skyrat-tg issue please post there
