### ISSUE TITLE
Replica pods in lavaland produce living humans

### ISSUE THREAD

**Issue by Colfer1** [Bubberstation/Bubberstation#326]
Reporting client version: 514.1589

## Round ID:
1668

## Testmerges:
- [Test revert of #190 to try and solve the error-people.](https://github.com/Bubberstation/Bubberstation/pull/208)
- [[MODULAR] Adds a hud to being a cortical borer.](https://github.com/Bubberstation/Bubberstation/pull/282)
- [Blacksmithing workshops](https://github.com/Bubberstation/Bubberstation/pull/294)
- [Reset the Gateway to TGstation, allowing cyborgs to enter](https://github.com/Bubberstation/Bubberstation/pull/248)
- [Ports GAS](https://github.com/Bubberstation/Bubberstation/pull/306)
- [Ports Lima Station from TaleStation](https://github.com/Bubberstation/Bubberstation/pull/305)
- [Adds nearly every item to the game into maintenance.](https://github.com/Bubberstation/Bubberstation/pull/272)
- [[NON-MODULAR] Jetpack Fix](https://github.com/Bubberstation/Bubberstation/pull/313)
- [(NON-MODULAR) Salt PR](https://github.com/Bubberstation/Bubberstation/pull/312)
- [[MODULAR] Biodome Un-Soulening](https://github.com/Bubberstation/Bubberstation/pull/318)
- [[NON-MODULAR] Buffs Burn Wounds](https://github.com/Bubberstation/Bubberstation/pull/319)
- [[MODULAR] Progtot goals override](https://github.com/Bubberstation/Bubberstation/pull/241)
- [[Modular] Moves Crewsimov, adds Crew Overlord](https://github.com/Bubberstation/Bubberstation/pull/309)
- [[Semi-Modular] Makes asset protection compatible with digi and better vox](https://github.com/Bubberstation/Bubberstation/pull/310)
- [[Modular] Makes all techwebs generate points](https://github.com/Bubberstation/Bubberstation/pull/314)
- [[Fixes Modularity] Removes ballistic weapons from command, gives proper eguns](https://github.com/Bubberstation/Bubberstation/pull/315)

## Reproduction:
Plant replica pods (pod people thing) into the soil on lavaland, the plant will transform into an object that produces the plant product periodically, but the plant product for replica pods is people, the replica pods normally disappear if theres no blood in them and leave behind seeds, but replica pods planted in lavaland soil produce random humans

**Comment by DerFlammenwerfer** [comment]
Is this specific to lavaland soil?

**Comment by Colfer1** [comment]
Yes, It works as intended when in hydroponics. I don't think any soil other than lavaland "Soil" (The turf) does this behavior

**Comment by Majkl-J** [comment]
Fixed (Unintentionally) with https://github.com/Skyrat-SS13/Skyrat-tg/pull/23954
