### ISSUE TITLE
Brain type does not affect cyborg deconstruction 

### ISSUE THREAD

**Issue by Sweettoothart** [Bubberstation/Bubberstation#354]
Reporting client version: 514.1589

## Round ID: 
1731

## Testmerges:
- [Test revert of #190 to try and solve the error-people.](https://github.com/Bubberstation/Bubberstation/pull/208)
- [[MODULAR] Adds a hud to being a cortical borer.](https://github.com/Bubberstation/Bubberstation/pull/282)
- [Blacksmithing workshops](https://github.com/Bubberstation/Bubberstation/pull/294)
- [Reset the Gateway to TGstation, allowing cyborgs to enter](https://github.com/Bubberstation/Bubberstation/pull/248)
- [Ports GAS](https://github.com/Bubberstation/Bubberstation/pull/306)
- [Ports Lima Station from TaleStation](https://github.com/Bubberstation/Bubberstation/pull/305)
- [Adds nearly every item to the game into maintenance.](https://github.com/Bubberstation/Bubberstation/pull/272)
- [[NON-MODULAR] Jetpack Fix](https://github.com/Bubberstation/Bubberstation/pull/313)
- [(NON-MODULAR) Salt PR](https://github.com/Bubberstation/Bubberstation/pull/312)
- [[MODULAR] Biodome Un-Soulening](https://github.com/Bubberstation/Bubberstation/pull/318)
- [[NON-MODULAR] Buffs Burn Wounds](https://github.com/Bubberstation/Bubberstation/pull/319)
- [[MODULAR] Progtot goals override](https://github.com/Bubberstation/Bubberstation/pull/241)
- [[Modular] Moves Crewsimov, adds Crew Overlord](https://github.com/Bubberstation/Bubberstation/pull/309)
- [[Semi-Modular] Makes asset protection compatible with digi and better vox](https://github.com/Bubberstation/Bubberstation/pull/310)
- [[Modular] Makes all techwebs generate points](https://github.com/Bubberstation/Bubberstation/pull/314)
- [[Fixes Modularity] Removes ballistic weapons from command, gives proper eguns](https://github.com/Bubberstation/Bubberstation/pull/315)

## Reproduction:
Have Silicon and Synthetic Brain Type be a positronic brain, be deconstructed, show up as an MMI. Clearly somethings fucking up.

**Comment by magatsuchi** [comment]
upstream issue
