### ISSUE TITLE
Biodome tram issues

### ISSUE THREAD

**Issue by Cyprex** [Bubberstation/Bubberstation#355]
## Round ID: 1732

The tram call button on the bottommost station doesn't work. The display on the tram doesn't display correctly either, likely due to missing icon_state's
https://i.imgur.com/Vt5avmD.png
The tram on this map honestly feels a bit forced- the boat is quite cute but it doesn't really connect all that much. The middle station only leads to a maintenance tunnel.
## Testmerges:
Round ID: 1732
BYOND Version: 514.1589
Server revision compiled on: 2023-07-11T22:12:09+00:00
Master commit: [c76bc9f114cc343ab1556774de99ef66390d2cee](https://github.com/Bubberstation/Bubberstation/commit/c76bc9f114cc343ab1556774de99ef66390d2cee)
The following pull requests are currently test merged:
[#208: 'Test revert of #190 to try and solve the error-people.' by KathrinBailey at commit 9d786b9510](https://github.com/Bubberstation/Bubberstation/pull/208)
[#282: '[MODULAR] Adds a hud to being a cortical borer.' by nevimer at commit a4201d2928](https://github.com/Bubberstation/Bubberstation/pull/282)
[#294: 'Blacksmithing workshops' by Scuhf-git at commit c706d49aaf](https://github.com/Bubberstation/Bubberstation/pull/294)
[#248: 'Reset the Gateway to TGstation, allowing cyborgs to enter' by nevimer at commit e499e44135](https://github.com/Bubberstation/Bubberstation/pull/248)
[#306: 'Ports GAS' by nevimer at commit 41f7d18ef3](https://github.com/Bubberstation/Bubberstation/pull/306)
[#305: 'Ports Lima Station from TaleStation' by INKVD at commit d13af4c06a](https://github.com/Bubberstation/Bubberstation/pull/305)
[#272: 'Adds nearly every item to the game into maintenance.' by BurgerLUA at commit 3bfc1c4699](https://github.com/Bubberstation/Bubberstation/pull/272)
[#313: '[NON-MODULAR] Jetpack Fix' by Higgin at commit 92285db044](https://github.com/Bubberstation/Bubberstation/pull/313)
[#312: '(NON-MODULAR) Salt PR' by Kilmented at commit 512572a40d](https://github.com/Bubberstation/Bubberstation/pull/312)
[#318: '[MODULAR] Biodome Un-Soulening' by TripleShades at commit ff767aafcd](https://github.com/Bubberstation/Bubberstation/pull/318)
[#319: '[NON-MODULAR] Buffs Burn Wounds' by Higgin at commit 5b53e86277](https://github.com/Bubberstation/Bubberstation/pull/319)
[#241: '[MODULAR] Progtot goals override' by nevimer at commit a234c045e1](https://github.com/Bubberstation/Bubberstation/pull/241)
[#309: '[Modular] Moves Crewsimov, adds Crew Overlord' by ReturnToZender at commit 05f5cd254a](https://github.com/Bubberstation/Bubberstation/pull/309)
[#310: '[Semi-Modular] Makes asset protection compatible with digi and better vox' by ReturnToZender at commit 1fb587bcb6](https://github.com/Bubberstation/Bubberstation/pull/310)
[#314: '[Modular] Makes all techwebs generate points' by ReturnToZender at commit 8a41be5ab2](https://github.com/Bubberstation/Bubberstation/pull/314)
[#315: '[Fixes Modularity] Removes ballistic weapons from command, gives proper eguns' by ReturnToZender at commit b45fee125a](https://github.com/Bubberstation/Bubberstation/pull/315)

**Comment by TripleShades** [comment]
Latest push to this pr fixes the button, thanks for finding this.
I forgot to write AFT when unifying variables.
Someone else is working on the display state being wrong.

**Comment by magatsuchi** [comment]
closed by #370

**Comment by magatsuchi** [comment]
woops teehee
