### ISSUE TITLE
AI Buttons are visually locked to the top of the screen, however can still be "hovered over" and interacted with like they're at the bottom of the screen.

### ISSUE THREAD

**Issue by BurgerLUA** [Bubberstation/Bubberstation#372]
![image](https://github.com/Bubberstation/Bubberstation/assets/8602857/6c23fe37-4ac1-44a8-a33d-3a69d6f777d3)

## Testmerges:

[#208: 'Test revert of #190 to try and solve the error-people.' by KathrinBailey at commit 9d786b9510](https://github.com/Bubberstation/Bubberstation/pull/208)
[#294: 'Blacksmithing workshops' by Scuhf-git at commit 5ec8cdaf73](https://github.com/Bubberstation/Bubberstation/pull/294)
[#248: 'Reset the Gateway to TGstation, allowing cyborgs to enter' by nevimer at commit e499e44135](https://github.com/Bubberstation/Bubberstation/pull/248)
[#241: '[MODULAR] Progtot goals override' by nevimer at commit a234c045e1](https://github.com/Bubberstation/Bubberstation/pull/241)
[#314: '[Modular] Makes all techwebs generate points' by ReturnToZender at commit 8a41be5ab2](https://github.com/Bubberstation/Bubberstation/pull/314)
[#365: 'Chirp Donor Plushie' by Icarus-The-Sun at commit ccb50a98d1](https://github.com/Bubberstation/Bubberstation/pull/365)
[#367: 'Revert antag removal v2' by nevimer at commit 4a0dc791aa](https://github.com/Bubberstation/Bubberstation/pull/367)
[#272: 'Adds nearly every item to the game into maintenance.' by BurgerLUA at commit a03a6bb2cc](https://github.com/Bubberstation/Bubberstation/pull/272)
[#368: '.burningcold's donator items' by Icarus-The-Sun at commit 56aa270f83](https://github.com/Bubberstation/Bubberstation/pull/368)
[#369: 'Revert the Lizard Screams' by nevimer at commit 16ce74920b](https://github.com/Bubberstation/Bubberstation/pull/369)

## Reproduction:

Join as AI.
Get this issue regardless of widescreen settings.
Currently running 515.1609

**Comment by nevimer** [comment]
> 
![dreamseeker_6p3fFAw0Ln](https://github.com/Bubberstation/Bubberstation/assets/77420409/26e98cfc-ce9f-49d9-ae2c-e4343b6e2579)
514.1589

**Comment by magatsuchi** [comment]
banished to the land of issue closed because i also cannot get this to replicate

please recomment if you can get it to reproduce again
