### ISSUE TITLE
Vox don't spawn with Nitrogen when spawning as a midround antagonist.

### ISSUE THREAD

**Issue by INKVD** [Bubberstation/Bubberstation#373]
## Round ID:
N/A

## Testmerges:
N/A

## Reproduction:

Create a Vox Primalis character.
Spawn as from-ghost midround antagonist like Contractor / Lone Infiltrator.
Proceed to die due to spawning with an Oxygen tank instead of Nitrogen.

**Comment by magatsuchi** [comment]
skyrat issue please post upstream
