### ISSUE TITLE
Laying down in Pools or deep enough water causes you to always have a Negative moodlet.

### ISSUE THREAD

**Issue by ShamanSliph** [Bubberstation/Bubberstation#388]
## Testmerges:
#208
[Test revert of #190 to try and solve the error-people.](https://github.com/Bubberstation/Bubberstation/pull/208) by [@KathrinBailey](https://github.com/KathrinBailey)
Commit: [9d786b9](https://github.com/bubberstation/Bubberstation/commit/9d786b9510b97506c587afa2310aa12c5ffb33b8)
#294
[Blacksmithing workshops](https://github.com/Bubberstation/Bubberstation/pull/294) by [@Scuhf-git](https://github.com/Scuhf-git)
Commit: [5ec8cda](https://github.com/bubberstation/Bubberstation/commit/5ec8cdaf73afe28edd182ed8da64dda2ec237532)
#248
[Reset the Gateway to TGstation, allowing cyborgs to enter](https://github.com/Bubberstation/Bubberstation/pull/248) by [@nevimer](https://github.com/nevimer)
Commit: [e499e44](https://github.com/bubberstation/Bubberstation/commit/e499e441353f09c2b5eec078a2cee6ddd7aa6d4f)
#241
[[MODULAR] Progtot goals override](https://github.com/Bubberstation/Bubberstation/pull/241) by [@nevimer](https://github.com/nevimer)
Commit: [a234c04](https://github.com/bubberstation/Bubberstation/commit/a234c045e1b3c233c2d2c0cd5a72b335107e02c6)
#314
[[Modular] Makes all techwebs generate points](https://github.com/Bubberstation/Bubberstation/pull/314) by [@ReturnToZender](https://github.com/ReturnToZender)
Commit: [8a41be5](https://github.com/bubberstation/Bubberstation/commit/8a41be5ab28a8d5d639ae93a7f48e2a5f3eb629f)
#367
[Revert antag removal v2](https://github.com/Bubberstation/Bubberstation/pull/367) by [@nevimer](https://github.com/nevimer)
Commit: [4a0dc79](https://github.com/bubberstation/Bubberstation/commit/4a0dc791aaea14742b5a5e431889d5fb9464cf5a)
#272
[Adds nearly every item to the game into maintenance.](https://github.com/Bubberstation/Bubberstation/pull/272) by [@BurgerLUA](https://github.com/BurgerLUA)
Commit: [a03a6bb](https://github.com/bubberstation/Bubberstation/commit/a03a6bb2ccd00fae8a29df1e9abb48db9a314e82)
#368
[.burningcold's donator items](https://github.com/Bubberstation/Bubberstation/pull/368) by [@Icarus-The-Sun](https://github.com/Icarus-The-Sun)
Commit: [56aa270](https://github.com/bubberstation/Bubberstation/commit/56aa270f83f70401275250c6ce7c817650bb5721)
#369
[Revert the Lizard Screams](https://github.com/Bubberstation/Bubberstation/pull/369) by [@nevimer](https://github.com/nevimer)
Commit: [16ce749](https://github.com/bubberstation/Bubberstation/commit/16ce74920b726234da18789de75b276b07b47b37)
#371
[Post-upstream fix for PR 344](https://github.com/Bubberstation/Bubberstation/pull/371) by [@DerFlammenwerfer](https://github.com/DerFlammenwerfer)
Commit: [b7ba34e](https://github.com/bubberstation/Bubberstation/commit/b7ba34e9a0c274ebd2bf2da02f8d2dbfa684363f)
#370
[Biodome Tweaks](https://github.com/Bubberstation/Bubberstation/pull/370) by [@TripleShades](https://github.com/TripleShades)
Commit: [c4c852b](https://github.com/bubberstation/Bubberstation/commit/c4c852bb691c5afa413e05ebee592e90887dcc8b)
#306
[Ports GAS](https://github.com/Bubberstation/Bubberstation/pull/306) by [@nevimer](https://github.com/nevimer)
Commit: [6a8dcd4](https://github.com/bubberstation/Bubberstation/commit/6a8dcd414d14014dfc28dd53a21557e7aa1b9a78)
#382
[fixes oversized synths/species with nohunger getting huge guts](https://github.com/Bubberstation/Bubberstation/pull/382) by [@Kraseo](https://github.com/Kraseo)
Commit: [1ec9089](https://github.com/bubberstation/Bubberstation/commit/1ec9089104e5b28179ea8b3e7fb42a332def5ba8)

## Reproduction:
Step 1: Find a pool, or any standing water that is deep enough that laying down will cause your character to start drowning. Best place to test would be Void Raptor's Perma or Void Raptor's Dorms pool.
Step 2: Lay down and check your current mood, once you have  "CAN'T....BREATHE...." stand back up.
Step: 3: Once you are standing back up, check your mood, the suffocation moodlet should still be active, leave the water completely and wait around, that moodlet should never go away until another source of suffocation is entered and exited..

For some reason laying down in deep water will  cause the 'CAN'T.....BREATHE..." moodlet to remain stuck to the character and will not come off until you trigger another form of suffocation. So entering a room with no air and leaving will cause you to lose the moodlet.

**Comment by magatsuchi** [comment]
![image](https://github.com/Bubberstation/Bubberstation/assets/88991542/fe15694f-787e-4e6a-9eca-da1c86f60e85)

(please post this issue to either Skyrat-SS13/Skyrat-tg or tgstation/tgstation)
