### ISSUE TITLE
Typing indicator for Anti-Ghost Subtle.

### ISSUE THREAD

**Issue by ronfino** [Bubberstation/Bubberstation#39]
Copy-pasting this suggestion from the discord because i'm bored, also Butters told me to post it here.

Add a typing indicator when emoting in anti-ghost. People have frequently asked me in LOOC if i was actually typing because all they could see is my character being completely still.

It'd be nice to keep the box (check pic) rather than a bar, so i can fully see what i am going to send.
![image](https://user-images.githubusercontent.com/77462428/218336535-9b76f8d7-2a58-4c8d-ac5e-6a9d7184b04e.png)

**Comment by mcmeiler** [comment]
There's a bandaid fix, you can open a chat window while having this one open. I _might_ look into this, though.

**Comment by magatsuchi** [comment]
stale suggestion
