### ISSUE TITLE
You can PDA cafe cyborgs on station

### ISSUE THREAD

**Issue by Sweettoothart** [Bubberstation/Bubberstation#390]
Reporting client version: 514.1589

## Round ID:
1798

## Testmerges:
- [Test revert of #190 to try and solve the error-people.](https://github.com/Bubberstation/Bubberstation/pull/208)
- [Blacksmithing workshops](https://github.com/Bubberstation/Bubberstation/pull/294)
- [Reset the Gateway to TGstation, allowing cyborgs to enter](https://github.com/Bubberstation/Bubberstation/pull/248)
- [[MODULAR] Progtot goals override](https://github.com/Bubberstation/Bubberstation/pull/241)
- [[Modular] Makes all techwebs generate points](https://github.com/Bubberstation/Bubberstation/pull/314)
- [Revert antag removal v2](https://github.com/Bubberstation/Bubberstation/pull/367)
- [Adds nearly every item to the game into maintenance.](https://github.com/Bubberstation/Bubberstation/pull/272)
- [Revert the Lizard Screams](https://github.com/Bubberstation/Bubberstation/pull/369)
- [Post-upstream fix for PR 344](https://github.com/Bubberstation/Bubberstation/pull/371)
- [Biodome Tweaks](https://github.com/Bubberstation/Bubberstation/pull/370)
- [Ports GAS](https://github.com/Bubberstation/Bubberstation/pull/306)
- [fixes oversized synths/species with nohunger getting huge guts](https://github.com/Bubberstation/Bubberstation/pull/382)

## Reproduction:
Get a pda. Get a cyborg in the cafe. Look for their name in the message lists, bam can send messages. Im unsure if the cyborgs can reply, though.

**Comment by YakumoChen** [comment]
https://github.com/Skyrat-SS13/Skyrat-tg/pull/22708

**Comment by magatsuchi** [comment]
upstream
