### ISSUE TITLE
Trying to recolor anything in loadout leads to NTos Error

### ISSUE THREAD

**Issue by Sweettoothart** [Bubberstation/Bubberstation#409]
Reporting client version: 514.1589

## Round ID:
1859

## Testmerges:
- [Test revert of #190 to try and solve the error-people.](https://github.com/Bubberstation/Bubberstation/pull/208)
- [Blacksmithing workshops](https://github.com/Bubberstation/Bubberstation/pull/294)
- [Reset the Gateway to TGstation, allowing cyborgs to enter](https://github.com/Bubberstation/Bubberstation/pull/248)
- [[MODULAR] Progtot goals override](https://github.com/Bubberstation/Bubberstation/pull/241)
- [[Modular] Makes all techwebs generate points](https://github.com/Bubberstation/Bubberstation/pull/314)
- [Revert antag removal v2](https://github.com/Bubberstation/Bubberstation/pull/367)
- [Revert the Lizard Screams](https://github.com/Bubberstation/Bubberstation/pull/369)
- [Post-upstream fix for PR 344](https://github.com/Bubberstation/Bubberstation/pull/371)
- [Ports GAS](https://github.com/Bubberstation/Bubberstation/pull/306)
- [fixes oversized synths/species with nohunger getting huge guts](https://github.com/Bubberstation/Bubberstation/pull/382)

## Reproduction:
Pull up the loadout on characters, selected something able to be customized. Try to customize it, find out you can not.

**Comment by glitchbow** [comment]
So apparently Skyrat fixed this and then some with [this PR](https://github.com/Skyrat-SS13/Skyrat-tg/pull/22900). If Bubber could get it too and have it fix this issue, that would be great.

**Comment by lurzefromgermany** [comment]
@nevimer close this issue
