### ISSUE TITLE
Connection stability keeps getting worse and worse as days pass

### ISSUE THREAD

**Issue by Androofroo** [Bubberstation/Bubberstation#415]
## Round ID: 1881

The connection stability has been slowly degrading. I notice decals taking a while to load in, the game not responding to inputs, or responding with delay, opening windows in-game (consoles and machines) takes longer than it should, and moving in any direction makes me lag.

Today it got so bad, the game randomly stopped responding to my inputs, be it movement, clicking, or opening the chatbox, it didnt even let me reconnect or close the game, i had to do it through the task manager.

Could anyone dedicate themselves to looking into this? Or implementing ways for the game to be easier to load? The higher population might have something to do with this, but nobody else seems to be suffering this same issue.

Please, and thank you

**Comment by ReturnToZender** [comment]
This isn't really the place to ask for help with network stability, but I'd recommend messaging Zirok on the Discord.

**Comment by nevimer** [comment]
Not a codebase issue but it is known and being worked on behind the scenes.
