### ISSUE TITLE
Borgs do not appear to die when falling into chasms.

### ISSUE THREAD

**Issue by Icarus-The-Sun** [Bubberstation/Bubberstation#417]
## Reproduction:
Throw a borg into a chasm and it will be able to continue to speak and be present in its bodies old position and distinctly NOT a ghost.

**Comment by lurzefromgermany** [comment]
The borg dies, the MMI lives. One ash storm will take care of them.

**Comment by Majkl-J** [comment]
> The borg dies, the MMI lives. One ash storm will take care of them.

This is terribly unintended because it bugs the player out

**Comment by Majkl-J** [comment]
Fixed all the way at tg
