### ISSUE TITLE
Borgs will sleep forever when using Collapse and Faint emotes

### ISSUE THREAD

**Issue by Icarus-The-Sun** [Bubberstation/Bubberstation#418]
## Round ID: 
Unsure, locally tested to confirm.

## Testmerges: 
#382, #306, #371, #361, #314, #241, #248, #294, #208 

## Reproduction:
Using faint/collapse as a borg will force the borg to sleep until reset.

**Comment by thegrb93** [comment]
Can't reproduce as of today

**Comment by Icarus-The-Sun** [comment]
Likely stale at this point, or fixed with a merge of some kind.
