### ISSUE TITLE
Honorbound Sect doesn't work

### ISSUE THREAD

**Issue by Soundverse-Games** [Bubberstation/Bubberstation#44]
When using the honorbound sect there is no way to declare anyone as enemies in order to attack them, theres no ritual using the altar and no way for admins to do it. The honorbound sect also doesnt allow you to attack people even if they attack you and should be considered not just for doing so.

**Comment by magatsuchi** [comment]
this is a tg issue that im pretty sure is already fixed so CLOSED grrr
