### ISSUE TITLE
security medic uniform uses digitigrade sprite for plantigrade

### ISSUE THREAD

**Issue by MaineTheMan** [Bubberstation/Bubberstation#460]
## Reproduction: wear security medic uniform as plantigrade. wtf after
![Screenshot_933](https://github.com/Bubberstation/Bubberstation/assets/64584757/8cbc24cf-6eab-4c97-a375-e1d87f0b2ba6)
![Screenshot_934](https://github.com/Bubberstation/Bubberstation/assets/64584757/8f0558ac-8cf2-4e1a-9fdd-d6cdbc74e7c3)

**Comment by projectkepler-ru** [comment]
@MaineTheMan  Is this still happening?
