### ISSUE TITLE
Medical Borg Drapes Missing

### ISSUE THREAD

**Issue by TripleShades** [Bubberstation/Bubberstation#468]
Reporting client version: 514.1589

## Round ID:
2021

## Testmerges:
- [[non-modular] Space Ninja no longer spawns in BALD. ](https://github.com/Bubberstation/Bubberstation/pull/440)
- [mostly resets dynamic to tg](https://github.com/Bubberstation/Bubberstation/pull/450)
- [Cyborg-Reverse-Nerf](https://github.com/Bubberstation/Bubberstation/pull/458)
- [[MODULAR] Aurora Station Knitting Port](https://github.com/Bubberstation/Bubberstation/pull/317)
- [grrr fixes gags menu cutely](https://github.com/Bubberstation/Bubberstation/pull/463)
- [Jukeboksss Update](https://github.com/Bubberstation/Bubberstation/pull/462)

## Reproduction:
Go medical borg.
Get upgraded.
Realize you have no fucking drapes.
Panic and despair.

**Comment by lurzefromgermany** [comment]
Your surgical processor is drapes.

**Comment by lurzefromgermany** [comment]
> Go medical borg. Get upgraded. Realize you have no fucking drapes. Panic and despair.

https://github.com/Bubberstation/Bubberstation/assets/70082939/672fa7ec-6dc3-40fd-91ca-08328788609d

**Comment by TripleShades** [comment]
Thank you I feel extremely embarassed.
Would it be possible to make this more evident upon examining the processor? And also in the description for it in the mechfab, assuming it doesn't imply anything there as well.
