### ISSUE TITLE
burgerstation issues

### ISSUE THREAD

**Issue by Cyprex** [Bubberstation/Bubberstation#470]
-missing nuke disk
-missing kitchen supplies(flour, some locker apparently?)

**Comment by Cyprex** [comment]
kitchen is 2 closets- freezer/kitchen and freezer/fridge I think. Dunno,check other maps. Also a bottle of enzyme

**Comment by Cyprex** [comment]
odd gateway placement

**Comment by Cyprex** [comment]
xenobio pens lack windoors

**Comment by Cyprex** [comment]
viro is barebones & lacks monkeys

**Comment by Cyprex** [comment]
lacks beakers/syringe boxes

**Comment by Cyprex** [comment]
cryo beakers apparently missing from medbay

**Comment by Cyprex** [comment]
barber lacks massage tables

**Comment by BurgerLUA** [comment]
99% of above have been fixed
1% is what I'm working on right now

**Comment by Tupinambis** [comment]
Maintenance is well built but feels a bit empty in terms of content. I immediately think of meta or delta in terms of what I'm looking for, like maint bar, maint med, maint robotics, maint library, etc. It also lacks smaller maint rooms and hangout spots which are always nice to have for RP and/or antag purposes.

Maint also felt a bit too narrow with one tile halls, so a bit of widening with bumps of grilles, walls, and loot would probably be nice.

**Comment by DeerJesus** [comment]
janitor shutters are all-access

**Comment by Tupinambis** [comment]
No bot patrol nodes, so bots just kinda stand there doing nothing even on patrol mode.

**Comment by BurgerLUA** [comment]
> No bot patrol nodes, so bots just kinda stand there doing nothing even on patrol mode.

They exist. I don't know why they stopped working.

**Comment by Tupinambis** [comment]
> > No bot patrol nodes, so bots just kinda stand there doing nothing even on patrol mode.
> 
> They exist. I don't know why they stopped working.

This was my bad, it was just the hygeinebots

Couple of other robotics issues though: No roundstart proximity sensors, which forces you to go to cargo or tech storage to use an autolathe, and only two flashes which is fewer than on other maps.

Additionally robotics lacks a fuel tank, which means robos have to scrounge maint for one to refill their welders.

**Comment by Tupinambis** [comment]
The AI sat cameras are accessible with standard sec cams, they should only be accessible via the RD telescreen. Otherwise it's too easy to spot malf/rogue AI shenanigans.

**Comment by Literallynotpickles** [comment]
cargo-bay (top) conveyer lever controls like 4 tiles of the (bottom) conveyer and the (bottom) controls like 1 tile of the (top)

the bay also has quite a few disposal pipes (near the bottom row of reinforced glass floors) that seem to just lead nowhere and you don't appear to be able to r-glass floors with any normal tools

**Comment by BurgerLUA** [comment]
> cargo-bay (top) conveyer lever controls like 4 tiles of the (bottom) conveyer and the (bottom) controls like 1 tile of the (top)
> 
> the bay also has quite a few disposal pipes (near the bottom row of reinforced glass floors) that seem to just lead nowhere and you don't appear to be able to remove r-glass floors with any normal tools

thanks for reporting this, i don't know how I missed this lmao 
![image](https://github.com/Bubberstation/Bubberstation/assets/8602857/b793d434-39ce-473f-9000-a2ddd62ceeb7)

**Comment by Literallynotpickles** [comment]
lacking paramedic access to the first two engi-foyer doors (so assuming the same for prolathe room too)
