### ISSUE TITLE
Stuck in bloodcrawl

### ISSUE THREAD

**Issue by GoreDem** [Bubberstation/Bubberstation#479]
## Testmerges: 
[#450: 'mostly resets dynamic to tg' by nevimer at commit c6fd998a40](https://github.com/Bubberstation/Bubberstation/pull/450)
[#458: 'Cyborg-Reverse-Nerf' by lurzefromgermany at commit f4ac6be93d](https://github.com/Bubberstation/Bubberstation/pull/458)
[#317: '[MODULAR] Aurora Station Knitting Port' by Icarus-The-Sun at commit d5331425d2](https://github.com/Bubberstation/Bubberstation/pull/317)
[#471: 'Obscure Examine Panel Pref' by GreytidePanda at commit f65fe12c59](https://github.com/Bubberstation/Bubberstation/pull/471)

**Comment by Serxule** [comment]
were you near blood?

**Comment by GoreDem** [comment]
Yeah

**Comment by GoreDem** [comment]
Works now
