### ISSUE TITLE
Character Preferences - Occupations bugged. Characters can be locked out of selecting certain jobs.

### ISSUE THREAD

**Issue by dandydragon** [Bubberstation/Bubberstation#487]
Reporting client version: 514.1589

Occupations for Character Preferences is bugged for the Supply jobs. For the sake of simplicity, I will refer to each "slot" as a number.
![image](https://github.com/Bubberstation/Bubberstation/assets/89354011/0bf325e6-494e-4709-8c62-cb7c705a4aa8)
**Slot 1, 3, and 5 do not have Quartermaster, Cargo Technician, or Shaft Miner for their respective dropdown menus.** This means that if someone selects a different job in that slot, they can no longer select and play Quartermaster, Cargo Technician, or Shaft Miner.

![image](https://github.com/Bubberstation/Bubberstation/assets/89354011/007e9c16-9676-43b6-91ff-8c3c3433f22c)
![image](https://github.com/Bubberstation/Bubberstation/assets/89354011/a1ec580f-698d-40b4-ab4b-2a26401f2fb7)
Normal. I can freely go back to Virologist.

![image](https://github.com/Bubberstation/Bubberstation/assets/89354011/34e37796-7da7-4f3b-ab2c-4103bff4851f)
![image](https://github.com/Bubberstation/Bubberstation/assets/89354011/96ad8ab7-4bcd-4577-8124-295744f5df25)
Bugged. Note the lack of "Quartermaster" on the dropdown menu. Quartermaster can no longer be selected for this character.

## Round ID:
2080

## Testmerges:
- [mostly resets dynamic to tg](https://github.com/Bubberstation/Bubberstation/pull/450)
- [Cyborg-Reverse-Nerf](https://github.com/Bubberstation/Bubberstation/pull/458)
- [[MODULAR] Aurora Station Knitting Port](https://github.com/Bubberstation/Bubberstation/pull/317)
- [Obscure Examine Panel Pref](https://github.com/Bubberstation/Bubberstation/pull/471)
- [Adds a new map](https://github.com/Bubberstation/Bubberstation/pull/459)
- [[Non-Modular] Makes Changeling normal again](https://github.com/Bubberstation/Bubberstation/pull/480)
- [Storyteller port from horizon [DNM]](https://github.com/Bubberstation/Bubberstation/pull/456)

## Reproduction:
1. Open game before starting a round, go to Character Preferences, and ideally go to an unused character slot.
2. Select Slot 1, 3, or 5.
3. Select any role.
4. You can no longer play Quartermaster, Cargo Technician, or Shaft Miner for that character.

**Comment by dandydragon** [comment]
Additional, but much less concerning bug.

![image](https://github.com/Bubberstation/Bubberstation/assets/89354011/afaf570e-021b-4622-852f-5d38b72caca9) 
![image](https://github.com/Bubberstation/Bubberstation/assets/89354011/37f6998d-9a15-42f3-8d08-f8fe150922ec)
Service Guard is the default job for this slot. Oddly, it does not appear on the top of the dropdown menu, unlike other slots. **You are still able to select Service Guard** from the dropdown menu if you click Bouncer. 
So, not a big deal.

**Comment by Erol509** [comment]
I belive its a upstream issue, because they decided to turn cargo into union. Im not sure hownit is now, but it used to be on skyrat too
