### ISSUE TITLE
(Item/Code Bounty) Portal Panty+Fleshlight kit

### ISSUE THREAD

**Issue by Iemier** [Bubberstation/Bubberstation#511]
I'm not sure what would be a good offer on something like this, but I'd happily pay for a recreation or port from one of the stations that has a functional one.  I was told that Skyrat had one; I know Splurt also has them.  My gut impulse says around $50, but I honestly don't know if that's too high or too low.

**Comment by Majkl-J** [comment]
Been told this won't happen
