### ISSUE TITLE
Edited antag objectives have issues being shown in the round-end menu

### ISSUE THREAD

**Issue by ronfino** [Bubberstation/Bubberstation#52]
I have noticed that when editing antag objectives it won't show the edited ones at round-end panel but the default ones that are given at round-start.

Example: i changed two blood brothers' objectives from assassination to stealing items but in the round-end panel they still had the original ones.
![Winner2](https://user-images.githubusercontent.com/77462428/221160898-001d297f-4c73-43d2-92fe-e03faf4902bf.png)

**Comment by magatsuchi** [comment]
stale
