### ISSUE TITLE
Game Options: Widescreen Not Working

### ISSUE THREAD

**Issue by Floofies** [Bubberstation/Bubberstation#534]
## Round ID: 2231

Seems to be round-independent.

## Testmerges:

[#450: 'mostly resets dynamic to tg' by nevimer at commit c6fd998a40](https://github.com/Bubberstation/Bubberstation/pull/450)
[#459: 'Adds a new map' by BurgerLUA at commit 3ed73395a9](https://github.com/Bubberstation/Bubberstation/pull/459)
[#505: 'Nerfs Fingerprints + Olfaction: Remade' by BurgerLUA at commit dbd1701136](https://github.com/Bubberstation/Bubberstation/pull/505)
[#520: '(Mostly-Modular) SSV Dauntless - Interdyne Rework' by StrangeWeirdKitten at commit 8e3140588a](https://github.com/Bubberstation/Bubberstation/pull/520)
[#522: '[MODULAR] Ashwalker-friend' by lurzefromgermany at commit 5b0421c3ef](https://github.com/Bubberstation/Bubberstation/pull/522)
[#518: 'You can now sext (Send PDA messages) when resting' by Majkl-J at commit f03da71cbd](https://github.com/Bubberstation/Bubberstation/pull/518)
[#532: 'Removes Unecessary Skyrat Edits that made the HoS Gun Useless' by Tupinambis at commit de208f4ab0](https://github.com/Bubberstation/Bubberstation/pull/532)
[#531: 'Removed skyratified armories, reverting them to tg standard gearsets.' by Tupinambis at commit df57aec426](https://github.com/Bubberstation/Bubberstation/pull/531)
[#530: 'Threat Level is displayed at the join game menu' by BurgerLUA at commit d9740f7508](https://github.com/Bubberstation/Bubberstation/pull/530)
[#528: '[Semi-Definitely-Non-Modular] Service Borg Edits' by IgiariValkyr at commit cf7768a99f](https://github.com/Bubberstation/Bubberstation/pull/528)
[#524: 'surgery cap default changed to loosened state' by Literallynotpickles at commit d595fe122c](https://github.com/Bubberstation/Bubberstation/pull/524)
[#502: 'Clockcult Cogging Changes' by destrucktoid at commit c456db52d4](https://github.com/Bubberstation/Bubberstation/pull/502)
[#448: 'amonugs' by tf-4 at commit 50a2359a93](https://github.com/Bubberstation/Bubberstation/pull/448)

## Reproduction:

Join the server, The game will immediately say "CRITICAL FAILURE IN PREFERENCE MIGRATION, REPORT THIS IMMEDIATELY." in the chat panel which may be related. Open Game Options, try to change the Widescreen setting in the UI tab, and observe that Widescreen stays disabled regardless of whether or not the checkbox is checked. Other preferences seem to work OK.

**Comment by nevimer** [comment]
Has it reoccured for you?

**Comment by Floofies** [comment]
@nevimer 

It has not! It has stopped being reproducible for me now. I'm now able to change the checkbox and see the screen size change.

**Comment by yorii** [comment]
I recently joined the server for the first time, using an ultrawide screen, didn't notice anything weird.
Probably safe to close this.
