### ISSUE TITLE
Compact AI Circuit Bug

### ISSUE THREAD

**Issue by Courier2223** [Bubberstation/Bubberstation#543]
## Reproduction: Upon creation

I was not the one who made this occur, but it has happened twice, and I have been the one to spawn in as it twice. It seems upon creation of a Compact AI Circuit, or perhaps activation, it will immediately teleport to the debug room and the player inside the card will be trapped there until they ghost eventually. I am sorry that I do not have any more details as to why this happens, but I am only the person who has been the compact AI twice now. This pictured below is proof that this happens.
![Evidence](https://github.com/Bubberstation/Bubberstation/assets/144965367/31983934-b987-464e-84ba-4bac5c1688aa)

**Comment by rintherat** [comment]
not sure if you can make these things anymore. recreating this in thunderdome did not yield similar results. need more info, what map was it, what made the circuit? only thing i see is the skyrat module

**Comment by Majkl-J** [comment]
This might no longer be happening

**Comment by Majkl-J** [comment]
Closed due to being unable to reproduce anymore

**Comment by Majkl-J** [comment]
Turns out this is still happening
