### ISSUE TITLE
Polymorphic Holoparasite

### ISSUE THREAD

**Issue by Glyphee** [Bubberstation/Bubberstation#571]
Reporting client version: 514.1589

## Round ID:
2354

## Testmerges:
- [mostly resets dynamic to tg](https://github.com/Bubberstation/Bubberstation/pull/450)
- [Changes Obsessed objs to less round-removing types](https://github.com/Bubberstation/Bubberstation/pull/558)
- [Storyteller port from horizon [DNM]](https://github.com/Bubberstation/Bubberstation/pull/456)
- [Early Pull: Feature: bitrunner, a new supply role (READY) (#77259)](https://github.com/Bubberstation/Bubberstation/pull/569)
- [early pull: https://github.com/tgstation/tgstation/pull/78564](https://github.com/Bubberstation/Bubberstation/pull/570)

## Reproduction:

The polymorphic belt can be used on some very abusable mobs, like for instance a holoparasite, which when spawned without a host is literally invincible.

**Comment by Serxule** [comment]
report this on TG, as theyre the ones who made it (and are working on it)

**Comment by StrangeWeirdKitten** [comment]
https://github.com/tgstation/tgstation/issues/78578
