### ISSUE TITLE
Uniform stripping proc doesn't fully get completed, and bugs out your character.

### ISSUE THREAD

**Issue by BurgerLUA** [Bubberstation/Bubberstation#576]
## Testmerges:

Might be caused by #573. Probably caused by it. Very likely.

## Reproduction:

- ~~Get almost killed by a shadowling in the hallways.~~
- ~~2 people watch as you near bleed out, calling for help.~~
- ~~Collapse into crit.~~
- ~~Captain does a snide announcement about maxing suit sensors.~~
- ~~Survive because you injected yourself with meds you found in maint.~~
- ~~Arrive at medical. Spent 5 minutes waiting for treatment, and another 5 minutes being treated for malpractice because someone used O- blood on you when you're a lizard.~~
- Try to get stripped by medical for brute treatment surgery even though you have like 5 brute damage.
- Medical spends another 5 minutes taking turns stripping you because they can't seem to remove your uniform and refuse to ahelp the issue.
- The uniform item object is removed, but it actually isn't removed on your character.
- Character is bugged for the rest of the game.
- ~~Cryo because you're assblasted.~~

**Comment by Majkl-J** [comment]
I did only basic level testing and this didnt come up but I'll look into it.

**Comment by Majkl-J** [comment]
This shouldnt happen unless I fucked up indentations since my edit only effects the part that drops all your items

**Comment by Majkl-J** [comment]
Alright let this be a lesson about not doing enough testing and hyper focusing on other issues. Fixed
