### ISSUE TITLE
you cannot observe or go to the gateway as a ghost at all (unless you use auto-observe on someone in the gateway)

### ISSUE THREAD

**Issue by MaineTheMan** [Bubberstation/Bubberstation#578]
## Testmerges: [#450: 'mostly resets dynamic to tg' by nevimer at commit a6168f82a0](https://github.com/Bubberstation/Bubberstation/pull/450)
[#558: 'Changes Obsessed objs to less round-removing types' by rintherat at commit 132736d8ae](https://github.com/Bubberstation/Bubberstation/pull/558)
[#456: 'Storyteller port from horizon [DNM]' by nevimer at commit 896f10089d](https://github.com/Bubberstation/Bubberstation/pull/456)
[#569: 'Early Pull: Feature: bitrunner, a new supply role (READY) (#77259)' by nevimer at commit e9c0ff2ce6](https://github.com/Bubberstation/Bubberstation/pull/569)
[#570: 'early pull: https://github.com/tgstation/tgstation/pull/78564' by nevimer at commit 2bc9d45b11](https://github.com/Bubberstation/Bubberstation/pull/570)
[#574: 'Revert "Fixes vents having "infinite" pressure caps. (#77686)"' by nevimer at commit b96a1c8673](https://github.com/Bubberstation/Bubberstation/pull/574)

Local commit: 8b8744af721443f6a61ba21526db2c6801f94a8d
TGS version: 5.12.2
DMAPI version: 5.6.1

**Comment by rintherat** [comment]
Not a bug, the area was set to secret, disallowing you to do this. Fully intentional by staffmembers.

**Comment by Majkl-J** [comment]
Intended behaviour

**Comment by Majkl-J** [comment]
Intended behaviour
