### ISSUE TITLE
Riot dart recycler module broken

### ISSUE THREAD

**Issue by Cool10007** [Bubberstation/Bubberstation#584]
## Reproduction:
The Riot dart recycler module from the Black market didn't work at all. It won't pay out the darts, makes the pickup noise when going over garbage without picking it up and ate four boxes of riot darts and two of normal darts while still saying it didn't have enough materials. I was in a standard modsuit with the civilian skin.

**Comment by projectkepler-ru** [comment]
Tested this, didn't discover the same bug, infact, I discovered an entirely new bug where instead it use up all the resource at once to produce one box, allowing you to actually lose out materials
