### ISSUE TITLE
mkultra: bugged temperature

### ISSUE THREAD

**Issue by thematycer** [Bubberstation/Bubberstation#652]
## Round ID:2619

While adding beaker filled with chemicals needed to make mkultra:
1 part Coco Powder
1 part Bluespace Dust
1 part Mindbreaker Toxin
1 part Psicodine
1 part Happiness
1 unit Blood (catalyst)
 and with correct pH 12-13. if you set any temperature on said heater. The chemical temperature gets set every tick as random value between 400 to 1000- does not matter what temperature you set, just that heater is on. heating chemicals with welder works normally, but doesnt give any results

**Comment by catmanpop** [comment]
If understanding chem, some force a set temp when created (such as seiver and anything in the beaker being set to 0k)

**Comment by Swiftfeather** [comment]
We don't even have MK ultra anymore

**Comment by thematycer** [comment]
which maybe causes this bug? maybe?
