### ISSUE TITLE
pAIs prevent people from going though gateway

### ISSUE THREAD

**Issue by KeptheKobold** [Bubberstation/Bubberstation#670]
## Testmerges:
[#450: 'mostly resets dynamic to tg' by nevimer at commit a6168f82a0](https://github.com/Bubberstation/Bubberstation/pull/450)
[#456: 'Storyteller port from horizon [DNM]' by nevimer at commit 896f10089d](https://github.com/Bubberstation/Bubberstation/pull/456)
[#570: 'early pull: https://github.com/tgstation/tgstation/pull/78564' by nevimer at commit 2bc9d45b11](https://github.com/Bubberstation/Bubberstation/pull/570)
#574: 'Revert "Fixes vents having "infinite" pressure caps. (#77686)" &  Overclocked Vent Pumps (#78583) ' by nevimer at commit 149d839b81
[#583: 'Ports Gimmick Traitor from Daedalus Dock (and raises starting TC)' by nevimer at commit 8162c64b8f](https://github.com/Bubberstation/Bubberstation/pull/583)
[#573: '[NOW WITH LESS BUGS AND OVERSIGHTS 2] Undressing as synth no longer drops all your items' by Majkl-J at commit 1ebd7fb9fb](https://github.com/Bubberstation/Bubberstation/pull/573)
[#598: '[Testmerge Ready] Adds the RB-MK2 Reactor, Makes Tritium buyable from Cargo' by BurgerLUA at commit 63115a924e](https://github.com/Bubberstation/Bubberstation/pull/598)
[#612: 'Seedlings can no longer have the Perennial Growth (Repeatable Harvest) trait because I died to them once.' by BurgerLUA at commit 3fb9ec0207](https://github.com/Bubberstation/Bubberstation/pull/612)
[#625: 'Contractor and Ninja Modsuits Are Eternal (and cannot be removed)' by nevimer at commit cf1185ffdf](https://github.com/Bubberstation/Bubberstation/pull/625)
[#659: 'Revert "Tints the screen for halloween (#79062)"' by nevimer at commit 6faafe8fb4](https://github.com/Bubberstation/Bubberstation/pull/659)
[#658: 'Early Pull: Retires the Vore pref, replaces it with a Hypno pref' by StrangeWeirdKitten at commit 43b6ce1503](https://github.com/Bubberstation/Bubberstation/pull/658)
[#634: '{Ready] Adds nearly every toy/fun item to Arcade Loot, makes 1 ticket vend 1 prize.' by BurgerLUA at commit f6372e5ecc](https://github.com/Bubberstation/Bubberstation/pull/634)
[#480: '[Non-Modular] Reverts changeling balance back to TG' by ReturnToZender at commit ce1f1b6710](https://github.com/Bubberstation/Bubberstation/pull/480)
[#655: 'Adds the WT-551' by BurgerLUA at commit 0dd03b4934](https://github.com/Bubberstation/Bubberstation/pull/655)
[#665: '[Fixes modularity] Restores Radioblock refreshed' by ReturnToZender at commit e2290100e0](https://github.com/Bubberstation/Bubberstation/pull/665)
[#668: '[Testmerge Only] Adds reverie to the fax list' by ReturnToZender at commit b6a15d58c8](https://github.com/Bubberstation/Bubberstation/pull/668)

## Reproduction:
Download a personal AI and have it on your person
Try to enter a gateway

Youll be blocked with message that [pAI Name] seems to be blocking you from entering.

**Comment by StrangeWeirdKitten** [comment]
This isn't a bug. Skyrat made silicons unable to enter gateways.

**Comment by projectkepler-ru** [comment]
@KeptheKobold  you'll have to refer to skyrat for this as this is intended
