### ISSUE TITLE
Codex Cicatrix uncraftable

### ISSUE THREAD

**Issue by destrucktoid** [Bubberstation/Bubberstation#676]
## Round ID:

2668

## Testmerges:

[#450: 'mostly resets dynamic to tg' by nevimer at commit 3998b2e04b](https://github.com/Bubberstation/Bubberstation/pull/450)
[#456: 'Storyteller port from horizon [DNM]' by nevimer at commit 896f10089d](https://github.com/Bubberstation/Bubberstation/pull/456)
[#583: 'Ports Gimmick Traitor from Daedalus Dock (and raises starting TC)' by nevimer at commit 8162c64b8f](https://github.com/Bubberstation/Bubberstation/pull/583)
[#655: 'Adds the WT-551, Unskyrats the WT-550 ammo' by BurgerLUA at commit 6a30f2c47d](https://github.com/Bubberstation/Bubberstation/pull/655)
[#634: '{Ready] Adds nearly every toy/fun item to Arcade Loot, makes 1 ticket vend 1 prize.' by BurgerLUA at commit b804802463](https://github.com/Bubberstation/Bubberstation/pull/634)
[#659: 'Revert "Tints the screen for halloween (#79062)"' by nevimer at commit 6faafe8fb4](https://github.com/Bubberstation/Bubberstation/pull/659)
[#570: 'early pull: https://github.com/tgstation/tgstation/pull/78564' by nevimer at commit 2bc9d45b11](https://github.com/Bubberstation/Bubberstation/pull/570)
#574: 'Revert "Fixes vents having "infinite" pressure caps. (#77686)" &  Overclocked Vent Pumps (#78583) ' by nevimer at commit 149d839b81
[#658: 'Early Pull: Retires the Vore pref, replaces it with a Hypno pref' by StrangeWeirdKitten at commit 43b6ce1503](https://github.com/Bubberstation/Bubberstation/pull/658)
[#625: 'Contractor and Ninja Modsuits Are Eternal (and cannot be removed)' by nevimer at commit cf1185ffdf](https://github.com/Bubberstation/Bubberstation/pull/625)
[#668: '[Event Testmerge Only] Adds reverie to the fax list' by ReturnToZender at commit b6a15d58c8](https://github.com/Bubberstation/Bubberstation/pull/668)
[#674: 'Memory leak quick fix (DO NOT MERGE)' by StrangeWeirdKitten at commit bf14d36721](https://github.com/Bubberstation/Bubberstation/pull/674)

## Reproduction:

Try to make codex cicatrix, it doesn't work.

**Comment by projectkepler-ru** [comment]
how exactly are you supposed to make one?
