### ISSUE TITLE
Buckshot is Broken

### ISSUE THREAD

**Issue by ThinkArbies** [Bubberstation/Bubberstation#679]
[Round ID]: Reported on #2763 but really any round is applicable.

## Reproduction: 

Load any shotgun (tested with HoS' compact and Carwo Renoster) with buckshot of basic or really any variety and attempt to shoot and nothing will happen. The only way buckshot works is if fired point-blank at someone.

And yes I skimmed through tg's github and there is no reported issue regarding buckshot.

**Comment by StrangeWeirdKitten** [comment]
This is being fixed by an upstream merge
