### ISSUE TITLE
Material synthesizer on engineering silicons lockout

### ISSUE THREAD

**Issue by aKromatopzia** [Bubberstation/Bubberstation#689]
When attempting to use the engineering model's material manipulator on an inactive [material] synthesizer module, it locks the module out after retrieving it successfully - once. The module will still be visible, but unusable. The sprite on the ground when the material is dropped from the manipulator additionally ignores lighting.

Example sprite: 
![Screenshot_34](https://github.com/Bubberstation/Bubberstation/assets/94389683/0516de3b-a797-471f-bf94-c13712e8f752)

**Comment by Majkl-J** [comment]
Can't reproduce anymore, presumably fixed
