### ISSUE TITLE
Lime Juice from the biogen is actually orange juice

### ISSUE THREAD

**Issue by trazodont** [Bubberstation/Bubberstation#693]
Reporting client version: 514.1589

## Round ID:
2722

## Testmerges:
- [Storyteller port from horizon [DNM]](https://github.com/Bubberstation/Bubberstation/pull/456)
- [Ports Gimmick Traitor from Daedalus Dock (and raises starting TC)](https://github.com/Bubberstation/Bubberstation/pull/583)
- [early pull: https://github.com/tgstation/tgstation/pull/78564](https://github.com/Bubberstation/Bubberstation/pull/570)
- [Revert "Fixes vents having "infinite" pressure caps. (#77686)" &  Overclocked Vent Pumps (#78583) ](https://github.com/Bubberstation/Bubberstation/pull/574)
- [Early Pull: Retires the Vore pref, replaces it with a Hypno pref](https://github.com/Bubberstation/Bubberstation/pull/658)
- [Contractor and Ninja Modsuits Are Eternal (and cannot be removed)](https://github.com/Bubberstation/Bubberstation/pull/625)
- [[Event Testmerge Only] Adds reverie to the fax list](https://github.com/Bubberstation/Bubberstation/pull/668)
- [round end credits](https://github.com/Bubberstation/Bubberstation/pull/677)
- [[Ready] Firelock (and air alarm) Overhaul](https://github.com/Bubberstation/Bubberstation/pull/492)
- [[Not Modular] Drifting contractor adjustments](https://github.com/Bubberstation/Bubberstation/pull/667)

## Reproduction:

Use the biogen for lime juice, get only orange juice.

**Comment by Majkl-J** [comment]
This can't be real

**Comment by Majkl-J** [comment]
![image](https://github.com/Bubberstation/Bubberstation/assets/49160555/f9833d7b-f0c9-4b5e-a81e-54e916d44a7e)
It is nevermind
