### ISSUE TITLE
Mod Shell Part Duplication

### ISSUE THREAD

**Issue by EldritchBaguette** [Bubberstation/Bubberstation#695]
## Round ID:
2726

## Testmerges:
#456
#574
#658
#625
#668

## Reproduction:
I accidentally duplicated a mod suit chestplate while assembling mod suits.

This was done by:
1- Starting to assemble the modsuit shell by alt-clicking the tile and up the shell itself from the tile.
2 - installing and securing a mod core in the shell
3- Adding helmet to modsuit shell, picked up via tile menu
4 - Adding chestplate to modsuit shell, picked up  via tile menu
5 - Accidentally clicking the chestplate in the tile menu when trying to grab the gauntlets
6 - Suddenly, chestplate i didnt fabricate.

**Comment by projectkepler-ru** [comment]
Need reproduction, I couldn't get this to work
