### ISSUE TITLE
Chaplain Mechanical God Conversion Rite - Digitigrade legs become unhealable through almost all means

### ISSUE THREAD

**Issue by NargaInDisguise** [Bubberstation/Bubberstation#705]
## Reproduction:
If you have digitigrade legs on your character, and are placed through a chaplain mechanical god android conversion rite, when you become robotic, your legs are completely incapable of being healed outside of two very specific methods.
A rapid first aid device and a medigun.

For some reason the legs stay organic, but when you try to heal them with chems/sutures/regen mesh/whatever, it'll tell you "There is no thin material or exposed flesh on this body part." This means that you cannot heal them in any way without a medigun/first aid device.

This has happened 100% consistently with my character Stryk so I know its easily reproducible.

**Comment by projectkepler-ru** [comment]
Does this still happen?

**Comment by NargaInDisguise** [comment]
At christmas stuff today, will attempt replication when I get home, but I have no reason to believe it isnt still bugged.

**Comment by NargaInDisguise** [comment]
Agh accidentally hit the close button bcuz of mobile

**Comment by aKromatopzia** [comment]
So I made sprites for the potential fix, but I'm at a loss of what causes this. Having a robotic leg keeps it robotic, so idk...?

**Comment by aKromatopzia** [comment]
This is unfortunately not complete but I cannot fix it here. This is a Skyrat code issue

**Comment by NargaInDisguise** [comment]
Cool reply, anyhow...
I can confirm that THIS IS STILL bugged via live testing.
