### ISSUE TITLE
Deconverted cultist sees cult overlay/icons

### ISSUE THREAD

**Issue by KazooBard** [Bubberstation/Bubberstation#730]
## Reproduction:
I was a cultist, got deconverted with holy water and then these persisted. No clue how that works, but here's a video showing how it looks. Apparently thanks to Burger's info the icons were not 100% accurate since Bar (green lizard bunny ears) was a cultist at the time, yet no icon for them. 
https://github.com/Bubberstation/Bubberstation/assets/65713506/72c00be6-235b-4138-b972-cb6206437c19

(if anything is lacking, notify me. First time I make an issue, so some stuff might be missing from this report.)

**Comment by Majkl-J** [comment]
Seems to have been fixed
