### ISSUE TITLE
Borgs cannot use their crushers

### ISSUE THREAD

**Issue by shellspeed1** [Bubberstation/Bubberstation#731]
## Testmerges:

[#456: 'Storyteller port from horizon [DNM]' by nevimer at commit aa3b527d63](https://github.com/Bubberstation/Bubberstation/pull/456)
[#625: 'Contractor and Ninja Modsuits have a deployable macrobomb (Enable the DNA lock and hit Lock on the modsuit to arm)' by nevimer at commit 6c1dd1cc91](https://github.com/Bubberstation/Bubberstation/pull/625)
[#306: 'Ports GAS' by nevimer at commit 9b5b12ae48](https://github.com/Bubberstation/Bubberstation/pull/306)
[#700: '[Mostly Modular] Hypnosis Preference' by StrangeWeirdKitten at commit 42a3878da0](https://github.com/Bubberstation/Bubberstation/pull/700)
[#719: '[Modular] Removes multiple secure tech boards from the research tree (Makes them orderable)' by StrangeWeirdKitten at commit 01a07248b2](https://github.com/Bubberstation/Bubberstation/pull/719)

**Comment by thegrb93** [comment]
I actually couldn't reproduce this. Pressing z with the crusher selected gives the message 'You dedicate your module to the proto-kinetic crusher (Wielded)' and using it works fine.

**Comment by thegrb93** [comment]
I tested locally so might be a test merge. Will test in server later

**Comment by Majkl-J** [comment]
> I actually couldn't reproduce this. Pressing z with the crusher selected gives the message 'You dedicate your module to the proto-kinetic crusher (Wielded)' and using it works fine.

It shows the message but doesn't actually create the offhand_item correctly due to borg put_in_hand_check not allowing it to be put in the borgs module. This results in the state of the offhand being less than ideal and some unintended behaviour

**Comment by Majkl-J** [comment]
update: that is an unrelated bug. Turns out the crusher has no borg secondary attack

**Comment by thegrb93** [comment]
@Majkl-J It seems you have to right-click within 1 tile distance of yourself for it to work
