### ISSUE TITLE
Elephant snout rendering issue- tips of tusks render black regardless of color settings, looks wonky.

### ISSUE THREAD

**Issue by SpiritAngler** [Bubberstation/Bubberstation#736]
Round ID: 2802

BYOND Version: 515.1616
Server revision compiled on: 2023-11-15T19:41:06+00:00
Master commit: [8d6944ddfb490ff26a344076c7313160502f5dcc](https://github.com/Bubberstation/Bubberstation/commit/8d6944ddfb490ff26a344076c7313160502f5dcc)
The following pull requests are currently test merged:
[#456: 'Storyteller port from horizon [DNM]' by nevimer at commit aa3b527d63](https://github.com/Bubberstation/Bubberstation/pull/456)
[#625: 'Contractor and Ninja Modsuits have a deployable macrobomb (Enable the DNA lock and hit Lock on the modsuit to arm)' by nevimer at commit 6c1dd1cc91](https://github.com/Bubberstation/Bubberstation/pull/625)
[#306: 'Ports GAS' by nevimer at commit 9b5b12ae48](https://github.com/Bubberstation/Bubberstation/pull/306)
[#700: '[Mostly Modular] Hypnosis Preference' by StrangeWeirdKitten at commit 42a3878da0](https://github.com/Bubberstation/Bubberstation/pull/700)
[#719: '[Modular] Removes multiple secure tech boards from the research tree (Makes them orderable)' by StrangeWeirdKitten at commit 01a07248b2](https://github.com/Bubberstation/Bubberstation/pull/719)

## Reproduction:
Open character creator. Choose elephant snout. Notice tusks are reading a 100% black coloration, for some reason. Pretty simple, sorry for making this in the first place- just wanna play an elephant, but it looks baaaaaad.

**Comment by Majkl-J** [comment]
Seems to have been fixed
