### ISSUE TITLE
Cybernetic Naga sprite being broken

### ISSUE THREAD

**Issue by AshVietnam** [Bubberstation/Bubberstation#738]
When having Cybernetic Naga taur body, bloody sprites are off to the right by quite bit which is outside of character sprite and when using _**mark turf conscript to be precise**_ makes character leg sprites to show up above the tail sprite which ruins the look of it.

**Links of those images:**
https://cdn.discordapp.com/attachments/1061433759947313233/1175085208479989800/image.png?ex=6569f261&is=65577d61&hm=cbb09e5ccf2a9e84f05f704ebf81bf112826b88d23b7398c25fd5fb4c4366207&

https://cdn.discordapp.com/attachments/1061433759947313233/1175085209247551550/image.png?ex=6569f261&is=65577d61&hm=ebdbf036980062cf69fea4f85fcbff01b1b2fcc85c548e3016c1bdae5b7de43d&

**Comment by Majkl-J** [comment]
Took my bloody time but eh, could take a look at it
