### ISSUE TITLE
Single Legion skull instakill/legionfied at orange health while not in crit state.

### ISSUE THREAD

**Issue by BoringSkully** [Bubberstation/Bubberstation#743]
## Round ID: 2816

 2816

 Bubberstation

## Reproduction:

 I was in lavaland to help a dead miner, ran past the legion tendril and took some damage on the way there, only one legion skull was chasing me so I was going to kill it and tank the hit. I was at half or at least below half of health, the orange color but after I got hit by the skull, I instantly transformed into a legion, not even in crit at all.

**Comment by projectkepler-ru** [comment]
I could not replicate this

**Comment by BoringSkully** [comment]
Aw darn, the only thing I can think of what happened was I got incredibly
unlucky.
There wasn't lag either.
Oh and apologies for the late reply.

**Comment by projectkepler-ru** [comment]
> Aw darn, the only thing I can think of what happened was I got incredibly unlucky. There wasn't lag either. Oh and apologies for the late reply.

I'll keep it up incase something encounter this otherwise you're free to close it
