### ISSUE TITLE
Morph does not have threat

### ISSUE THREAD

**Issue by GoreDem** [Bubberstation/Bubberstation#769]
## Reproduction: Spawn morph, wait till round end, see it's on the round end report but not under executed rules
![image](https://github.com/Bubberstation/Bubberstation/assets/58603746/b939fec1-a38c-418d-b912-9e7be510c2a4)
![image](https://github.com/Bubberstation/Bubberstation/assets/58603746/b025af0e-2efc-4b57-ab1e-51c8b669e6dc)

**Comment by StrangeWeirdKitten** [comment]
not a bug. Morph is considered an event.
