### ISSUE TITLE
Giant Error message on modsuit depowering

### ISSUE THREAD

**Issue by Zulu0009** [Bubberstation/Bubberstation#775]
Reporting client version: 514.1589

## Round ID:
2881

## Testmerges:
- [Storyteller port from horizon [DNM]](https://github.com/Bubberstation/Bubberstation/pull/456)
- [Contractor and Ninja Modsuits have a deployable macrobomb (Enable the DNA lock and hit Lock on the modsuit to arm)](https://github.com/Bubberstation/Bubberstation/pull/625)
- [Sol-Fed Guns Return to Cargo](https://github.com/Bubberstation/Bubberstation/pull/754)
- [[Event Testmerge Only] Adds reverie to the fax list](https://github.com/Bubberstation/Bubberstation/pull/668)
- [Cherry Pick: Gives blueshields a new shoulder-bruising "submachinegun" (Early Balance Changes)](https://github.com/Bubberstation/Bubberstation/pull/768)
- [Blueshield Part II: The MOD suit awakening (+ buffs security modsuit armor)](https://github.com/Bubberstation/Bubberstation/pull/771)

## Reproduction:
Wearing, deploying and powering, then depowering a standard modsuit. Image attached. The player is a lizardperson with some character augments like a tail, wings, snout, horns and digitigrade legs, if that helps.

![image](https://github.com/Bubberstation/Bubberstation/assets/69118363/21f87696-05b8-4fa3-9478-c7815b3fc91b)

**Comment by projectkepler-ru** [comment]
This might be an issue related to upstream not having an icon  for it? I'll check in 1-2 business days again if it's still a thing

**Comment by Majkl-J** [comment]
You most likely peaked the overlay limit since I can't reproduce it
