### ISSUE TITLE
Emergency shuttle consoles stay hijackable when it's not on the shuttle during the escape

### ISSUE THREAD

**Issue by OceanFish1** [Bubberstation/Bubberstation#799]
## Reproduction: Move the console away from the shuttle/Remove the floor under it. You can still emag/hijack it while you're not on the shuttle. 

Making it to make sure coders are aware. Maybe make it unmovable, maybe add a special kind of floor under the consoles of all shuttles, maybe it should be moved to a feature reqeust. I don't know, but I want to make sure people know about this since it went so far.

**Comment by Majkl-J** [comment]
![image](https://github.com/Bubberstation/Bubberstation/assets/49160555/79d4121f-132e-4435-9ab3-9395eef3ece6)
![image](https://github.com/Bubberstation/Bubberstation/assets/49160555/eab0a31e-c038-4bda-87dc-b1b49d88e44b)

Seems to have been fixed
