### ISSUE TITLE
Make an install guide for newbies.

### ISSUE THREAD

**Issue by xplshn** [Bubberstation/Bubberstation#806]
I am not able to find any install guide on this repo, or what I've figured out must be its game engine: Byond. Please, clarification needed.

**Comment by Arturlang** [comment]
@xplshn the guide is in one of the links on the readme, i reccomend also looking at tg wikis coding resources and tgs discords coding channel

**Comment by projectkepler-ru** [comment]
https://tgstation13.org/wiki/New_Players
