### ISSUE TITLE
(Code Bounty) Adding Vore Mechanics to Bubberstation - $600

### ISSUE THREAD

**Issue by ReturnToZender** [Bubberstation/Bubberstation#845]
With MiniusAreas pulling his funds out of the vore bounty, this is going to be the new place for it. Message maintainers if you want to be commissioned for this, but here's the current, confirmed pot:

**Zeckle: $200 
Snaffle: $100
Server: $300 (Server match up to $300) = 600**

If you would like to contribute to this pot, please message @ReturnToZender on Discord and send your contribution to the Bubberstation Ko-Fi at https://ko-fi.com/bubberhost, use the one-time donation feature, and say it's for the vore bounty.
Contributions will not be accepted past the bounty going to $600 as we'd prefer to redirect funds elsewhere at that point, though you can take over existing costs from the server if you'd like.

Payment will be released upon completion of code, marked by its merging to Bubberstation, and the bounty will involve bugfixes and maintenance later on. As much modularity as possible is desired and expected.
Design document with requirements will be prepared soon, and when ready, will be posted here.

If you believe you can finish this bounty in a reasonable amount of time (6 months or less), and want to secure your spot in completing it, please request a commission from @StrangeWeirdKitten and @ReturnToZender. We would be glad to pay up-front for a good product if you so desire. 

### Design Doc available here: 

https://docs.google.com/document/d/1ktQw26fBANHzA1A1MC2LP_uF80dYq4chNYZbb_QmKEA/edit?usp=sharing

**Comment by StrangeWeirdKitten** [comment]
## We are making a design doc first. There will be no exchange of code for funds until this is completed on our end.

Overall, I'm still open to people messaging both me and Zender, obviously. I'll keep you updated in discord.

**Comment by Arturlang** [comment]
ping me when the doc is done

**Comment by YakumoChen** [comment]
> ping me when the doc is done, and is this still going to be a virgo port?

Even skyrat wouldn't port Virgo code when rebasing under tg. The code is awful and abysmal on performance. I wholeheartedly do not recommend it.

**Comment by zeskorion** [comment]
600? dang. i'll consider it

**Comment by NullDagaf** [comment]
sure

**Comment by ReturnToZender** [comment]
Design doc reviewed by headstaff and complete @Arturlang @zeskorion

**Comment by softcerv** [comment]
I am working on this right now
https://github.com/Skyrat-SS13/Skyrat-tg/pull/24717

**Comment by ReturnToZender** [comment]
Small update: Hypnosis is no longer required for the vore bounty. It will be bountied separately.
