### ISSUE TITLE
[Bug] Virtual Domains are missing their fallback floor; open to space instead when floors are pried up

### ISSUE THREAD

**Issue by iskawhiskers** [Bubberstation/Bubberstation#886]
## Issue Summary

Normally, when prying up flooring in virtual domains, it should have a floor version of "tear in the fabric of reality"/matrix wall.  Currently, the turf is instead replaced with space, which causes rapid depressurisation.  The floor can be replaced if you have floor tiles available.

## Round ID:

3117

## Testmerges:

#625
#734
#851 
#885 
#884 
#873 
(unsure if these are related)

## Reproduction:

1. Selected the factory virtual domain, and loaded in.
2. Took crowbar, and attempted to pry up flooring.
3. Normal "matrix" turf that prevents depressurisation does not appear, and is instead space.

**Comment by projectkepler-ru** [comment]
Need to check if this occur upstream too

**Comment by Majkl-J** [comment]
Has been fixed
