### ISSUE TITLE
Port monke's Ethereal QOL

### ISSUE THREAD

**Issue by MitztheKat** [Bubberstation/Bubberstation#893]
Monkestation fixed ethereals in several ways. Lamp bois (ethereals are hence-forth referred to as from now on) currently have a very small chance each time they overcharge and send sparks out to cause heart failure. This was a fix to a wider problem of lamp bois being so easy to overcharge in cyborg chargers - any other way to overcharge them takes actual time. the [PR](https://github.com/Monkestation/Monkestation2.0/pull/148) the boys over there created solves many issues that I as a lamp boi main have with modern /TG/ lamp boi gameplay. If someone could port these, that'd be awesome, but for now my github is being a fuck and refusing to let me fork various projects

**Comment by Majkl-J** [comment]
The lamp bois can no longer overchange in in cyborg chargers so all is good with the world
