### ISSUE TITLE
Character editor's OOC notes, Flavor-text, etc, boxes don't update when switching between characters

### ISSUE THREAD

**Issue by thegrb93** [Bubberstation/Bubberstation#904]
## Issue Summary

Character editor's OOC notes, Flavor-text, etc, boxes don't update when switching between characters

## Reproduction:

Switch from one character to another and their notes will be visible instead of the selected one. Opening and closing the menu seems to be a workaround for now

**Comment by projectkepler-ru** [comment]
?

**Comment by thegrb93** [comment]
> ?

Not explained well enough or you can't reproduce it?

**Comment by thegrb93** [comment]
I'm on byond 515.1623 and my browser is firefox, maybe that is part of the issue?

**Comment by projectkepler-ru** [comment]
I didn't understand what you mean at first but I understand the actual severity of this now

**Comment by Majkl-J** [comment]
This is a tgui issue with the ui loading incorrectly, I can't catch it but seems to happen when your client lags and desyncs with the backend, leaving you with a broken UI. Reopening fixes the issue

**Comment by thegrb93** [comment]
I found the issue happening consistently and reopening didn't fix the issue. Maybe I should try stable byond.

**Comment by thegrb93** [comment]
Might also be my 100ping

**Comment by thegrb93** [comment]
It looks like skyrat also has the issue so I might move this over to them.

**Comment by thegrb93** [comment]
https://github.com/NovaSector/NovaSector/issues/162

**Comment by Majkl-J** [comment]
I will look into getting it to appear, currently can't reproduce it myself in a way where reloading the window wouldn't fix it, but if I do catch it actually happening I'll try to fix it

**Comment by thegrb93** [comment]
I think a byond updated introduced it because this didn't happen to me before I think. I noticed byond also started using other internet browsers, so it might be specific for people who have firefox as their default internet browser.

**Comment by thegrb93** [comment]
@Majkl-J looks like a fix was PR'd to TG. Just have to wait for it.

**Comment by Majkl-J** [comment]
> @Majkl-J looks like a fix was PR'd to TG. Just have to wait for it.

Gonna be watching it to violently yank it over to us the moment it's done

**Comment by thegrb93** [comment]
Should be merged in TG now

**Comment by Majkl-J** [comment]
> The fix should be merged in TG now

Yup, on it!
