### ISSUE TITLE
Dragging a contractor victim to a pod while they're on your back will drag you in as well.

### ISSUE THREAD

**Issue by Savotta** [Bubberstation/Bubberstation#907]
## Issue Summary

Dragging a contractor victim to a pod while they're on your back will drag you in as well.

## Round ID:

3133

## Testmerges:

[#625: 'Contractor and Ninja Modsuits have a deployable microbomb (Enable the DNA lock and hit Lock on the modsuit to arm)' by nevimer at commit 1a9af007c8](https://github.com/Bubberstation/Bubberstation/pull/625)
[#734: '[Modular] misc loadout edits' by ReturnToZender at commit 1d710af0dc](https://github.com/Bubberstation/Bubberstation/pull/734)
[#885: 'Makes DNR more reliable and simple again' by nevimer at commit 55c29fe016](https://github.com/Bubberstation/Bubberstation/pull/885)
[#884: 'Some tail fixes' by thegrb93 at commit 6527a3197e](https://github.com/Bubberstation/Bubberstation/pull/884)
[#873: 'adds missing raptor borg sprites & fixes raptor borg sprite eyes' by aKromatopzia at commit dc5a1971eb](https://github.com/Bubberstation/Bubberstation/pull/873)
[#851: 'NSFW Flavor Text exists, and shows on examine!' by ReturnToZender at commit b6c9b2b09a](https://github.com/Bubberstation/Bubberstation/pull/851)
[#881: 'Adds prefs to the subtler sound' by Majkl-J at commit e6414c084e](https://github.com/Bubberstation/Bubberstation/pull/881)
[#890: 'Upstream bugfixes' by StrangeWeirdKitten at commit 659fec3051](https://github.com/Bubberstation/Bubberstation/pull/890)

## Reproduction:

Drag your victim onto your back, then drag them into a syndicate pod.

**Comment by projectkepler-ru** [comment]
Check if this occurs on TG aswell @MrMelbert ?

**Comment by Odairu** [comment]
fixed by https://github.com/tgstation/tgstation/pull/85461
