### ISSUE TITLE
[BOUNTY] port vore mechanics

### ISSUE THREAD

**Issue by toastywaffelz** [Bubberstation/Bubberstation#91]
I would like:
Dogborg sleepers/recyclers to be added

A vore panel to be added

Vore/belly mechanics to be added

Ideally, you would just port the stuff from Splurt or something

Price is very negotiable

Contact me here if interested: Slugcat#1724

**Comment by Cyprex** [comment]
I'm told CHOMP has the best vorecode, might want to port that(?)

**Comment by magatsuchi** [comment]
this is not an issue
