### ISSUE TITLE
Headshot entry being overwritten

### ISSUE THREAD

**Issue by aKromatopzia** [Bubberstation/Bubberstation#917]
## Issue Summary

The headshot field in character info gets overwritten by the silicon headshot field if you have one of the latter. This seems to happen whenever the server restarts.

## Testmerges:

Definitely [#851](https://github.com/Bubberstation/Bubberstation/pull/851)

**Comment by projectkepler-ru** [comment]
May or may not be related to [NSFW Text](https://github.com/Bubberstation/Bubberstation/pull/851)
