### ISSUE TITLE
OOC -> Character Directory TGUI is broken

### ISSUE THREAD

**Issue by thegrb93** [Bubberstation/Bubberstation#939]
## Issue Summary
Seems none of the controls work in the Character Directory. Guessing TGUI updates broken it.

## Reproduction:
Open the character directory and click any of the controls.

**Comment by lessthnthree** [comment]
Fixed in https://github.com/Bubberstation/Bubberstation/pull/851

**Comment by Majkl-J** [comment]
This seems to have been fixed
