### ISSUE TITLE
Plastitanium fake walls appear invisible

### ISSUE THREAD

**Issue by tmyqlfpir** [Bubberstation/Bubberstation#940]
## Issue Summary

Constructing a fake wall with plastitanium results in an invisible wall.

## Reproduction:

Video of the issue in question.

https://github.com/Bubberstation/Bubberstation/assets/80724828/c427f33e-2594-4a6a-a2dc-99fb7920f0cb

**Comment by Sylphet** [comment]
This is the case with all false walls, excluding standard iron and reinforced. Seems to relate to the way Skyrat decided to override the TG walls in 
> modular_skyrat\modules\aesthetics\walls\code\walls.dm 

since the issue doesn't exist upstream.

**Comment by Majkl-J** [comment]
> This is the case with all false walls, excluding standard iron and reinforced. Seems to relate to the way Skyrat decided to override the TG walls in
> 
> > modular_skyrat\modules\aesthetics\walls\code\walls.dm
> 
> since the issue doesn't exist upstream.

bubber only issue, someone did a funny
