### ISSUE TITLE
Circuit window crashes when attempting to add new components

### ISSUE THREAD

**Issue by tmyqlfpir** [Bubberstation/Bubberstation#941]
## Issue Summary

The circuits dialog window will crash when attempting to load the available components. This triggers when clicking the components menu (+).

## Reproduction:

See video for example. Confirmed by other player working in science department. I have confirmed this issue happens on clients 1589 and 1620.

https://github.com/Bubberstation/Bubberstation/assets/80724828/3c2e9a86-67eb-48e9-9ffc-01419659e036

**Comment by Elli-Skala** [comment]
Already fixed on tg nova and skyrat, we updated to the bug but not the fox
