### ISSUE TITLE
One-armed characters cannot wash their hand.

### ISSUE THREAD

**Issue by MrZoraman** [Bubberstation/Bubberstation#944]
## Issue Summary

If a character only has one arm and their hand gets bloody, it will be permanently bloody. No amount of washing will return the remaining hand's icon state back to normal.
![image](https://github.com/Bubberstation/Bubberstation/assets/720034/ce013b47-0ccd-493c-9f00-27692c0b9e3d)

**Comment by Majkl-J** [comment]
Seems to have been fixed since
