### ISSUE TITLE
Space Changeling appears to fail without log.

### ISSUE THREAD

**Issue by Yawet330** [Bubberstation/Bubberstation#95]
## Testmerges:[#70: 'REMOVES DS-2' by ReturnToZender at commit f22c2468a5](https://github.com/Bubberstation/Bubberstation/pull/70)
[#48: 'Felinid Skintone Bandaid Fix' by ShamanSliph at commit 978dc63f4f](https://github.com/Bubberstation/Bubberstation/pull/48)
[#79: 'Let the Skrell DRINK' by Gr33d-y at commit 0983bf284d](https://github.com/Bubberstation/Bubberstation/pull/79)
[#93: 'enables progtot' by Gr33d-y at commit 803bd48501](https://github.com/Bubberstation/Bubberstation/pull/93)

## Reproduction:N/A

For an explaination, Space Changeling rolled, I briefly disconnected and reconnected, checked. Space Changeling proceeded to not have rolled (or spawned) and admins didn't appear to be able to find it in logs.

From what appears to have happened, it was triggered via disruptive random ruleset and attempted to poll ghosts, as I hit yes and disconnected (as the only ghost); it likely failed to find a mind and therefor failed entirely. Not sure on the details of this, but its the most likely explaination.

**Comment by Cyprex** [comment]
Should be /datum/dynamic_ruleset/midround/from_ghosts/changeling_midround

**Comment by Icarus-The-Sun** [comment]
I think this is no longer an issue on our codebase? If it isn't, this should be closed!

**Comment by magatsuchi** [comment]
upstream issue
