### ISSUE TITLE
[Request] Disable X-Rays in AI Cores

### ISSUE THREAD

**Issue by snaffle15** [Bubberstation/Bubberstation#956]
I would love to see something of this sort because we've had a few rounds and instances where the AI is defeated by an X-Ray weapon. Can we tend to that or at least create a reflector that they can craft as an engineer borg which is impervious to X-Rays?

**Comment by YakumoChen** [comment]
Do reflector mirrors not redirect them?

**Comment by Cyprex** [comment]
which weapon(s)?

**Comment by YakumoChen** [comment]
New nominally working idea: Surround the AI core with monkey(human) corpses buckled to chairs. X-ray lasers do not have PASSMOB.

**Comment by projectkepler-ru** [comment]
I am not actually sure whether or not to consider this as an issue or not, On one hand it's intended behaviour and x-ray gun isn't hard to get once researched

on the other

Yeah this is scuffed, should check upstream
